// @generated by scripts/generate_api_encoder.py from the vendored
// internal/ast/kind_generated.go and internal/api/encoder/encoder_generated.go.
// Do not edit by hand.

use tsc_syntax::{Node, NodeData, SyntaxKind};

use super::Property;

pub(crate) const KIND_IDENTIFIER: u32 = 79;
pub(crate) const KIND_STRING_LITERAL: u32 = 10;
pub(crate) const KIND_NO_SUBSTITUTION_TEMPLATE_LITERAL: u32 = 14;
pub(crate) const KIND_TEMPLATE_TAIL: u32 = 17;

/// tsgo's `Kind.String()` of each kind number.
pub(crate) const KIND_NAMES: [&str; 352] = [
    "KindUnknown",
    "KindEndOfFile",
    "KindSingleLineCommentTrivia",
    "KindMultiLineCommentTrivia",
    "KindNewLineTrivia",
    "KindWhitespaceTrivia",
    "KindConflictMarkerTrivia",
    "KindNonTextFileMarkerTrivia",
    "KindNumericLiteral",
    "KindBigIntLiteral",
    "KindStringLiteral",
    "KindJsxText",
    "KindJsxTextAllWhiteSpaces",
    "KindRegularExpressionLiteral",
    "KindNoSubstitutionTemplateLiteral",
    "KindTemplateHead",
    "KindTemplateMiddle",
    "KindTemplateTail",
    "KindOpenBraceToken",
    "KindCloseBraceToken",
    "KindOpenParenToken",
    "KindCloseParenToken",
    "KindOpenBracketToken",
    "KindCloseBracketToken",
    "KindDotToken",
    "KindDotDotDotToken",
    "KindSemicolonToken",
    "KindCommaToken",
    "KindQuestionDotToken",
    "KindLessThanToken",
    "KindLessThanSlashToken",
    "KindGreaterThanToken",
    "KindLessThanEqualsToken",
    "KindGreaterThanEqualsToken",
    "KindEqualsEqualsToken",
    "KindExclamationEqualsToken",
    "KindEqualsEqualsEqualsToken",
    "KindExclamationEqualsEqualsToken",
    "KindEqualsGreaterThanToken",
    "KindPlusToken",
    "KindMinusToken",
    "KindAsteriskToken",
    "KindAsteriskAsteriskToken",
    "KindSlashToken",
    "KindPercentToken",
    "KindPlusPlusToken",
    "KindMinusMinusToken",
    "KindLessThanLessThanToken",
    "KindGreaterThanGreaterThanToken",
    "KindGreaterThanGreaterThanGreaterThanToken",
    "KindAmpersandToken",
    "KindBarToken",
    "KindCaretToken",
    "KindExclamationToken",
    "KindTildeToken",
    "KindAmpersandAmpersandToken",
    "KindBarBarToken",
    "KindQuestionToken",
    "KindColonToken",
    "KindAtToken",
    "KindQuestionQuestionToken",
    "KindBacktickToken",
    "KindHashToken",
    "KindEqualsToken",
    "KindPlusEqualsToken",
    "KindMinusEqualsToken",
    "KindAsteriskEqualsToken",
    "KindAsteriskAsteriskEqualsToken",
    "KindSlashEqualsToken",
    "KindPercentEqualsToken",
    "KindLessThanLessThanEqualsToken",
    "KindGreaterThanGreaterThanEqualsToken",
    "KindGreaterThanGreaterThanGreaterThanEqualsToken",
    "KindAmpersandEqualsToken",
    "KindBarEqualsToken",
    "KindBarBarEqualsToken",
    "KindAmpersandAmpersandEqualsToken",
    "KindQuestionQuestionEqualsToken",
    "KindCaretEqualsToken",
    "KindIdentifier",
    "KindPrivateIdentifier",
    "KindJSDocCommentTextToken",
    "KindBreakKeyword",
    "KindCaseKeyword",
    "KindCatchKeyword",
    "KindClassKeyword",
    "KindConstKeyword",
    "KindContinueKeyword",
    "KindDebuggerKeyword",
    "KindDefaultKeyword",
    "KindDeleteKeyword",
    "KindDoKeyword",
    "KindElseKeyword",
    "KindEnumKeyword",
    "KindExportKeyword",
    "KindExtendsKeyword",
    "KindFalseKeyword",
    "KindFinallyKeyword",
    "KindForKeyword",
    "KindFunctionKeyword",
    "KindIfKeyword",
    "KindImportKeyword",
    "KindInKeyword",
    "KindInstanceOfKeyword",
    "KindNewKeyword",
    "KindNullKeyword",
    "KindReturnKeyword",
    "KindSuperKeyword",
    "KindSwitchKeyword",
    "KindThisKeyword",
    "KindThrowKeyword",
    "KindTrueKeyword",
    "KindTryKeyword",
    "KindTypeOfKeyword",
    "KindVarKeyword",
    "KindVoidKeyword",
    "KindWhileKeyword",
    "KindWithKeyword",
    "KindImplementsKeyword",
    "KindInterfaceKeyword",
    "KindLetKeyword",
    "KindPackageKeyword",
    "KindPrivateKeyword",
    "KindProtectedKeyword",
    "KindPublicKeyword",
    "KindStaticKeyword",
    "KindYieldKeyword",
    "KindAbstractKeyword",
    "KindAccessorKeyword",
    "KindAsKeyword",
    "KindAssertsKeyword",
    "KindAssertKeyword",
    "KindAnyKeyword",
    "KindAsyncKeyword",
    "KindAwaitKeyword",
    "KindBooleanKeyword",
    "KindConstructorKeyword",
    "KindDeclareKeyword",
    "KindGetKeyword",
    "KindImmediateKeyword",
    "KindInferKeyword",
    "KindIntrinsicKeyword",
    "KindIsKeyword",
    "KindKeyOfKeyword",
    "KindModuleKeyword",
    "KindNamespaceKeyword",
    "KindNeverKeyword",
    "KindOutKeyword",
    "KindReadonlyKeyword",
    "KindRequireKeyword",
    "KindNumberKeyword",
    "KindObjectKeyword",
    "KindSatisfiesKeyword",
    "KindSetKeyword",
    "KindStringKeyword",
    "KindSymbolKeyword",
    "KindTypeKeyword",
    "KindUndefinedKeyword",
    "KindUniqueKeyword",
    "KindUnknownKeyword",
    "KindUsingKeyword",
    "KindFromKeyword",
    "KindGlobalKeyword",
    "KindBigIntKeyword",
    "KindOverrideKeyword",
    "KindOfKeyword",
    "KindDeferKeyword",
    "KindQualifiedName",
    "KindComputedPropertyName",
    "KindTypeParameter",
    "KindParameter",
    "KindDecorator",
    "KindPropertySignature",
    "KindPropertyDeclaration",
    "KindMethodSignature",
    "KindMethodDeclaration",
    "KindClassStaticBlockDeclaration",
    "KindConstructor",
    "KindGetAccessor",
    "KindSetAccessor",
    "KindCallSignature",
    "KindConstructSignature",
    "KindIndexSignature",
    "KindTypePredicate",
    "KindTypeReference",
    "KindFunctionType",
    "KindConstructorType",
    "KindTypeQuery",
    "KindTypeLiteral",
    "KindArrayType",
    "KindTupleType",
    "KindOptionalType",
    "KindRestType",
    "KindUnionType",
    "KindIntersectionType",
    "KindConditionalType",
    "KindInferType",
    "KindParenthesizedType",
    "KindThisType",
    "KindTypeOperator",
    "KindIndexedAccessType",
    "KindMappedType",
    "KindLiteralType",
    "KindNamedTupleMember",
    "KindTemplateLiteralType",
    "KindTemplateLiteralTypeSpan",
    "KindImportType",
    "KindObjectBindingPattern",
    "KindArrayBindingPattern",
    "KindBindingElement",
    "KindArrayLiteralExpression",
    "KindObjectLiteralExpression",
    "KindPropertyAccessExpression",
    "KindElementAccessExpression",
    "KindCallExpression",
    "KindNewExpression",
    "KindTaggedTemplateExpression",
    "KindTypeAssertionExpression",
    "KindParenthesizedExpression",
    "KindFunctionExpression",
    "KindArrowFunction",
    "KindDeleteExpression",
    "KindTypeOfExpression",
    "KindVoidExpression",
    "KindAwaitExpression",
    "KindPrefixUnaryExpression",
    "KindPostfixUnaryExpression",
    "KindBinaryExpression",
    "KindConditionalExpression",
    "KindTemplateExpression",
    "KindYieldExpression",
    "KindSpreadElement",
    "KindClassExpression",
    "KindOmittedExpression",
    "KindExpressionWithTypeArguments",
    "KindAsExpression",
    "KindNonNullExpression",
    "KindMetaProperty",
    "KindSyntheticExpression",
    "KindSatisfiesExpression",
    "KindTemplateSpan",
    "KindSemicolonClassElement",
    "KindBlock",
    "KindEmptyStatement",
    "KindVariableStatement",
    "KindExpressionStatement",
    "KindIfStatement",
    "KindDoStatement",
    "KindWhileStatement",
    "KindForStatement",
    "KindForInStatement",
    "KindForOfStatement",
    "KindContinueStatement",
    "KindBreakStatement",
    "KindReturnStatement",
    "KindWithStatement",
    "KindSwitchStatement",
    "KindLabeledStatement",
    "KindThrowStatement",
    "KindTryStatement",
    "KindDebuggerStatement",
    "KindVariableDeclaration",
    "KindVariableDeclarationList",
    "KindFunctionDeclaration",
    "KindClassDeclaration",
    "KindInterfaceDeclaration",
    "KindTypeAliasDeclaration",
    "KindEnumDeclaration",
    "KindModuleDeclaration",
    "KindModuleBlock",
    "KindCaseBlock",
    "KindNamespaceExportDeclaration",
    "KindImportEqualsDeclaration",
    "KindImportDeclaration",
    "KindImportClause",
    "KindNamespaceImport",
    "KindNamedImports",
    "KindImportSpecifier",
    "KindExportAssignment",
    "KindExportDeclaration",
    "KindNamedExports",
    "KindNamespaceExport",
    "KindExportSpecifier",
    "KindMissingDeclaration",
    "KindExternalModuleReference",
    "KindJsxElement",
    "KindJsxSelfClosingElement",
    "KindJsxOpeningElement",
    "KindJsxClosingElement",
    "KindJsxFragment",
    "KindJsxOpeningFragment",
    "KindJsxClosingFragment",
    "KindJsxAttribute",
    "KindJsxAttributes",
    "KindJsxSpreadAttribute",
    "KindJsxExpression",
    "KindJsxNamespacedName",
    "KindCaseClause",
    "KindDefaultClause",
    "KindHeritageClause",
    "KindCatchClause",
    "KindImportAttributes",
    "KindImportAttribute",
    "KindPropertyAssignment",
    "KindShorthandPropertyAssignment",
    "KindSpreadAssignment",
    "KindEnumMember",
    "KindSourceFile",
    "KindJSDocTypeExpression",
    "KindJSDocNameReference",
    "KindJSDocAllType",
    "KindJSDocNullableType",
    "KindJSDocNonNullableType",
    "KindJSDocOptionalType",
    "KindJSDocVariadicType",
    "KindJSDoc",
    "KindJSDocText",
    "KindJSDocTypeLiteral",
    "KindJSDocSignature",
    "KindJSDocLink",
    "KindJSDocLinkCode",
    "KindJSDocLinkPlain",
    "KindJSDocUnknownTag",
    "KindJSDocAugmentsTag",
    "KindJSDocImplementsTag",
    "KindJSDocDeprecatedTag",
    "KindJSDocPublicTag",
    "KindJSDocPrivateTag",
    "KindJSDocProtectedTag",
    "KindJSDocReadonlyTag",
    "KindJSDocOverrideTag",
    "KindJSDocCallbackTag",
    "KindJSDocOverloadTag",
    "KindJSDocParameterTag",
    "KindJSDocReturnTag",
    "KindJSDocThisTag",
    "KindJSDocTypeTag",
    "KindJSDocTemplateTag",
    "KindJSDocTypedefTag",
    "KindJSDocSeeTag",
    "KindJSDocPropertyTag",
    "KindJSDocThrowsTag",
    "KindJSDocSatisfiesTag",
    "KindJSDocImportTag",
    "KindSyntaxList",
    "KindJSTypeAliasDeclaration",
    "KindJSImportDeclaration",
    "KindNotEmittedStatement",
    "KindPartiallyEmittedExpression",
    "KindSyntheticReferenceExpression",
    "KindNotEmittedTypeElement",
    "KindCount",
];

/// tsgo's kind number of a tsc-rs kind (`None`: tsgo has no such kind).
pub(crate) fn tsgo_kind(kind: SyntaxKind) -> Option<u32> {
    Some(match kind {
        SyntaxKind::Unknown => 0,
        SyntaxKind::EndOfFileToken => 1,
        SyntaxKind::SingleLineCommentTrivia => 2,
        SyntaxKind::MultiLineCommentTrivia => 3,
        SyntaxKind::NewLineTrivia => 4,
        SyntaxKind::WhitespaceTrivia => 5,
        SyntaxKind::ConflictMarkerTrivia => 6,
        SyntaxKind::NonTextFileMarkerTrivia => 7,
        SyntaxKind::NumericLiteral => 8,
        SyntaxKind::BigIntLiteral => 9,
        SyntaxKind::StringLiteral => 10,
        SyntaxKind::JsxText => 11,
        SyntaxKind::JsxTextAllWhiteSpaces => 12,
        SyntaxKind::RegularExpressionLiteral => 13,
        SyntaxKind::NoSubstitutionTemplateLiteral => 14,
        SyntaxKind::TemplateHead => 15,
        SyntaxKind::TemplateMiddle => 16,
        SyntaxKind::TemplateTail => 17,
        SyntaxKind::OpenBraceToken => 18,
        SyntaxKind::CloseBraceToken => 19,
        SyntaxKind::OpenParenToken => 20,
        SyntaxKind::CloseParenToken => 21,
        SyntaxKind::OpenBracketToken => 22,
        SyntaxKind::CloseBracketToken => 23,
        SyntaxKind::DotToken => 24,
        SyntaxKind::DotDotDotToken => 25,
        SyntaxKind::SemicolonToken => 26,
        SyntaxKind::CommaToken => 27,
        SyntaxKind::QuestionDotToken => 28,
        SyntaxKind::LessThanToken => 29,
        SyntaxKind::LessThanSlashToken => 30,
        SyntaxKind::GreaterThanToken => 31,
        SyntaxKind::LessThanEqualsToken => 32,
        SyntaxKind::GreaterThanEqualsToken => 33,
        SyntaxKind::EqualsEqualsToken => 34,
        SyntaxKind::ExclamationEqualsToken => 35,
        SyntaxKind::EqualsEqualsEqualsToken => 36,
        SyntaxKind::ExclamationEqualsEqualsToken => 37,
        SyntaxKind::EqualsGreaterThanToken => 38,
        SyntaxKind::PlusToken => 39,
        SyntaxKind::MinusToken => 40,
        SyntaxKind::AsteriskToken => 41,
        SyntaxKind::AsteriskAsteriskToken => 42,
        SyntaxKind::SlashToken => 43,
        SyntaxKind::PercentToken => 44,
        SyntaxKind::PlusPlusToken => 45,
        SyntaxKind::MinusMinusToken => 46,
        SyntaxKind::LessThanLessThanToken => 47,
        SyntaxKind::GreaterThanGreaterThanToken => 48,
        SyntaxKind::GreaterThanGreaterThanGreaterThanToken => 49,
        SyntaxKind::AmpersandToken => 50,
        SyntaxKind::BarToken => 51,
        SyntaxKind::CaretToken => 52,
        SyntaxKind::ExclamationToken => 53,
        SyntaxKind::TildeToken => 54,
        SyntaxKind::AmpersandAmpersandToken => 55,
        SyntaxKind::BarBarToken => 56,
        SyntaxKind::QuestionToken => 57,
        SyntaxKind::ColonToken => 58,
        SyntaxKind::AtToken => 59,
        SyntaxKind::QuestionQuestionToken => 60,
        SyntaxKind::BacktickToken => 61,
        SyntaxKind::HashToken => 62,
        SyntaxKind::EqualsToken => 63,
        SyntaxKind::PlusEqualsToken => 64,
        SyntaxKind::MinusEqualsToken => 65,
        SyntaxKind::AsteriskEqualsToken => 66,
        SyntaxKind::AsteriskAsteriskEqualsToken => 67,
        SyntaxKind::SlashEqualsToken => 68,
        SyntaxKind::PercentEqualsToken => 69,
        SyntaxKind::LessThanLessThanEqualsToken => 70,
        SyntaxKind::GreaterThanGreaterThanEqualsToken => 71,
        SyntaxKind::GreaterThanGreaterThanGreaterThanEqualsToken => 72,
        SyntaxKind::AmpersandEqualsToken => 73,
        SyntaxKind::BarEqualsToken => 74,
        SyntaxKind::BarBarEqualsToken => 75,
        SyntaxKind::AmpersandAmpersandEqualsToken => 76,
        SyntaxKind::QuestionQuestionEqualsToken => 77,
        SyntaxKind::CaretEqualsToken => 78,
        SyntaxKind::Identifier => 79,
        SyntaxKind::PrivateIdentifier => 80,
        SyntaxKind::JSDocCommentTextToken => 81,
        SyntaxKind::BreakKeyword => 82,
        SyntaxKind::CaseKeyword => 83,
        SyntaxKind::CatchKeyword => 84,
        SyntaxKind::ClassKeyword => 85,
        SyntaxKind::ConstKeyword => 86,
        SyntaxKind::ContinueKeyword => 87,
        SyntaxKind::DebuggerKeyword => 88,
        SyntaxKind::DefaultKeyword => 89,
        SyntaxKind::DeleteKeyword => 90,
        SyntaxKind::DoKeyword => 91,
        SyntaxKind::ElseKeyword => 92,
        SyntaxKind::EnumKeyword => 93,
        SyntaxKind::ExportKeyword => 94,
        SyntaxKind::ExtendsKeyword => 95,
        SyntaxKind::FalseKeyword => 96,
        SyntaxKind::FinallyKeyword => 97,
        SyntaxKind::ForKeyword => 98,
        SyntaxKind::FunctionKeyword => 99,
        SyntaxKind::IfKeyword => 100,
        SyntaxKind::ImportKeyword => 101,
        SyntaxKind::InKeyword => 102,
        SyntaxKind::InstanceOfKeyword => 103,
        SyntaxKind::NewKeyword => 104,
        SyntaxKind::NullKeyword => 105,
        SyntaxKind::ReturnKeyword => 106,
        SyntaxKind::SuperKeyword => 107,
        SyntaxKind::SwitchKeyword => 108,
        SyntaxKind::ThisKeyword => 109,
        SyntaxKind::ThrowKeyword => 110,
        SyntaxKind::TrueKeyword => 111,
        SyntaxKind::TryKeyword => 112,
        SyntaxKind::TypeOfKeyword => 113,
        SyntaxKind::VarKeyword => 114,
        SyntaxKind::VoidKeyword => 115,
        SyntaxKind::WhileKeyword => 116,
        SyntaxKind::WithKeyword => 117,
        SyntaxKind::ImplementsKeyword => 118,
        SyntaxKind::InterfaceKeyword => 119,
        SyntaxKind::LetKeyword => 120,
        SyntaxKind::PackageKeyword => 121,
        SyntaxKind::PrivateKeyword => 122,
        SyntaxKind::ProtectedKeyword => 123,
        SyntaxKind::PublicKeyword => 124,
        SyntaxKind::StaticKeyword => 125,
        SyntaxKind::YieldKeyword => 126,
        SyntaxKind::AbstractKeyword => 127,
        SyntaxKind::AccessorKeyword => 128,
        SyntaxKind::AsKeyword => 129,
        SyntaxKind::AssertsKeyword => 130,
        SyntaxKind::AssertKeyword => 131,
        SyntaxKind::AnyKeyword => 132,
        SyntaxKind::AsyncKeyword => 133,
        SyntaxKind::AwaitKeyword => 134,
        SyntaxKind::BooleanKeyword => 135,
        SyntaxKind::ConstructorKeyword => 136,
        SyntaxKind::DeclareKeyword => 137,
        SyntaxKind::GetKeyword => 138,
        SyntaxKind::InferKeyword => 140,
        SyntaxKind::IntrinsicKeyword => 141,
        SyntaxKind::IsKeyword => 142,
        SyntaxKind::KeyOfKeyword => 143,
        SyntaxKind::ModuleKeyword => 144,
        SyntaxKind::NamespaceKeyword => 145,
        SyntaxKind::NeverKeyword => 146,
        SyntaxKind::OutKeyword => 147,
        SyntaxKind::ReadonlyKeyword => 148,
        SyntaxKind::RequireKeyword => 149,
        SyntaxKind::NumberKeyword => 150,
        SyntaxKind::ObjectKeyword => 151,
        SyntaxKind::SatisfiesKeyword => 152,
        SyntaxKind::SetKeyword => 153,
        SyntaxKind::StringKeyword => 154,
        SyntaxKind::SymbolKeyword => 155,
        SyntaxKind::TypeKeyword => 156,
        SyntaxKind::UndefinedKeyword => 157,
        SyntaxKind::UniqueKeyword => 158,
        SyntaxKind::UnknownKeyword => 159,
        SyntaxKind::UsingKeyword => 160,
        SyntaxKind::FromKeyword => 161,
        SyntaxKind::GlobalKeyword => 162,
        SyntaxKind::BigIntKeyword => 163,
        SyntaxKind::OverrideKeyword => 164,
        SyntaxKind::OfKeyword => 165,
        SyntaxKind::DeferKeyword => 166,
        SyntaxKind::QualifiedName => 167,
        SyntaxKind::ComputedPropertyName => 168,
        SyntaxKind::TypeParameter => 169,
        SyntaxKind::Parameter => 170,
        SyntaxKind::Decorator => 171,
        SyntaxKind::PropertySignature => 172,
        SyntaxKind::PropertyDeclaration => 173,
        SyntaxKind::MethodSignature => 174,
        SyntaxKind::MethodDeclaration => 175,
        SyntaxKind::ClassStaticBlockDeclaration => 176,
        SyntaxKind::Constructor => 177,
        SyntaxKind::GetAccessor => 178,
        SyntaxKind::SetAccessor => 179,
        SyntaxKind::CallSignature => 180,
        SyntaxKind::ConstructSignature => 181,
        SyntaxKind::IndexSignature => 182,
        SyntaxKind::TypePredicate => 183,
        SyntaxKind::TypeReference => 184,
        SyntaxKind::FunctionType => 185,
        SyntaxKind::ConstructorType => 186,
        SyntaxKind::TypeQuery => 187,
        SyntaxKind::TypeLiteral => 188,
        SyntaxKind::ArrayType => 189,
        SyntaxKind::TupleType => 190,
        SyntaxKind::OptionalType => 191,
        SyntaxKind::RestType => 192,
        SyntaxKind::UnionType => 193,
        SyntaxKind::IntersectionType => 194,
        SyntaxKind::ConditionalType => 195,
        SyntaxKind::InferType => 196,
        SyntaxKind::ParenthesizedType => 197,
        SyntaxKind::ThisType => 198,
        SyntaxKind::TypeOperator => 199,
        SyntaxKind::IndexedAccessType => 200,
        SyntaxKind::MappedType => 201,
        SyntaxKind::LiteralType => 202,
        SyntaxKind::NamedTupleMember => 203,
        SyntaxKind::TemplateLiteralType => 204,
        SyntaxKind::TemplateLiteralTypeSpan => 205,
        SyntaxKind::ImportType => 206,
        SyntaxKind::ObjectBindingPattern => 207,
        SyntaxKind::ArrayBindingPattern => 208,
        SyntaxKind::BindingElement => 209,
        SyntaxKind::ArrayLiteralExpression => 210,
        SyntaxKind::ObjectLiteralExpression => 211,
        SyntaxKind::PropertyAccessExpression => 212,
        SyntaxKind::ElementAccessExpression => 213,
        SyntaxKind::CallExpression => 214,
        SyntaxKind::NewExpression => 215,
        SyntaxKind::TaggedTemplateExpression => 216,
        SyntaxKind::TypeAssertionExpression => 217,
        SyntaxKind::ParenthesizedExpression => 218,
        SyntaxKind::FunctionExpression => 219,
        SyntaxKind::ArrowFunction => 220,
        SyntaxKind::DeleteExpression => 221,
        SyntaxKind::TypeOfExpression => 222,
        SyntaxKind::VoidExpression => 223,
        SyntaxKind::AwaitExpression => 224,
        SyntaxKind::PrefixUnaryExpression => 225,
        SyntaxKind::PostfixUnaryExpression => 226,
        SyntaxKind::BinaryExpression => 227,
        SyntaxKind::ConditionalExpression => 228,
        SyntaxKind::TemplateExpression => 229,
        SyntaxKind::YieldExpression => 230,
        SyntaxKind::SpreadElement => 231,
        SyntaxKind::ClassExpression => 232,
        SyntaxKind::OmittedExpression => 233,
        SyntaxKind::ExpressionWithTypeArguments => 234,
        SyntaxKind::AsExpression => 235,
        SyntaxKind::NonNullExpression => 236,
        SyntaxKind::MetaProperty => 237,
        SyntaxKind::SyntheticExpression => 238,
        SyntaxKind::SatisfiesExpression => 239,
        SyntaxKind::TemplateSpan => 240,
        SyntaxKind::SemicolonClassElement => 241,
        SyntaxKind::Block => 242,
        SyntaxKind::EmptyStatement => 243,
        SyntaxKind::VariableStatement => 244,
        SyntaxKind::ExpressionStatement => 245,
        SyntaxKind::IfStatement => 246,
        SyntaxKind::DoStatement => 247,
        SyntaxKind::WhileStatement => 248,
        SyntaxKind::ForStatement => 249,
        SyntaxKind::ForInStatement => 250,
        SyntaxKind::ForOfStatement => 251,
        SyntaxKind::ContinueStatement => 252,
        SyntaxKind::BreakStatement => 253,
        SyntaxKind::ReturnStatement => 254,
        SyntaxKind::WithStatement => 255,
        SyntaxKind::SwitchStatement => 256,
        SyntaxKind::LabeledStatement => 257,
        SyntaxKind::ThrowStatement => 258,
        SyntaxKind::TryStatement => 259,
        SyntaxKind::DebuggerStatement => 260,
        SyntaxKind::VariableDeclaration => 261,
        SyntaxKind::VariableDeclarationList => 262,
        SyntaxKind::FunctionDeclaration => 263,
        SyntaxKind::ClassDeclaration => 264,
        SyntaxKind::InterfaceDeclaration => 265,
        SyntaxKind::TypeAliasDeclaration => 266,
        SyntaxKind::EnumDeclaration => 267,
        SyntaxKind::ModuleDeclaration => 268,
        SyntaxKind::ModuleBlock => 269,
        SyntaxKind::CaseBlock => 270,
        SyntaxKind::NamespaceExportDeclaration => 271,
        SyntaxKind::ImportEqualsDeclaration => 272,
        SyntaxKind::ImportDeclaration => 273,
        SyntaxKind::ImportClause => 274,
        SyntaxKind::NamespaceImport => 275,
        SyntaxKind::NamedImports => 276,
        SyntaxKind::ImportSpecifier => 277,
        SyntaxKind::ExportAssignment => 278,
        SyntaxKind::ExportDeclaration => 279,
        SyntaxKind::NamedExports => 280,
        SyntaxKind::NamespaceExport => 281,
        SyntaxKind::ExportSpecifier => 282,
        SyntaxKind::MissingDeclaration => 283,
        SyntaxKind::ExternalModuleReference => 284,
        SyntaxKind::JsxElement => 285,
        SyntaxKind::JsxSelfClosingElement => 286,
        SyntaxKind::JsxOpeningElement => 287,
        SyntaxKind::JsxClosingElement => 288,
        SyntaxKind::JsxFragment => 289,
        SyntaxKind::JsxOpeningFragment => 290,
        SyntaxKind::JsxClosingFragment => 291,
        SyntaxKind::JsxAttribute => 292,
        SyntaxKind::JsxAttributes => 293,
        SyntaxKind::JsxSpreadAttribute => 294,
        SyntaxKind::JsxExpression => 295,
        SyntaxKind::JsxNamespacedName => 296,
        SyntaxKind::CaseClause => 297,
        SyntaxKind::DefaultClause => 298,
        SyntaxKind::HeritageClause => 299,
        SyntaxKind::CatchClause => 300,
        SyntaxKind::ImportAttributes => 301,
        SyntaxKind::ImportAttribute => 302,
        SyntaxKind::PropertyAssignment => 303,
        SyntaxKind::ShorthandPropertyAssignment => 304,
        SyntaxKind::SpreadAssignment => 305,
        SyntaxKind::EnumMember => 306,
        SyntaxKind::SourceFile => 307,
        SyntaxKind::JSDocTypeExpression => 308,
        SyntaxKind::JSDocNameReference => 309,
        SyntaxKind::JSDocAllType => 310,
        SyntaxKind::JSDocNullableType => 311,
        SyntaxKind::JSDocNonNullableType => 312,
        SyntaxKind::JSDocOptionalType => 313,
        SyntaxKind::JSDocVariadicType => 314,
        SyntaxKind::JSDoc => 315,
        SyntaxKind::JSDocText => 316,
        SyntaxKind::JSDocTypeLiteral => 317,
        SyntaxKind::JSDocSignature => 318,
        SyntaxKind::JSDocLink => 319,
        SyntaxKind::JSDocLinkCode => 320,
        SyntaxKind::JSDocLinkPlain => 321,
        SyntaxKind::JSDocTag => 322,
        SyntaxKind::JSDocAugmentsTag => 323,
        SyntaxKind::JSDocImplementsTag => 324,
        SyntaxKind::JSDocDeprecatedTag => 325,
        SyntaxKind::JSDocPublicTag => 326,
        SyntaxKind::JSDocPrivateTag => 327,
        SyntaxKind::JSDocProtectedTag => 328,
        SyntaxKind::JSDocReadonlyTag => 329,
        SyntaxKind::JSDocOverrideTag => 330,
        SyntaxKind::JSDocCallbackTag => 331,
        SyntaxKind::JSDocOverloadTag => 332,
        SyntaxKind::JSDocParameterTag => 333,
        SyntaxKind::JSDocReturnTag => 334,
        SyntaxKind::JSDocThisTag => 335,
        SyntaxKind::JSDocTypeTag => 336,
        SyntaxKind::JSDocTemplateTag => 337,
        SyntaxKind::JSDocTypedefTag => 338,
        SyntaxKind::JSDocSeeTag => 339,
        SyntaxKind::JSDocPropertyTag => 340,
        SyntaxKind::JSDocThrowsTag => 341,
        SyntaxKind::JSDocSatisfiesTag => 342,
        SyntaxKind::JSDocImportTag => 343,
        SyntaxKind::SyntaxList => 344,
        SyntaxKind::NotEmittedStatement => 347,
        SyntaxKind::NotEmittedTypeElement => 350,
        SyntaxKind::PartiallyEmittedExpression => 348,
        SyntaxKind::SyntheticReferenceExpression => 349,
        SyntaxKind::Count => 351,
        _ => return None,
    })
}

/// tsgo `getNodeDataType` of a tsgo kind number.
pub(crate) fn node_data_type(kind: u32) -> u32 {
    match kind {
        8 | 9 | 10 | 13 | 14 | 15 | 16 | 17 | 307 => super::NODE_DATA_TYPE_EXTENDED_DATA,
        11 | 79 | 80 | 316 | 319 | 320 | 321 => super::NODE_DATA_TYPE_STRING,
        _ => super::NODE_DATA_TYPE_CHILDREN,
    }
}

/// The child properties tsgo's encoder visits on `node`, in visitor order
/// (`getChildrenPropertyMask`'s bits); a node with none calls nothing.
pub(crate) fn for_each_property<'a>(node: &'a Node, mut f: impl FnMut(Property<'a>)) {
    match &node.data {
        NodeData::QualifiedName(d) => {
            f(Property::Node(d.left));
            f(Property::Node(d.right));
        }
        NodeData::ComputedPropertyName(d) => {
            f(Property::Node(d.expression));
        }
        NodeData::TypeParameter(d) => {
            f(Property::Modifiers(d.modifiers));
            f(Property::Node(d.name));
            f(Property::Node(d.constraint));
            f(Property::Node(d.expression));
            f(Property::Node(d.r#default));
        }
        NodeData::Parameter(d) => {
            f(Property::Modifiers(d.modifiers));
            f(Property::Node(d.dot_dot_dot_token));
            f(Property::Node(d.name));
            f(Property::Node(d.question_token));
            f(Property::Node(d.r#type));
            f(Property::Node(d.initializer));
        }
        NodeData::Decorator(d) => {
            f(Property::Node(d.expression));
        }
        NodeData::PropertySignature(d) => {
            f(Property::Modifiers(d.modifiers));
            f(Property::Node(d.name));
            f(Property::Node(d.question_token));
            f(Property::Node(d.r#type));
            f(Property::Node(d.initializer));
        }
        NodeData::PropertyDeclaration(d) => {
            f(Property::Modifiers(d.modifiers));
            f(Property::Node(d.name));
            f(Property::Node(d.question_token.or(d.exclamation_token)));
            f(Property::Node(d.r#type));
            f(Property::Node(d.initializer));
        }
        NodeData::MethodSignature(d) => {
            f(Property::Modifiers(d.modifiers));
            f(Property::Node(d.name));
            f(Property::Node(d.question_token));
            f(Property::List(d.type_parameters));
            f(Property::List(d.parameters));
            f(Property::Node(d.r#type));
        }
        NodeData::MethodDeclaration(d) => {
            f(Property::Modifiers(d.modifiers));
            f(Property::Node(d.asterisk_token));
            f(Property::Node(d.name));
            f(Property::Node(d.question_token.or(d.exclamation_token)));
            f(Property::List(d.type_parameters));
            f(Property::List(d.parameters));
            f(Property::Node(d.r#type));
            f(Property::Node(d.body));
        }
        NodeData::ClassStaticBlockDeclaration(d) => {
            f(Property::Modifiers(d.modifiers));
            f(Property::Node(d.body));
        }
        NodeData::Constructor(d) => {
            f(Property::Modifiers(d.modifiers));
            f(Property::List(d.type_parameters));
            f(Property::List(d.parameters));
            f(Property::Node(d.r#type));
            f(Property::Node(d.body));
        }
        NodeData::GetAccessor(d) => {
            f(Property::Modifiers(d.modifiers));
            f(Property::Node(d.name));
            f(Property::List(d.type_parameters));
            f(Property::List(d.parameters));
            f(Property::Node(d.r#type));
            f(Property::Node(d.body));
        }
        NodeData::SetAccessor(d) => {
            f(Property::Modifiers(d.modifiers));
            f(Property::Node(d.name));
            f(Property::List(d.type_parameters));
            f(Property::List(d.parameters));
            f(Property::Node(d.r#type));
            f(Property::Node(d.body));
        }
        NodeData::CallSignature(d) => {
            f(Property::List(d.type_parameters));
            f(Property::List(d.parameters));
            f(Property::Node(d.r#type));
        }
        NodeData::ConstructSignature(d) => {
            f(Property::List(d.type_parameters));
            f(Property::List(d.parameters));
            f(Property::Node(d.r#type));
        }
        NodeData::IndexSignature(d) => {
            f(Property::Modifiers(d.modifiers));
            f(Property::List(d.parameters));
            f(Property::Node(d.r#type));
        }
        NodeData::TypePredicate(d) => {
            f(Property::Node(d.asserts_modifier));
            f(Property::Node(d.parameter_name));
            f(Property::Node(d.r#type));
        }
        NodeData::TypeReference(d) => {
            f(Property::Node(d.type_name));
            f(Property::List(d.type_arguments));
        }
        NodeData::FunctionType(d) => {
            f(Property::List(d.type_parameters));
            f(Property::List(d.parameters));
            f(Property::Node(d.r#type));
        }
        NodeData::ConstructorType(d) => {
            f(Property::Modifiers(d.modifiers));
            f(Property::List(d.type_parameters));
            f(Property::List(d.parameters));
            f(Property::Node(d.r#type));
        }
        NodeData::TypeQuery(d) => {
            f(Property::Node(d.expr_name));
            f(Property::List(d.type_arguments));
        }
        NodeData::TypeLiteral(d) => {
            f(Property::List(d.members));
        }
        NodeData::ArrayType(d) => {
            f(Property::Node(d.element_type));
        }
        NodeData::TupleType(d) => {
            f(Property::List(d.elements));
        }
        NodeData::OptionalType(d) => {
            f(Property::Node(d.r#type));
        }
        NodeData::RestType(d) => {
            f(Property::Node(d.r#type));
        }
        NodeData::UnionType(d) => {
            f(Property::List(d.types));
        }
        NodeData::IntersectionType(d) => {
            f(Property::List(d.types));
        }
        NodeData::ConditionalType(d) => {
            f(Property::Node(d.check_type));
            f(Property::Node(d.extends_type));
            f(Property::Node(d.true_type));
            f(Property::Node(d.false_type));
        }
        NodeData::InferType(d) => {
            f(Property::Node(d.type_parameter));
        }
        NodeData::ParenthesizedType(d) => {
            f(Property::Node(d.r#type));
        }
        NodeData::TypeOperator(d) => {
            f(Property::Node(d.r#type));
        }
        NodeData::IndexedAccessType(d) => {
            f(Property::Node(d.object_type));
            f(Property::Node(d.index_type));
        }
        NodeData::MappedType(d) => {
            f(Property::Node(d.readonly_token));
            f(Property::Node(d.type_parameter));
            f(Property::Node(d.name_type));
            f(Property::Node(d.question_token));
            f(Property::Node(d.r#type));
            f(Property::List(d.members));
        }
        NodeData::LiteralType(d) => {
            f(Property::Node(d.literal));
        }
        NodeData::NamedTupleMember(d) => {
            f(Property::Node(d.dot_dot_dot_token));
            f(Property::Node(d.name));
            f(Property::Node(d.question_token));
            f(Property::Node(d.r#type));
        }
        NodeData::TemplateLiteralType(d) => {
            f(Property::Node(d.head));
            f(Property::List(d.template_spans));
        }
        NodeData::TemplateLiteralTypeSpan(d) => {
            f(Property::Node(d.r#type));
            f(Property::Node(d.literal));
        }
        NodeData::ImportType(d) => {
            f(Property::Node(d.argument));
            f(Property::Node(d.attributes));
            f(Property::Node(d.qualifier));
            f(Property::List(d.type_arguments));
        }
        NodeData::ObjectBindingPattern(d) => {
            f(Property::List(d.elements));
        }
        NodeData::ArrayBindingPattern(d) => {
            f(Property::List(d.elements));
        }
        NodeData::BindingElement(d) => {
            f(Property::Node(d.dot_dot_dot_token));
            f(Property::Node(d.property_name));
            f(Property::Node(d.name));
            f(Property::Node(d.initializer));
        }
        NodeData::ArrayLiteralExpression(d) => {
            f(Property::List(d.elements));
        }
        NodeData::ObjectLiteralExpression(d) => {
            f(Property::List(d.properties));
        }
        NodeData::PropertyAccessExpression(d) => {
            f(Property::Node(d.expression));
            f(Property::Node(d.question_dot_token));
            f(Property::Node(d.name));
        }
        NodeData::ElementAccessExpression(d) => {
            f(Property::Node(d.expression));
            f(Property::Node(d.question_dot_token));
            f(Property::Node(d.argument_expression));
        }
        NodeData::CallExpression(d) => {
            f(Property::Node(d.expression));
            f(Property::Node(d.question_dot_token));
            f(Property::List(d.type_arguments));
            f(Property::List(d.arguments));
        }
        NodeData::NewExpression(d) => {
            f(Property::Node(d.expression));
            f(Property::List(d.type_arguments));
            f(Property::List(d.arguments));
        }
        NodeData::TaggedTemplateExpression(d) => {
            f(Property::Node(d.tag));
            f(Property::Node(d.question_dot_token));
            f(Property::List(d.type_arguments));
            f(Property::Node(d.template));
        }
        NodeData::TypeAssertionExpression(d) => {
            f(Property::Node(d.r#type));
            f(Property::Node(d.expression));
        }
        NodeData::ParenthesizedExpression(d) => {
            f(Property::Node(d.expression));
        }
        NodeData::FunctionExpression(d) => {
            f(Property::Modifiers(d.modifiers));
            f(Property::Node(d.asterisk_token));
            f(Property::Node(d.name));
            f(Property::List(d.type_parameters));
            f(Property::List(d.parameters));
            f(Property::Node(d.r#type));
            f(Property::Node(d.body));
        }
        NodeData::ArrowFunction(d) => {
            f(Property::Modifiers(d.modifiers));
            f(Property::List(d.type_parameters));
            f(Property::List(d.parameters));
            f(Property::Node(d.r#type));
            f(Property::Node(d.equals_greater_than_token));
            f(Property::Node(d.body));
        }
        NodeData::DeleteExpression(d) => {
            f(Property::Node(d.expression));
        }
        NodeData::TypeOfExpression(d) => {
            f(Property::Node(d.expression));
        }
        NodeData::VoidExpression(d) => {
            f(Property::Node(d.expression));
        }
        NodeData::AwaitExpression(d) => {
            f(Property::Node(d.expression));
        }
        NodeData::PrefixUnaryExpression(d) => {
            f(Property::Node(d.operand));
        }
        NodeData::PostfixUnaryExpression(d) => {
            f(Property::Node(d.operand));
        }
        NodeData::BinaryExpression(d) => {
            f(Property::Node(None));
            f(Property::Node(d.left));
            f(Property::Node(None));
            f(Property::Node(d.operator_token));
            f(Property::Node(d.right));
        }
        NodeData::ConditionalExpression(d) => {
            f(Property::Node(d.condition));
            f(Property::Node(d.question_token));
            f(Property::Node(d.when_true));
            f(Property::Node(d.colon_token));
            f(Property::Node(d.when_false));
        }
        NodeData::TemplateExpression(d) => {
            f(Property::Node(d.head));
            f(Property::List(d.template_spans));
        }
        NodeData::YieldExpression(d) => {
            f(Property::Node(d.asterisk_token));
            f(Property::Node(d.expression));
        }
        NodeData::SpreadElement(d) => {
            f(Property::Node(d.expression));
        }
        NodeData::ClassExpression(d) => {
            f(Property::Modifiers(d.modifiers));
            f(Property::Node(d.name));
            f(Property::List(d.type_parameters));
            f(Property::List(d.heritage_clauses));
            f(Property::List(d.members));
        }
        NodeData::ExpressionWithTypeArguments(d) => {
            f(Property::Node(d.expression));
            f(Property::List(d.type_arguments));
        }
        NodeData::AsExpression(d) => {
            f(Property::Node(d.expression));
            f(Property::Node(d.r#type));
        }
        NodeData::NonNullExpression(d) => {
            f(Property::Node(d.expression));
        }
        NodeData::MetaProperty(d) => {
            f(Property::Node(d.name));
        }
        NodeData::SatisfiesExpression(d) => {
            f(Property::Node(d.expression));
            f(Property::Node(d.r#type));
        }
        NodeData::TemplateSpan(d) => {
            f(Property::Node(d.expression));
            f(Property::Node(d.literal));
        }
        NodeData::Block(d) => {
            f(Property::List(d.statements));
        }
        NodeData::VariableStatement(d) => {
            f(Property::Modifiers(d.modifiers));
            f(Property::Node(d.declaration_list));
        }
        NodeData::ExpressionStatement(d) => {
            f(Property::Node(d.expression));
        }
        NodeData::IfStatement(d) => {
            f(Property::Node(d.expression));
            f(Property::Node(d.then_statement));
            f(Property::Node(d.else_statement));
        }
        NodeData::DoStatement(d) => {
            f(Property::Node(d.statement));
            f(Property::Node(d.expression));
        }
        NodeData::WhileStatement(d) => {
            f(Property::Node(d.expression));
            f(Property::Node(d.statement));
        }
        NodeData::ForStatement(d) => {
            f(Property::Node(d.initializer));
            f(Property::Node(d.condition));
            f(Property::Node(d.incrementor));
            f(Property::Node(d.statement));
        }
        NodeData::ForInStatement(d) => {
            f(Property::Node(None));
            f(Property::Node(d.initializer));
            f(Property::Node(d.expression));
            f(Property::Node(d.statement));
        }
        NodeData::ForOfStatement(d) => {
            f(Property::Node(d.await_modifier));
            f(Property::Node(d.initializer));
            f(Property::Node(d.expression));
            f(Property::Node(d.statement));
        }
        NodeData::ContinueStatement(d) => {
            f(Property::Node(d.label));
        }
        NodeData::BreakStatement(d) => {
            f(Property::Node(d.label));
        }
        NodeData::ReturnStatement(d) => {
            f(Property::Node(d.expression));
        }
        NodeData::WithStatement(d) => {
            f(Property::Node(d.expression));
            f(Property::Node(d.statement));
        }
        NodeData::SwitchStatement(d) => {
            f(Property::Node(d.expression));
            f(Property::Node(d.case_block));
        }
        NodeData::LabeledStatement(d) => {
            f(Property::Node(d.label));
            f(Property::Node(d.statement));
        }
        NodeData::ThrowStatement(d) => {
            f(Property::Node(d.expression));
        }
        NodeData::TryStatement(d) => {
            f(Property::Node(d.try_block));
            f(Property::Node(d.catch_clause));
            f(Property::Node(d.finally_block));
        }
        NodeData::VariableDeclaration(d) => {
            f(Property::Node(d.name));
            f(Property::Node(d.exclamation_token));
            f(Property::Node(d.r#type));
            f(Property::Node(d.initializer));
        }
        NodeData::VariableDeclarationList(d) => {
            f(Property::List(d.declarations));
        }
        NodeData::FunctionDeclaration(d) => {
            f(Property::Modifiers(d.modifiers));
            f(Property::Node(d.asterisk_token));
            f(Property::Node(d.name));
            f(Property::List(d.type_parameters));
            f(Property::List(d.parameters));
            f(Property::Node(d.r#type));
            f(Property::Node(d.body));
        }
        NodeData::ClassDeclaration(d) => {
            f(Property::Modifiers(d.modifiers));
            f(Property::Node(d.name));
            f(Property::List(d.type_parameters));
            f(Property::List(d.heritage_clauses));
            f(Property::List(d.members));
        }
        NodeData::InterfaceDeclaration(d) => {
            f(Property::Modifiers(d.modifiers));
            f(Property::Node(d.name));
            f(Property::List(d.type_parameters));
            f(Property::List(d.heritage_clauses));
            f(Property::List(d.members));
        }
        NodeData::TypeAliasDeclaration(d) => {
            f(Property::Modifiers(d.modifiers));
            f(Property::Node(d.name));
            f(Property::List(d.type_parameters));
            f(Property::Node(d.r#type));
        }
        NodeData::EnumDeclaration(d) => {
            f(Property::Modifiers(d.modifiers));
            f(Property::Node(d.name));
            f(Property::List(d.members));
        }
        NodeData::ModuleDeclaration(d) => {
            f(Property::Modifiers(d.modifiers));
            f(Property::Node(d.name));
            f(Property::Node(d.attributes));
            f(Property::Node(d.body));
        }
        NodeData::ModuleBlock(d) => {
            f(Property::List(d.statements));
        }
        NodeData::CaseBlock(d) => {
            f(Property::List(d.clauses));
        }
        NodeData::NamespaceExportDeclaration(d) => {
            f(Property::Modifiers(d.modifiers));
            f(Property::Node(d.name));
        }
        NodeData::ImportEqualsDeclaration(d) => {
            f(Property::Modifiers(d.modifiers));
            f(Property::Node(d.name));
            f(Property::Node(d.module_reference));
        }
        NodeData::ImportDeclaration(d) => {
            f(Property::Modifiers(d.modifiers));
            f(Property::Node(d.import_clause));
            f(Property::Node(d.module_specifier));
            f(Property::Node(d.attributes));
        }
        NodeData::ImportClause(d) => {
            f(Property::Node(d.name));
            f(Property::Node(d.named_bindings));
        }
        NodeData::NamespaceImport(d) => {
            f(Property::Node(d.name));
        }
        NodeData::NamedImports(d) => {
            f(Property::List(d.elements));
        }
        NodeData::ImportSpecifier(d) => {
            f(Property::Node(d.property_name));
            f(Property::Node(d.name));
        }
        NodeData::ExportAssignment(d) => {
            f(Property::Modifiers(d.modifiers));
            f(Property::Node(None));
            f(Property::Node(d.expression));
        }
        NodeData::ExportDeclaration(d) => {
            f(Property::Modifiers(d.modifiers));
            f(Property::Node(d.export_clause));
            f(Property::Node(d.module_specifier));
            f(Property::Node(d.attributes));
        }
        NodeData::NamedExports(d) => {
            f(Property::List(d.elements));
        }
        NodeData::NamespaceExport(d) => {
            f(Property::Node(d.name));
        }
        NodeData::ExportSpecifier(d) => {
            f(Property::Node(d.property_name));
            f(Property::Node(d.name));
        }
        NodeData::MissingDeclaration(d) => {
            f(Property::Modifiers(d.modifiers));
        }
        NodeData::ExternalModuleReference(d) => {
            f(Property::Node(d.expression));
        }
        NodeData::JsxElement(d) => {
            f(Property::Node(d.opening_element));
            f(Property::List(d.children));
            f(Property::Node(d.closing_element));
        }
        NodeData::JsxSelfClosingElement(d) => {
            f(Property::Node(d.tag_name));
            f(Property::List(d.type_arguments));
            f(Property::Node(d.attributes));
        }
        NodeData::JsxOpeningElement(d) => {
            f(Property::Node(d.tag_name));
            f(Property::List(d.type_arguments));
            f(Property::Node(d.attributes));
        }
        NodeData::JsxClosingElement(d) => {
            f(Property::Node(d.tag_name));
        }
        NodeData::JsxFragment(d) => {
            f(Property::Node(d.opening_fragment));
            f(Property::List(d.children));
            f(Property::Node(d.closing_fragment));
        }
        NodeData::JsxAttribute(d) => {
            f(Property::Node(d.name));
            f(Property::Node(d.initializer));
        }
        NodeData::JsxAttributes(d) => {
            f(Property::List(d.properties));
        }
        NodeData::JsxSpreadAttribute(d) => {
            f(Property::Node(d.expression));
        }
        NodeData::JsxExpression(d) => {
            f(Property::Node(d.dot_dot_dot_token));
            f(Property::Node(d.expression));
        }
        NodeData::JsxNamespacedName(d) => {
            f(Property::Node(d.namespace));
            f(Property::Node(d.name));
        }
        NodeData::CaseClause(d) => {
            f(Property::Node(d.expression));
            f(Property::List(d.statements));
        }
        NodeData::DefaultClause(d) => {
            f(Property::Node(None));
            f(Property::List(d.statements));
        }
        NodeData::HeritageClause(d) => {
            f(Property::List(d.types));
        }
        NodeData::CatchClause(d) => {
            f(Property::Node(d.variable_declaration));
            f(Property::Node(d.block));
        }
        NodeData::ImportAttributes(d) => {
            f(Property::List(d.elements));
        }
        NodeData::ImportAttribute(d) => {
            f(Property::Node(d.name));
            f(Property::Node(d.value));
        }
        NodeData::PropertyAssignment(d) => {
            f(Property::Modifiers(d.modifiers));
            f(Property::Node(d.name));
            f(Property::Node(d.question_token.or(d.exclamation_token)));
            f(Property::Node(None));
            f(Property::Node(d.initializer));
        }
        NodeData::ShorthandPropertyAssignment(d) => {
            f(Property::Modifiers(d.modifiers));
            f(Property::Node(d.name));
            f(Property::Node(d.question_token.or(d.exclamation_token)));
            f(Property::Node(None));
            f(Property::Node(d.equals_token));
            f(Property::Node(d.object_assignment_initializer));
        }
        NodeData::SpreadAssignment(d) => {
            f(Property::Node(d.expression));
        }
        NodeData::EnumMember(d) => {
            f(Property::Node(d.name));
            f(Property::Node(d.initializer));
        }
        NodeData::SourceFile(d) => {
            f(Property::List(d.statements));
            f(Property::Node(d.end_of_file_token));
        }
        NodeData::JSDocTypeExpression(d) => {
            f(Property::Node(d.r#type));
        }
        NodeData::JSDocNameReference(d) => {
            f(Property::Node(d.name));
        }
        NodeData::JSDocNullableType(d) => {
            f(Property::Node(d.r#type));
        }
        NodeData::JSDocNonNullableType(d) => {
            f(Property::Node(d.r#type));
        }
        NodeData::JSDocOptionalType(d) => {
            f(Property::Node(d.r#type));
        }
        NodeData::JSDocVariadicType(d) => {
            f(Property::Node(d.r#type));
        }
        NodeData::JSDoc(d) => {
            f(Property::Comment(&d.comment));
            f(Property::List(d.tags));
        }
        NodeData::JSDocTypeLiteral(d) => {
            f(Property::Slice(d.js_doc_property_tags));
        }
        NodeData::JSDocSignature(d) => {
            f(Property::List(d.type_parameters));
            f(Property::List(d.parameters));
            f(Property::Node(d.r#type));
        }
        NodeData::JSDocLink(d) => {
            f(Property::Node(d.name));
        }
        NodeData::JSDocLinkCode(d) => {
            f(Property::Node(d.name));
        }
        NodeData::JSDocLinkPlain(d) => {
            f(Property::Node(d.name));
        }
        NodeData::JSDocTag(d) => {
            f(Property::Node(d.tag_name));
            f(Property::Comment(&d.comment));
        }
        NodeData::JSDocAugmentsTag(d) => {
            f(Property::Node(d.tag_name));
            f(Property::Node(d.class));
            f(Property::Comment(&d.comment));
        }
        NodeData::JSDocImplementsTag(d) => {
            f(Property::Node(d.tag_name));
            f(Property::Node(d.class));
            f(Property::Comment(&d.comment));
        }
        NodeData::JSDocDeprecatedTag(d) => {
            f(Property::Node(d.tag_name));
            f(Property::Comment(&d.comment));
        }
        NodeData::JSDocPublicTag(d) => {
            f(Property::Node(d.tag_name));
            f(Property::Comment(&d.comment));
        }
        NodeData::JSDocPrivateTag(d) => {
            f(Property::Node(d.tag_name));
            f(Property::Comment(&d.comment));
        }
        NodeData::JSDocProtectedTag(d) => {
            f(Property::Node(d.tag_name));
            f(Property::Comment(&d.comment));
        }
        NodeData::JSDocReadonlyTag(d) => {
            f(Property::Node(d.tag_name));
            f(Property::Comment(&d.comment));
        }
        NodeData::JSDocOverrideTag(d) => {
            f(Property::Node(d.tag_name));
            f(Property::Comment(&d.comment));
        }
        NodeData::JSDocCallbackTag(d) => {
            f(Property::Node(d.tag_name));
            f(Property::Node(d.type_expression));
            f(Property::Node(d.full_name));
            f(Property::Comment(&d.comment));
        }
        NodeData::JSDocOverloadTag(d) => {
            f(Property::Node(d.tag_name));
            f(Property::Node(d.type_expression));
            f(Property::Comment(&d.comment));
        }
        NodeData::JSDocParameterTag(d) => {
            f(Property::Node(d.tag_name));
            f(Property::Node(d.name));
            f(Property::Node(d.type_expression));
            f(Property::Comment(&d.comment));
        }
        NodeData::JSDocReturnTag(d) => {
            f(Property::Node(d.tag_name));
            f(Property::Node(d.type_expression));
            f(Property::Comment(&d.comment));
        }
        NodeData::JSDocThisTag(d) => {
            f(Property::Node(d.tag_name));
            f(Property::Node(d.type_expression));
            f(Property::Comment(&d.comment));
        }
        NodeData::JSDocTypeTag(d) => {
            f(Property::Node(d.tag_name));
            f(Property::Node(d.type_expression));
            f(Property::Comment(&d.comment));
        }
        NodeData::JSDocTemplateTag(d) => {
            f(Property::Node(d.tag_name));
            f(Property::Node(d.constraint));
            f(Property::List(d.type_parameters));
            f(Property::Comment(&d.comment));
        }
        NodeData::JSDocTypedefTag(d) => {
            f(Property::Node(d.tag_name));
            f(Property::Node(d.type_expression));
            f(Property::Node(d.full_name));
            f(Property::Comment(&d.comment));
        }
        NodeData::JSDocSeeTag(d) => {
            f(Property::Node(d.tag_name));
            f(Property::Node(d.name));
            f(Property::Comment(&d.comment));
        }
        NodeData::JSDocPropertyTag(d) => {
            f(Property::Node(d.tag_name));
            f(Property::Node(d.name));
            f(Property::Node(d.type_expression));
            f(Property::Comment(&d.comment));
        }
        NodeData::JSDocThrowsTag(d) => {
            f(Property::Node(d.tag_name));
            f(Property::Node(d.type_expression));
            f(Property::Comment(&d.comment));
        }
        NodeData::JSDocSatisfiesTag(d) => {
            f(Property::Node(d.tag_name));
            f(Property::Node(d.type_expression));
            f(Property::Comment(&d.comment));
        }
        NodeData::JSDocImportTag(d) => {
            f(Property::Node(d.tag_name));
            f(Property::Node(d.import_clause));
            f(Property::Node(d.module_specifier));
            f(Property::Node(d.attributes));
            f(Property::Comment(&d.comment));
        }
        NodeData::SyntaxList(_) => {
            f(Property::Node(None));
        }
        NodeData::PartiallyEmittedExpression(d) => {
            f(Property::Node(d.expression));
        }
        _ => {}
    }
}
