//! Build script: generate `diagnostics_gen.rs` from the vendored TypeScript
//! `diagnosticMessages.json`. Zero-dependency: a tiny hand-rolled JSON reader
//! handles the (very regular) message catalog. The generated identifiers match
//! tsc's `scripts/processDiagnosticMessages.mjs` naming scheme byte-for-byte so
//! that `gen::<Name>` references resolve to the right code/category/text.

use std::collections::BTreeMap;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").unwrap();
    let json_path = PathBuf::from(&manifest).join("vendor/diagnosticMessages.json");
    println!("cargo:rerun-if-changed=vendor/diagnosticMessages.json");
    println!("cargo:rerun-if-changed=build.rs");

    let raw = fs::read_to_string(&json_path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", json_path.display()));

    let entries = parse_catalog(&raw);

    // Deterministic ordering: by code (ALL_BY_CODE must be sorted for the
    // binary search in `diagnostics::by_code`).
    let mut by_code: BTreeMap<u64, (String, String, String, bool, bool, bool)> = BTreeMap::new();
    let mut names: Vec<(String, u64)> = Vec::new();
    for (text, code, category, elided, ru, rd) in entries {
        let name = convert_property_name(&text);
        names.push((name.clone(), code));
        by_code.insert(code, (name, category, text, elided, ru, rd));
    }

    let mut out = String::new();
    out.push_str(
        "// @generated by build.rs from vendor/diagnosticMessages.json - do not edit.\n\n",
    );

    // Per-message statics, emitted in code order for stable diffs.
    for (code, (name, category, text, elided, ru, rd)) in &by_code {
        let _ = writeln!(
            out,
            "pub static {name}: DiagnosticMessage = DiagnosticMessage {{ code: {code}, category: Category::{category}, text: {text:?}, elided: {elided}, reports_unnecessary: {ru}, reports_deprecated: {rd} }};"
        );
    }

    // ALL_BY_CODE: sorted slice of references for binary search + catalog size.
    out.push_str("\npub static ALL_BY_CODE: &[&DiagnosticMessage] = &[\n");
    for (_code, (name, _category, _text, _elided, _ru, _rd)) in &by_code {
        let _ = writeln!(out, "    &{name},");
    }
    out.push_str("];\n");

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = PathBuf::from(out_dir).join("diagnostics_gen.rs");
    fs::write(&dest, out).expect("write diagnostics_gen.rs");
}

/// Port of tsc `convertPropertyName`: map a message template to its Rust/TS
/// identifier. `*`->`_Asterisk`, `/`->`_Slash`, `:`->`_Colon`, word chars kept,
/// everything else `_`; collapse runs of `_`; drop a leading `_` unless it
/// precedes a digit; drop a trailing `_`.
fn convert_property_name(orig: &str) -> String {
    let mut s = String::with_capacity(orig.len());
    for ch in orig.chars() {
        match ch {
            '*' => s.push_str("_Asterisk"),
            '/' => s.push_str("_Slash"),
            ':' => s.push_str("_Colon"),
            c if c == '_' || c.is_ascii_alphanumeric() => s.push(c),
            _ => s.push('_'),
        }
    }
    // collapse multiple underscores
    let mut collapsed = String::with_capacity(s.len());
    let mut prev_us = false;
    for c in s.chars() {
        if c == '_' {
            if !prev_us {
                collapsed.push('_');
            }
            prev_us = true;
        } else {
            collapsed.push(c);
            prev_us = false;
        }
    }
    // remove leading underscore unless followed by a digit
    let bytes = collapsed.as_bytes();
    if bytes.first() == Some(&b'_') {
        let second_is_digit = bytes.get(1).map(|b| b.is_ascii_digit()).unwrap_or(false);
        if !second_is_digit {
            collapsed.remove(0);
        }
    }
    // remove trailing underscore
    while collapsed.ends_with('_') {
        collapsed.pop();
    }
    collapsed
}

/// Parse the catalog object into (text, code, category, elided) tuples. Only
/// the structure tsc emits is supported: a top-level object whose values are
/// objects with string `category`, integer `code`, and optional boolean
/// `elidedInCompatabilityPyramid` (other keys ignored).
fn parse_catalog(src: &str) -> Vec<(String, u64, String, bool, bool, bool)> {
    let mut p = Json::new(src);
    p.ws();
    p.expect('{');
    let mut out = Vec::new();
    p.ws();
    if p.peek() == Some('}') {
        p.bump();
        return out;
    }
    loop {
        p.ws();
        let key = p.string();
        p.ws();
        p.expect(':');
        p.ws();
        let (code, category, elided, ru, rd) = parse_entry(&mut p);
        out.push((key, code, category, elided, ru, rd));
        p.ws();
        match p.bump() {
            Some(',') => {
                p.ws();
                if p.peek() == Some('}') {
                    p.bump();
                    break;
                }
            }
            Some('}') => break,
            other => panic!("expected ',' or '}}' in catalog, got {other:?}"),
        }
    }
    out
}

fn parse_entry(p: &mut Json) -> (u64, String, bool, bool, bool) {
    p.expect('{');
    let mut code = None;
    let mut category = None;
    let mut elided = false;
    let mut reports_unnecessary = false;
    let mut reports_deprecated = false;
    p.ws();
    if p.peek() == Some('}') {
        p.bump();
        return (
            code.unwrap_or(0),
            category.unwrap_or_default(),
            elided,
            reports_unnecessary,
            reports_deprecated,
        );
    }
    loop {
        p.ws();
        let key = p.string();
        p.ws();
        p.expect(':');
        p.ws();
        match key.as_str() {
            "code" => code = Some(p.number()),
            "category" => category = Some(p.string()),
            "elidedInCompatabilityPyramid" => elided = p.boolean(),
            "reportsUnnecessary" => reports_unnecessary = p.boolean(),
            "reportsDeprecated" => reports_deprecated = p.boolean(),
            _ => p.skip_value(),
        }
        p.ws();
        match p.bump() {
            Some(',') => {}
            Some('}') => break,
            other => panic!("expected ',' or '}}' in entry, got {other:?}"),
        }
    }
    (
        code.unwrap_or(0),
        category.unwrap_or_default(),
        elided,
        reports_unnecessary,
        reports_deprecated,
    )
}

struct Json<'a> {
    b: &'a [u8],
    i: usize,
}

impl<'a> Json<'a> {
    fn new(s: &'a str) -> Json<'a> {
        Json {
            b: s.as_bytes(),
            i: 0,
        }
    }
    fn peek(&self) -> Option<char> {
        self.b.get(self.i).map(|&c| c as char)
    }
    fn bump(&mut self) -> Option<char> {
        let c = self.b.get(self.i).map(|&c| c as char);
        if c.is_some() {
            self.i += 1;
        }
        c
    }
    fn expect(&mut self, c: char) {
        match self.bump() {
            Some(x) if x == c => {}
            other => panic!("expected {c:?}, got {other:?} at byte {}", self.i),
        }
    }
    fn ws(&mut self) {
        while let Some(c) = self.peek() {
            if c == ' ' || c == '\t' || c == '\n' || c == '\r' {
                self.i += 1;
            } else {
                break;
            }
        }
    }
    fn string(&mut self) -> String {
        self.expect('"');
        let mut s = String::new();
        loop {
            let c = self.bump().expect("unterminated string");
            match c {
                '"' => break,
                '\\' => {
                    let e = self.bump().expect("bad escape");
                    match e {
                        '"' => s.push('"'),
                        '\\' => s.push('\\'),
                        '/' => s.push('/'),
                        'n' => s.push('\n'),
                        't' => s.push('\t'),
                        'r' => s.push('\r'),
                        'b' => s.push('\u{0008}'),
                        'f' => s.push('\u{000C}'),
                        'u' => {
                            let hex: String = (0..4).map(|_| self.bump().unwrap()).collect();
                            let cp = u32::from_str_radix(&hex, 16).expect("bad \\u");
                            s.push(char::from_u32(cp).unwrap_or('\u{FFFD}'));
                        }
                        other => panic!("unknown escape \\{other}"),
                    }
                }
                // The catalog is ASCII-only in practice; pass bytes through as
                // UTF-8 by re-reading the underlying char boundary.
                _ => {
                    if (c as u32) < 0x80 {
                        s.push(c);
                    } else {
                        // back up one byte and decode a full UTF-8 char
                        self.i -= 1;
                        let rest = std::str::from_utf8(&self.b[self.i..]).expect("utf8");
                        let ch = rest.chars().next().unwrap();
                        self.i += ch.len_utf8();
                        s.push(ch);
                    }
                }
            }
        }
        s
    }
    fn number(&mut self) -> u64 {
        let start = self.i;
        while let Some(c) = self.peek() {
            if c.is_ascii_digit() || c == '-' || c == '+' {
                self.i += 1;
            } else {
                break;
            }
        }
        std::str::from_utf8(&self.b[start..self.i])
            .unwrap()
            .parse()
            .expect("bad number")
    }
    fn boolean(&mut self) -> bool {
        if self.b[self.i..].starts_with(b"true") {
            self.i += 4;
            true
        } else if self.b[self.i..].starts_with(b"false") {
            self.i += 5;
            false
        } else {
            panic!("bad boolean at byte {}", self.i)
        }
    }
    fn skip_value(&mut self) {
        self.ws();
        match self.peek() {
            Some('"') => {
                self.string();
            }
            Some('{') => {
                self.bump();
                let mut depth = 1;
                while depth > 0 {
                    match self.bump() {
                        Some('"') => {
                            self.i -= 1;
                            self.string();
                        }
                        Some('{') => depth += 1,
                        Some('}') => depth -= 1,
                        Some(_) => {}
                        None => break,
                    }
                }
            }
            Some('[') => {
                self.bump();
                let mut depth = 1;
                while depth > 0 {
                    match self.bump() {
                        Some('"') => {
                            self.i -= 1;
                            self.string();
                        }
                        Some('[') => depth += 1,
                        Some(']') => depth -= 1,
                        Some(_) => {}
                        None => break,
                    }
                }
            }
            Some('t') | Some('f') => {
                self.boolean();
            }
            Some('n') => {
                self.i += 4; // null
            }
            _ => {
                self.number();
            }
        }
    }
}
