// Generated by scripts/observe-utf16-binder-names.mjs; do not edit.
// TypeScript 6.0.3 SHA-256: 569177652966bd528c319171c7dd22860dbf72bde116cbc4f644f1d02bb12e39
// Observer SHA-256: 56cbcfd2327fb8bacda7cee2327e9f31a53b2fe8a04ee886b9fa416f5be4eb07
// 7 cases, each observed twice in a fresh process. Binder API only.
const CASES: &[Case] = &[
    Case {
        id: "class-distinct-and-paired",
        source: r####"class C { "\uD800" = 1; "\uD801" = 2; "\uDC00" = 3; "\uFFFD" = 4; "\\uD800" = 5; "__call" = 6; "\uD83D\uDE00" = 7; "\u{1f600}" = 8; }"####,
        kind: 264, table: "members",
        entries: &[(&[55296], 1), (&[55297], 1), (&[56320], 1), (&[65533], 1), (&[92, 117, 68, 56, 48, 48], 1), (&[95, 95, 95, 99, 97, 108, 108], 1), (&[55357, 56832], 2)],
        patterns: &[],
        diagnostics: &[],
    },
    Case {
        id: "computed-object-names",
        source: r####"const o = { ["\uD800"]: 1, ["\uD801"]: 2, ["\uDC00"]: 3, ["\uFFFD"]: 4, ["__call"]: 5, ["\uD800"]: 6 };"####,
        kind: 211, table: "members",
        entries: &[(&[55296], 2), (&[55297], 1), (&[56320], 1), (&[65533], 1), (&[95, 95, 95, 99, 97, 108, 108], 1)],
        patterns: &[],
        diagnostics: &[],
    },
    Case {
        id: "internal-and-user-call",
        source: r####"interface I { (): void; "__call": string; ["\uD800"]: number; }"####,
        kind: 265, table: "members",
        entries: &[(&[95, 95, 99, 97, 108, 108], 1), (&[95, 95, 95, 99, 97, 108, 108], 1), (&[55296], 1)],
        patterns: &[],
        diagnostics: &[],
    },
    Case {
        id: "ambient-module-identity",
        source: r####"declare module "\uD800" {} declare module "\uD801" {} declare module "\uFFFD" {} declare module "\\uD800" {} declare module "a\uD800*z\uDC00" {}"####,
        kind: 308, table: "locals",
        entries: &[(&[34, 55296, 34], 1), (&[34, 55297, 34], 1), (&[34, 65533, 34], 1), (&[34, 92, 117, 68, 56, 48, 48, 34], 1), (&[34, 97, 55296, 42, 122, 56320, 34], 1)],
        patterns: &[(&[97, 55296], &[122, 56320])],
        diagnostics: &[],
    },
    Case {
        id: "arbitrary-export-names",
        source: r####"const foo = 1; export { foo as "\uD800", foo as "\uD801", foo as "\uFFFD", foo as "__call" };"####,
        kind: 308, table: "exports",
        entries: &[(&[55296], 1), (&[55297], 1), (&[65533], 1), (&[95, 95, 95, 99, 97, 108, 108], 1)],
        patterns: &[],
        diagnostics: &[],
    },
    Case {
        id: "private-and-user-prefix",
        source: r####"class C { #x = 1; "__#1@#x" = 2; "\uD800" = 3; }"####,
        kind: 264, table: "members",
        entries: &[(&[95, 95, 35, 49, 64, 35, 120], 1), (&[95, 95, 95, 35, 49, 64, 35, 120], 1), (&[55296], 1)],
        patterns: &[],
        diagnostics: &[],
    },
    Case {
        id: "numeric-keys",
        source: r####"class N { [1]: number; [-1]: number; [+1]: number; 1.0: number; }"####,
        kind: 264, table: "members",
        entries: &[(&[49], 2), (&[45, 49], 1), (&[43, 49], 1)],
        patterns: &[],
        diagnostics: &[],
    },
];
