// @generated by scripts/generate_api_encoder.py from the vendored
// internal/ast/kind_generated.go and internal/api/encoder/encoder_generated.go.
// Do not edit by hand.

use tsc_syntax::{NodeData, SyntaxKind};

use super::Children;

/// The tsc-rs kind of a tsgo kind number (`None`: tsc-rs has no such kind).
pub(crate) fn port_kind(kind: u32) -> Option<SyntaxKind> {
    Some(match kind {
        0 => SyntaxKind::Unknown,
        1 => SyntaxKind::EndOfFileToken,
        2 => SyntaxKind::SingleLineCommentTrivia,
        3 => SyntaxKind::MultiLineCommentTrivia,
        4 => SyntaxKind::NewLineTrivia,
        5 => SyntaxKind::WhitespaceTrivia,
        6 => SyntaxKind::ConflictMarkerTrivia,
        7 => SyntaxKind::NonTextFileMarkerTrivia,
        8 => SyntaxKind::NumericLiteral,
        9 => SyntaxKind::BigIntLiteral,
        10 => SyntaxKind::StringLiteral,
        11 => SyntaxKind::JsxText,
        12 => SyntaxKind::JsxTextAllWhiteSpaces,
        13 => SyntaxKind::RegularExpressionLiteral,
        14 => SyntaxKind::NoSubstitutionTemplateLiteral,
        15 => SyntaxKind::TemplateHead,
        16 => SyntaxKind::TemplateMiddle,
        17 => SyntaxKind::TemplateTail,
        18 => SyntaxKind::OpenBraceToken,
        19 => SyntaxKind::CloseBraceToken,
        20 => SyntaxKind::OpenParenToken,
        21 => SyntaxKind::CloseParenToken,
        22 => SyntaxKind::OpenBracketToken,
        23 => SyntaxKind::CloseBracketToken,
        24 => SyntaxKind::DotToken,
        25 => SyntaxKind::DotDotDotToken,
        26 => SyntaxKind::SemicolonToken,
        27 => SyntaxKind::CommaToken,
        28 => SyntaxKind::QuestionDotToken,
        29 => SyntaxKind::LessThanToken,
        30 => SyntaxKind::LessThanSlashToken,
        31 => SyntaxKind::GreaterThanToken,
        32 => SyntaxKind::LessThanEqualsToken,
        33 => SyntaxKind::GreaterThanEqualsToken,
        34 => SyntaxKind::EqualsEqualsToken,
        35 => SyntaxKind::ExclamationEqualsToken,
        36 => SyntaxKind::EqualsEqualsEqualsToken,
        37 => SyntaxKind::ExclamationEqualsEqualsToken,
        38 => SyntaxKind::EqualsGreaterThanToken,
        39 => SyntaxKind::PlusToken,
        40 => SyntaxKind::MinusToken,
        41 => SyntaxKind::AsteriskToken,
        42 => SyntaxKind::AsteriskAsteriskToken,
        43 => SyntaxKind::SlashToken,
        44 => SyntaxKind::PercentToken,
        45 => SyntaxKind::PlusPlusToken,
        46 => SyntaxKind::MinusMinusToken,
        47 => SyntaxKind::LessThanLessThanToken,
        48 => SyntaxKind::GreaterThanGreaterThanToken,
        49 => SyntaxKind::GreaterThanGreaterThanGreaterThanToken,
        50 => SyntaxKind::AmpersandToken,
        51 => SyntaxKind::BarToken,
        52 => SyntaxKind::CaretToken,
        53 => SyntaxKind::ExclamationToken,
        54 => SyntaxKind::TildeToken,
        55 => SyntaxKind::AmpersandAmpersandToken,
        56 => SyntaxKind::BarBarToken,
        57 => SyntaxKind::QuestionToken,
        58 => SyntaxKind::ColonToken,
        59 => SyntaxKind::AtToken,
        60 => SyntaxKind::QuestionQuestionToken,
        61 => SyntaxKind::BacktickToken,
        62 => SyntaxKind::HashToken,
        63 => SyntaxKind::EqualsToken,
        64 => SyntaxKind::PlusEqualsToken,
        65 => SyntaxKind::MinusEqualsToken,
        66 => SyntaxKind::AsteriskEqualsToken,
        67 => SyntaxKind::AsteriskAsteriskEqualsToken,
        68 => SyntaxKind::SlashEqualsToken,
        69 => SyntaxKind::PercentEqualsToken,
        70 => SyntaxKind::LessThanLessThanEqualsToken,
        71 => SyntaxKind::GreaterThanGreaterThanEqualsToken,
        72 => SyntaxKind::GreaterThanGreaterThanGreaterThanEqualsToken,
        73 => SyntaxKind::AmpersandEqualsToken,
        74 => SyntaxKind::BarEqualsToken,
        75 => SyntaxKind::BarBarEqualsToken,
        76 => SyntaxKind::AmpersandAmpersandEqualsToken,
        77 => SyntaxKind::QuestionQuestionEqualsToken,
        78 => SyntaxKind::CaretEqualsToken,
        79 => SyntaxKind::Identifier,
        80 => SyntaxKind::PrivateIdentifier,
        81 => SyntaxKind::JSDocCommentTextToken,
        82 => SyntaxKind::BreakKeyword,
        83 => SyntaxKind::CaseKeyword,
        84 => SyntaxKind::CatchKeyword,
        85 => SyntaxKind::ClassKeyword,
        86 => SyntaxKind::ConstKeyword,
        87 => SyntaxKind::ContinueKeyword,
        88 => SyntaxKind::DebuggerKeyword,
        89 => SyntaxKind::DefaultKeyword,
        90 => SyntaxKind::DeleteKeyword,
        91 => SyntaxKind::DoKeyword,
        92 => SyntaxKind::ElseKeyword,
        93 => SyntaxKind::EnumKeyword,
        94 => SyntaxKind::ExportKeyword,
        95 => SyntaxKind::ExtendsKeyword,
        96 => SyntaxKind::FalseKeyword,
        97 => SyntaxKind::FinallyKeyword,
        98 => SyntaxKind::ForKeyword,
        99 => SyntaxKind::FunctionKeyword,
        100 => SyntaxKind::IfKeyword,
        101 => SyntaxKind::ImportKeyword,
        102 => SyntaxKind::InKeyword,
        103 => SyntaxKind::InstanceOfKeyword,
        104 => SyntaxKind::NewKeyword,
        105 => SyntaxKind::NullKeyword,
        106 => SyntaxKind::ReturnKeyword,
        107 => SyntaxKind::SuperKeyword,
        108 => SyntaxKind::SwitchKeyword,
        109 => SyntaxKind::ThisKeyword,
        110 => SyntaxKind::ThrowKeyword,
        111 => SyntaxKind::TrueKeyword,
        112 => SyntaxKind::TryKeyword,
        113 => SyntaxKind::TypeOfKeyword,
        114 => SyntaxKind::VarKeyword,
        115 => SyntaxKind::VoidKeyword,
        116 => SyntaxKind::WhileKeyword,
        117 => SyntaxKind::WithKeyword,
        118 => SyntaxKind::ImplementsKeyword,
        119 => SyntaxKind::InterfaceKeyword,
        120 => SyntaxKind::LetKeyword,
        121 => SyntaxKind::PackageKeyword,
        122 => SyntaxKind::PrivateKeyword,
        123 => SyntaxKind::ProtectedKeyword,
        124 => SyntaxKind::PublicKeyword,
        125 => SyntaxKind::StaticKeyword,
        126 => SyntaxKind::YieldKeyword,
        127 => SyntaxKind::AbstractKeyword,
        128 => SyntaxKind::AccessorKeyword,
        129 => SyntaxKind::AsKeyword,
        130 => SyntaxKind::AssertsKeyword,
        131 => SyntaxKind::AssertKeyword,
        132 => SyntaxKind::AnyKeyword,
        133 => SyntaxKind::AsyncKeyword,
        134 => SyntaxKind::AwaitKeyword,
        135 => SyntaxKind::BooleanKeyword,
        136 => SyntaxKind::ConstructorKeyword,
        137 => SyntaxKind::DeclareKeyword,
        138 => SyntaxKind::GetKeyword,
        140 => SyntaxKind::InferKeyword,
        141 => SyntaxKind::IntrinsicKeyword,
        142 => SyntaxKind::IsKeyword,
        143 => SyntaxKind::KeyOfKeyword,
        144 => SyntaxKind::ModuleKeyword,
        145 => SyntaxKind::NamespaceKeyword,
        146 => SyntaxKind::NeverKeyword,
        147 => SyntaxKind::OutKeyword,
        148 => SyntaxKind::ReadonlyKeyword,
        149 => SyntaxKind::RequireKeyword,
        150 => SyntaxKind::NumberKeyword,
        151 => SyntaxKind::ObjectKeyword,
        152 => SyntaxKind::SatisfiesKeyword,
        153 => SyntaxKind::SetKeyword,
        154 => SyntaxKind::StringKeyword,
        155 => SyntaxKind::SymbolKeyword,
        156 => SyntaxKind::TypeKeyword,
        157 => SyntaxKind::UndefinedKeyword,
        158 => SyntaxKind::UniqueKeyword,
        159 => SyntaxKind::UnknownKeyword,
        160 => SyntaxKind::UsingKeyword,
        161 => SyntaxKind::FromKeyword,
        162 => SyntaxKind::GlobalKeyword,
        163 => SyntaxKind::BigIntKeyword,
        164 => SyntaxKind::OverrideKeyword,
        165 => SyntaxKind::OfKeyword,
        166 => SyntaxKind::DeferKeyword,
        168 => SyntaxKind::QualifiedName,
        169 => SyntaxKind::ComputedPropertyName,
        170 => SyntaxKind::TypeParameter,
        171 => SyntaxKind::Parameter,
        172 => SyntaxKind::Decorator,
        173 => SyntaxKind::PropertySignature,
        174 => SyntaxKind::PropertyDeclaration,
        175 => SyntaxKind::MethodSignature,
        176 => SyntaxKind::MethodDeclaration,
        177 => SyntaxKind::ClassStaticBlockDeclaration,
        178 => SyntaxKind::Constructor,
        179 => SyntaxKind::GetAccessor,
        180 => SyntaxKind::SetAccessor,
        181 => SyntaxKind::CallSignature,
        182 => SyntaxKind::ConstructSignature,
        183 => SyntaxKind::IndexSignature,
        184 => SyntaxKind::TypePredicate,
        185 => SyntaxKind::TypeReference,
        186 => SyntaxKind::FunctionType,
        187 => SyntaxKind::ConstructorType,
        188 => SyntaxKind::TypeQuery,
        189 => SyntaxKind::TypeLiteral,
        190 => SyntaxKind::ArrayType,
        191 => SyntaxKind::TupleType,
        192 => SyntaxKind::OptionalType,
        193 => SyntaxKind::RestType,
        194 => SyntaxKind::UnionType,
        195 => SyntaxKind::IntersectionType,
        196 => SyntaxKind::ConditionalType,
        197 => SyntaxKind::InferType,
        198 => SyntaxKind::ParenthesizedType,
        199 => SyntaxKind::ThisType,
        200 => SyntaxKind::TypeOperator,
        201 => SyntaxKind::IndexedAccessType,
        202 => SyntaxKind::MappedType,
        203 => SyntaxKind::LiteralType,
        204 => SyntaxKind::NamedTupleMember,
        205 => SyntaxKind::TemplateLiteralType,
        206 => SyntaxKind::TemplateLiteralTypeSpan,
        207 => SyntaxKind::ImportType,
        208 => SyntaxKind::ObjectBindingPattern,
        209 => SyntaxKind::ArrayBindingPattern,
        210 => SyntaxKind::BindingElement,
        211 => SyntaxKind::ArrayLiteralExpression,
        212 => SyntaxKind::ObjectLiteralExpression,
        213 => SyntaxKind::PropertyAccessExpression,
        214 => SyntaxKind::ElementAccessExpression,
        215 => SyntaxKind::CallExpression,
        216 => SyntaxKind::NewExpression,
        217 => SyntaxKind::TaggedTemplateExpression,
        218 => SyntaxKind::TypeAssertionExpression,
        219 => SyntaxKind::ParenthesizedExpression,
        220 => SyntaxKind::FunctionExpression,
        221 => SyntaxKind::ArrowFunction,
        222 => SyntaxKind::DeleteExpression,
        223 => SyntaxKind::TypeOfExpression,
        224 => SyntaxKind::VoidExpression,
        225 => SyntaxKind::AwaitExpression,
        226 => SyntaxKind::PrefixUnaryExpression,
        227 => SyntaxKind::PostfixUnaryExpression,
        228 => SyntaxKind::BinaryExpression,
        229 => SyntaxKind::ConditionalExpression,
        230 => SyntaxKind::TemplateExpression,
        231 => SyntaxKind::YieldExpression,
        232 => SyntaxKind::SpreadElement,
        233 => SyntaxKind::ClassExpression,
        234 => SyntaxKind::OmittedExpression,
        235 => SyntaxKind::ExpressionWithTypeArguments,
        236 => SyntaxKind::AsExpression,
        237 => SyntaxKind::NonNullExpression,
        238 => SyntaxKind::MetaProperty,
        239 => SyntaxKind::SyntheticExpression,
        240 => SyntaxKind::SatisfiesExpression,
        241 => SyntaxKind::TemplateSpan,
        242 => SyntaxKind::SemicolonClassElement,
        243 => SyntaxKind::Block,
        244 => SyntaxKind::EmptyStatement,
        245 => SyntaxKind::VariableStatement,
        246 => SyntaxKind::ExpressionStatement,
        247 => SyntaxKind::IfStatement,
        248 => SyntaxKind::DoStatement,
        249 => SyntaxKind::WhileStatement,
        250 => SyntaxKind::ForStatement,
        251 => SyntaxKind::ForInStatement,
        252 => SyntaxKind::ForOfStatement,
        253 => SyntaxKind::ContinueStatement,
        254 => SyntaxKind::BreakStatement,
        255 => SyntaxKind::ReturnStatement,
        256 => SyntaxKind::WithStatement,
        257 => SyntaxKind::SwitchStatement,
        258 => SyntaxKind::LabeledStatement,
        259 => SyntaxKind::ThrowStatement,
        260 => SyntaxKind::TryStatement,
        261 => SyntaxKind::DebuggerStatement,
        262 => SyntaxKind::VariableDeclaration,
        263 => SyntaxKind::VariableDeclarationList,
        264 => SyntaxKind::FunctionDeclaration,
        265 => SyntaxKind::ClassDeclaration,
        266 => SyntaxKind::InterfaceDeclaration,
        267 => SyntaxKind::TypeAliasDeclaration,
        268 => SyntaxKind::EnumDeclaration,
        269 => SyntaxKind::ModuleDeclaration,
        270 => SyntaxKind::ModuleBlock,
        271 => SyntaxKind::CaseBlock,
        272 => SyntaxKind::NamespaceExportDeclaration,
        273 => SyntaxKind::ImportEqualsDeclaration,
        274 => SyntaxKind::ImportDeclaration,
        275 => SyntaxKind::ImportClause,
        276 => SyntaxKind::NamespaceImport,
        277 => SyntaxKind::NamedImports,
        278 => SyntaxKind::ImportSpecifier,
        279 => SyntaxKind::ExportAssignment,
        280 => SyntaxKind::ExportDeclaration,
        281 => SyntaxKind::NamedExports,
        282 => SyntaxKind::NamespaceExport,
        283 => SyntaxKind::ExportSpecifier,
        284 => SyntaxKind::MissingDeclaration,
        285 => SyntaxKind::ExternalModuleReference,
        286 => SyntaxKind::JsxElement,
        287 => SyntaxKind::JsxSelfClosingElement,
        288 => SyntaxKind::JsxOpeningElement,
        289 => SyntaxKind::JsxClosingElement,
        290 => SyntaxKind::JsxFragment,
        291 => SyntaxKind::JsxOpeningFragment,
        292 => SyntaxKind::JsxClosingFragment,
        293 => SyntaxKind::JsxAttribute,
        294 => SyntaxKind::JsxAttributes,
        295 => SyntaxKind::JsxSpreadAttribute,
        296 => SyntaxKind::JsxExpression,
        297 => SyntaxKind::JsxNamespacedName,
        298 => SyntaxKind::CaseClause,
        299 => SyntaxKind::DefaultClause,
        300 => SyntaxKind::HeritageClause,
        301 => SyntaxKind::CatchClause,
        302 => SyntaxKind::ImportAttributes,
        303 => SyntaxKind::ImportAttribute,
        304 => SyntaxKind::PropertyAssignment,
        305 => SyntaxKind::ShorthandPropertyAssignment,
        306 => SyntaxKind::SpreadAssignment,
        307 => SyntaxKind::EnumMember,
        308 => SyntaxKind::SourceFile,
        309 => SyntaxKind::JSDocTypeExpression,
        310 => SyntaxKind::JSDocNameReference,
        311 => SyntaxKind::JSDocAllType,
        312 => SyntaxKind::JSDocNullableType,
        313 => SyntaxKind::JSDocNonNullableType,
        314 => SyntaxKind::JSDocOptionalType,
        315 => SyntaxKind::JSDocVariadicType,
        316 => SyntaxKind::JSDoc,
        317 => SyntaxKind::JSDocText,
        318 => SyntaxKind::JSDocTypeLiteral,
        319 => SyntaxKind::JSDocSignature,
        320 => SyntaxKind::JSDocLink,
        321 => SyntaxKind::JSDocLinkCode,
        322 => SyntaxKind::JSDocLinkPlain,
        323 => SyntaxKind::JSDocTag,
        324 => SyntaxKind::JSDocAugmentsTag,
        325 => SyntaxKind::JSDocImplementsTag,
        326 => SyntaxKind::JSDocDeprecatedTag,
        327 => SyntaxKind::JSDocPublicTag,
        328 => SyntaxKind::JSDocPrivateTag,
        329 => SyntaxKind::JSDocProtectedTag,
        330 => SyntaxKind::JSDocReadonlyTag,
        331 => SyntaxKind::JSDocOverrideTag,
        332 => SyntaxKind::JSDocCallbackTag,
        333 => SyntaxKind::JSDocOverloadTag,
        334 => SyntaxKind::JSDocParameterTag,
        335 => SyntaxKind::JSDocReturnTag,
        336 => SyntaxKind::JSDocThisTag,
        337 => SyntaxKind::JSDocTypeTag,
        338 => SyntaxKind::JSDocTemplateTag,
        339 => SyntaxKind::JSDocTypedefTag,
        340 => SyntaxKind::JSDocSeeTag,
        341 => SyntaxKind::JSDocPropertyTag,
        342 => SyntaxKind::JSDocThrowsTag,
        343 => SyntaxKind::JSDocSatisfiesTag,
        344 => SyntaxKind::JSDocImportTag,
        345 => SyntaxKind::SyntaxList,
        348 => SyntaxKind::NotEmittedStatement,
        349 => SyntaxKind::PartiallyEmittedExpression,
        350 => SyntaxKind::SyntheticReferenceExpression,
        351 => SyntaxKind::NotEmittedTypeElement,
        352 => SyntaxKind::Count,
        _ => return None,
    })
}

/// Fills the child fields of `data` from the children tsgo's encoder
/// wrote in visitor order (`getChildrenPropertyMask`'s bits).
pub(crate) fn decode_properties(data: &mut NodeData, c: &mut Children<'_>) {
    match data {
        NodeData::QualifiedName(d) => {
            d.left = c.node(0);
            d.right = c.node(1);
        }
        NodeData::ComputedPropertyName(d) => {
            d.expression = c.node(0);
        }
        NodeData::TypeParameter(d) => {
            d.modifiers = c.list(0);
            d.name = c.node(1);
            d.constraint = c.node(2);
            d.expression = c.node(3);
            d.r#default = c.node(4);
        }
        NodeData::Parameter(d) => {
            d.modifiers = c.list(0);
            d.dot_dot_dot_token = c.node(1);
            d.name = c.node(2);
            d.question_token = c.node(3);
            d.r#type = c.node(4);
            d.initializer = c.node(5);
        }
        NodeData::Decorator(d) => {
            d.expression = c.node(0);
        }
        NodeData::PropertySignature(d) => {
            d.modifiers = c.list(0);
            d.name = c.node(1);
            d.question_token = c.node(2);
            d.r#type = c.node(3);
            d.initializer = c.node(4);
        }
        NodeData::PropertyDeclaration(d) => {
            d.modifiers = c.list(0);
            d.name = c.node(1);
            if let Some((token, kind)) = c.token(2) {
                if kind == SyntaxKind::QuestionToken {
                    d.question_token = Some(token);
                } else {
                    d.exclamation_token = Some(token);
                }
            }
            d.r#type = c.node(3);
            d.initializer = c.node(4);
        }
        NodeData::MethodSignature(d) => {
            d.modifiers = c.list(0);
            d.name = c.node(1);
            d.question_token = c.node(2);
            d.type_parameters = c.list(3);
            d.parameters = c.list(4);
            d.r#type = c.node(5);
        }
        NodeData::MethodDeclaration(d) => {
            d.modifiers = c.list(0);
            d.asterisk_token = c.node(1);
            d.name = c.node(2);
            if let Some((token, kind)) = c.token(3) {
                if kind == SyntaxKind::QuestionToken {
                    d.question_token = Some(token);
                } else {
                    d.exclamation_token = Some(token);
                }
            }
            d.type_parameters = c.list(4);
            d.parameters = c.list(5);
            d.r#type = c.node(6);
            d.body = c.node(7);
        }
        NodeData::ClassStaticBlockDeclaration(d) => {
            d.modifiers = c.list(0);
            d.body = c.node(1);
        }
        NodeData::Constructor(d) => {
            d.modifiers = c.list(0);
            d.type_parameters = c.list(1);
            d.parameters = c.list(2);
            d.r#type = c.node(3);
            d.body = c.node(4);
        }
        NodeData::GetAccessor(d) => {
            d.modifiers = c.list(0);
            d.name = c.node(1);
            d.type_parameters = c.list(2);
            d.parameters = c.list(3);
            d.r#type = c.node(4);
            d.body = c.node(5);
        }
        NodeData::SetAccessor(d) => {
            d.modifiers = c.list(0);
            d.name = c.node(1);
            d.type_parameters = c.list(2);
            d.parameters = c.list(3);
            d.r#type = c.node(4);
            d.body = c.node(5);
        }
        NodeData::CallSignature(d) => {
            d.type_parameters = c.list(0);
            d.parameters = c.list(1);
            d.r#type = c.node(2);
        }
        NodeData::ConstructSignature(d) => {
            d.type_parameters = c.list(0);
            d.parameters = c.list(1);
            d.r#type = c.node(2);
        }
        NodeData::IndexSignature(d) => {
            d.modifiers = c.list(0);
            d.parameters = c.list(1);
            d.r#type = c.node(2);
        }
        NodeData::TypePredicate(d) => {
            d.asserts_modifier = c.node(0);
            d.parameter_name = c.node(1);
            d.r#type = c.node(2);
        }
        NodeData::TypeReference(d) => {
            d.type_name = c.node(0);
            d.type_arguments = c.list(1);
        }
        NodeData::FunctionType(d) => {
            d.type_parameters = c.list(0);
            d.parameters = c.list(1);
            d.r#type = c.node(2);
        }
        NodeData::ConstructorType(d) => {
            d.modifiers = c.list(0);
            d.type_parameters = c.list(1);
            d.parameters = c.list(2);
            d.r#type = c.node(3);
        }
        NodeData::TypeQuery(d) => {
            d.expr_name = c.node(0);
            d.type_arguments = c.list(1);
        }
        NodeData::TypeLiteral(d) => {
            d.members = c.list(0);
        }
        NodeData::ArrayType(d) => {
            d.element_type = c.node(0);
        }
        NodeData::TupleType(d) => {
            d.elements = c.list(0);
        }
        NodeData::OptionalType(d) => {
            d.r#type = c.node(0);
        }
        NodeData::RestType(d) => {
            d.r#type = c.node(0);
        }
        NodeData::UnionType(d) => {
            d.types = c.list(0);
        }
        NodeData::IntersectionType(d) => {
            d.types = c.list(0);
        }
        NodeData::ConditionalType(d) => {
            d.check_type = c.node(0);
            d.extends_type = c.node(1);
            d.true_type = c.node(2);
            d.false_type = c.node(3);
        }
        NodeData::InferType(d) => {
            d.type_parameter = c.node(0);
        }
        NodeData::ParenthesizedType(d) => {
            d.r#type = c.node(0);
        }
        NodeData::TypeOperator(d) => {
            d.r#type = c.node(0);
        }
        NodeData::IndexedAccessType(d) => {
            d.object_type = c.node(0);
            d.index_type = c.node(1);
        }
        NodeData::MappedType(d) => {
            d.readonly_token = c.node(0);
            d.type_parameter = c.node(1);
            d.name_type = c.node(2);
            d.question_token = c.node(3);
            d.r#type = c.node(4);
            d.members = c.list(5);
        }
        NodeData::LiteralType(d) => {
            d.literal = c.node(0);
        }
        NodeData::NamedTupleMember(d) => {
            d.dot_dot_dot_token = c.node(0);
            d.name = c.node(1);
            d.question_token = c.node(2);
            d.r#type = c.node(3);
        }
        NodeData::TemplateLiteralType(d) => {
            d.head = c.node(0);
            d.template_spans = c.list(1);
        }
        NodeData::TemplateLiteralTypeSpan(d) => {
            d.r#type = c.node(0);
            d.literal = c.node(1);
        }
        NodeData::ImportType(d) => {
            d.argument = c.node(0);
            d.attributes = c.node(1);
            d.qualifier = c.node(2);
            d.type_arguments = c.list(3);
        }
        NodeData::ObjectBindingPattern(d) => {
            d.elements = c.list(0);
        }
        NodeData::ArrayBindingPattern(d) => {
            d.elements = c.list(0);
        }
        NodeData::BindingElement(d) => {
            d.dot_dot_dot_token = c.node(0);
            d.property_name = c.node(1);
            d.name = c.node(2);
            d.initializer = c.node(3);
        }
        NodeData::ArrayLiteralExpression(d) => {
            d.elements = c.list(0);
        }
        NodeData::ObjectLiteralExpression(d) => {
            d.properties = c.list(0);
        }
        NodeData::PropertyAccessExpression(d) => {
            d.expression = c.node(0);
            d.question_dot_token = c.node(1);
            d.name = c.node(2);
        }
        NodeData::ElementAccessExpression(d) => {
            d.expression = c.node(0);
            d.question_dot_token = c.node(1);
            d.argument_expression = c.node(2);
        }
        NodeData::CallExpression(d) => {
            d.expression = c.node(0);
            d.question_dot_token = c.node(1);
            d.type_arguments = c.list(2);
            d.arguments = c.list(3);
        }
        NodeData::NewExpression(d) => {
            d.expression = c.node(0);
            d.type_arguments = c.list(1);
            d.arguments = c.list(2);
        }
        NodeData::TaggedTemplateExpression(d) => {
            d.tag = c.node(0);
            d.question_dot_token = c.node(1);
            d.type_arguments = c.list(2);
            d.template = c.node(3);
        }
        NodeData::TypeAssertionExpression(d) => {
            d.r#type = c.node(0);
            d.expression = c.node(1);
        }
        NodeData::ParenthesizedExpression(d) => {
            d.expression = c.node(0);
        }
        NodeData::FunctionExpression(d) => {
            d.modifiers = c.list(0);
            d.asterisk_token = c.node(1);
            d.name = c.node(2);
            d.type_parameters = c.list(3);
            d.parameters = c.list(4);
            d.r#type = c.node(5);
            d.body = c.node(6);
        }
        NodeData::ArrowFunction(d) => {
            d.modifiers = c.list(0);
            d.type_parameters = c.list(1);
            d.parameters = c.list(2);
            d.r#type = c.node(3);
            d.equals_greater_than_token = c.node(4);
            d.body = c.node(5);
        }
        NodeData::DeleteExpression(d) => {
            d.expression = c.node(0);
        }
        NodeData::TypeOfExpression(d) => {
            d.expression = c.node(0);
        }
        NodeData::VoidExpression(d) => {
            d.expression = c.node(0);
        }
        NodeData::AwaitExpression(d) => {
            d.expression = c.node(0);
        }
        NodeData::PrefixUnaryExpression(d) => {
            d.operand = c.node(0);
        }
        NodeData::PostfixUnaryExpression(d) => {
            d.operand = c.node(0);
        }
        NodeData::BinaryExpression(d) => {
            c.skip(0);
            d.left = c.node(1);
            c.skip(2);
            d.operator_token = c.node(3);
            d.right = c.node(4);
        }
        NodeData::ConditionalExpression(d) => {
            d.condition = c.node(0);
            d.question_token = c.node(1);
            d.when_true = c.node(2);
            d.colon_token = c.node(3);
            d.when_false = c.node(4);
        }
        NodeData::TemplateExpression(d) => {
            d.head = c.node(0);
            d.template_spans = c.list(1);
        }
        NodeData::YieldExpression(d) => {
            d.asterisk_token = c.node(0);
            d.expression = c.node(1);
        }
        NodeData::SpreadElement(d) => {
            d.expression = c.node(0);
        }
        NodeData::ClassExpression(d) => {
            d.modifiers = c.list(0);
            d.name = c.node(1);
            d.type_parameters = c.list(2);
            d.heritage_clauses = c.list(3);
            d.members = c.list(4);
        }
        NodeData::ExpressionWithTypeArguments(d) => {
            d.expression = c.node(0);
            d.type_arguments = c.list(1);
        }
        NodeData::AsExpression(d) => {
            d.expression = c.node(0);
            d.r#type = c.node(1);
        }
        NodeData::NonNullExpression(d) => {
            d.expression = c.node(0);
        }
        NodeData::MetaProperty(d) => {
            d.name = c.node(0);
        }
        NodeData::SatisfiesExpression(d) => {
            d.expression = c.node(0);
            d.r#type = c.node(1);
        }
        NodeData::TemplateSpan(d) => {
            d.expression = c.node(0);
            d.literal = c.node(1);
        }
        NodeData::Block(d) => {
            d.statements = c.list(0);
        }
        NodeData::VariableStatement(d) => {
            d.modifiers = c.list(0);
            d.declaration_list = c.node(1);
        }
        NodeData::ExpressionStatement(d) => {
            d.expression = c.node(0);
        }
        NodeData::IfStatement(d) => {
            d.expression = c.node(0);
            d.then_statement = c.node(1);
            d.else_statement = c.node(2);
        }
        NodeData::DoStatement(d) => {
            d.statement = c.node(0);
            d.expression = c.node(1);
        }
        NodeData::WhileStatement(d) => {
            d.expression = c.node(0);
            d.statement = c.node(1);
        }
        NodeData::ForStatement(d) => {
            d.initializer = c.node(0);
            d.condition = c.node(1);
            d.incrementor = c.node(2);
            d.statement = c.node(3);
        }
        NodeData::ForInStatement(d) => {
            c.skip(0);
            d.initializer = c.node(1);
            d.expression = c.node(2);
            d.statement = c.node(3);
        }
        NodeData::ForOfStatement(d) => {
            d.await_modifier = c.node(0);
            d.initializer = c.node(1);
            d.expression = c.node(2);
            d.statement = c.node(3);
        }
        NodeData::ContinueStatement(d) => {
            d.label = c.node(0);
        }
        NodeData::BreakStatement(d) => {
            d.label = c.node(0);
        }
        NodeData::ReturnStatement(d) => {
            d.expression = c.node(0);
        }
        NodeData::WithStatement(d) => {
            d.expression = c.node(0);
            d.statement = c.node(1);
        }
        NodeData::SwitchStatement(d) => {
            d.expression = c.node(0);
            d.case_block = c.node(1);
        }
        NodeData::LabeledStatement(d) => {
            d.label = c.node(0);
            d.statement = c.node(1);
        }
        NodeData::ThrowStatement(d) => {
            d.expression = c.node(0);
        }
        NodeData::TryStatement(d) => {
            d.try_block = c.node(0);
            d.catch_clause = c.node(1);
            d.finally_block = c.node(2);
        }
        NodeData::VariableDeclaration(d) => {
            d.name = c.node(0);
            d.exclamation_token = c.node(1);
            d.r#type = c.node(2);
            d.initializer = c.node(3);
        }
        NodeData::VariableDeclarationList(d) => {
            d.declarations = c.list(0);
        }
        NodeData::FunctionDeclaration(d) => {
            d.modifiers = c.list(0);
            d.asterisk_token = c.node(1);
            d.name = c.node(2);
            d.type_parameters = c.list(3);
            d.parameters = c.list(4);
            d.r#type = c.node(5);
            d.body = c.node(6);
        }
        NodeData::ClassDeclaration(d) => {
            d.modifiers = c.list(0);
            d.name = c.node(1);
            d.type_parameters = c.list(2);
            d.heritage_clauses = c.list(3);
            d.members = c.list(4);
        }
        NodeData::InterfaceDeclaration(d) => {
            d.modifiers = c.list(0);
            d.name = c.node(1);
            d.type_parameters = c.list(2);
            d.heritage_clauses = c.list(3);
            d.members = c.list(4);
        }
        NodeData::TypeAliasDeclaration(d) => {
            d.modifiers = c.list(0);
            d.name = c.node(1);
            d.type_parameters = c.list(2);
            d.r#type = c.node(3);
        }
        NodeData::EnumDeclaration(d) => {
            d.modifiers = c.list(0);
            d.name = c.node(1);
            d.members = c.list(2);
        }
        NodeData::ModuleDeclaration(d) => {
            d.modifiers = c.list(0);
            d.name = c.node(1);
            d.attributes = c.node(2);
            d.body = c.node(3);
        }
        NodeData::ModuleBlock(d) => {
            d.statements = c.list(0);
        }
        NodeData::CaseBlock(d) => {
            d.clauses = c.list(0);
        }
        NodeData::NamespaceExportDeclaration(d) => {
            d.modifiers = c.list(0);
            d.name = c.node(1);
        }
        NodeData::ImportEqualsDeclaration(d) => {
            d.modifiers = c.list(0);
            d.name = c.node(1);
            d.module_reference = c.node(2);
        }
        NodeData::ImportDeclaration(d) => {
            d.modifiers = c.list(0);
            d.import_clause = c.node(1);
            d.module_specifier = c.node(2);
            d.attributes = c.node(3);
        }
        NodeData::ImportClause(d) => {
            d.name = c.node(0);
            d.named_bindings = c.node(1);
        }
        NodeData::NamespaceImport(d) => {
            d.name = c.node(0);
        }
        NodeData::NamedImports(d) => {
            d.elements = c.list(0);
        }
        NodeData::ImportSpecifier(d) => {
            d.property_name = c.node(0);
            d.name = c.node(1);
        }
        NodeData::ExportAssignment(d) => {
            d.modifiers = c.list(0);
            c.skip(1);
            d.expression = c.node(2);
        }
        NodeData::ExportDeclaration(d) => {
            d.modifiers = c.list(0);
            d.export_clause = c.node(1);
            d.module_specifier = c.node(2);
            d.attributes = c.node(3);
        }
        NodeData::NamedExports(d) => {
            d.elements = c.list(0);
        }
        NodeData::NamespaceExport(d) => {
            d.name = c.node(0);
        }
        NodeData::ExportSpecifier(d) => {
            d.property_name = c.node(0);
            d.name = c.node(1);
        }
        NodeData::MissingDeclaration(d) => {
            d.modifiers = c.list(0);
        }
        NodeData::ExternalModuleReference(d) => {
            d.expression = c.node(0);
        }
        NodeData::JsxElement(d) => {
            d.opening_element = c.node(0);
            d.children = c.list(1);
            d.closing_element = c.node(2);
        }
        NodeData::JsxSelfClosingElement(d) => {
            d.tag_name = c.node(0);
            d.type_arguments = c.list(1);
            d.attributes = c.node(2);
        }
        NodeData::JsxOpeningElement(d) => {
            d.tag_name = c.node(0);
            d.type_arguments = c.list(1);
            d.attributes = c.node(2);
        }
        NodeData::JsxClosingElement(d) => {
            d.tag_name = c.node(0);
        }
        NodeData::JsxFragment(d) => {
            d.opening_fragment = c.node(0);
            d.children = c.list(1);
            d.closing_fragment = c.node(2);
        }
        NodeData::JsxAttribute(d) => {
            d.name = c.node(0);
            d.initializer = c.node(1);
        }
        NodeData::JsxAttributes(d) => {
            d.properties = c.list(0);
        }
        NodeData::JsxSpreadAttribute(d) => {
            d.expression = c.node(0);
        }
        NodeData::JsxExpression(d) => {
            d.dot_dot_dot_token = c.node(0);
            d.expression = c.node(1);
        }
        NodeData::JsxNamespacedName(d) => {
            d.namespace = c.node(0);
            d.name = c.node(1);
        }
        NodeData::CaseClause(d) => {
            d.expression = c.node(0);
            d.statements = c.list(1);
        }
        NodeData::DefaultClause(d) => {
            c.skip(0);
            d.statements = c.list(1);
        }
        NodeData::HeritageClause(d) => {
            d.types = c.list(0);
        }
        NodeData::CatchClause(d) => {
            d.variable_declaration = c.node(0);
            d.block = c.node(1);
        }
        NodeData::ImportAttributes(d) => {
            d.elements = c.list(0);
        }
        NodeData::ImportAttribute(d) => {
            d.name = c.node(0);
            d.value = c.node(1);
        }
        NodeData::PropertyAssignment(d) => {
            d.modifiers = c.list(0);
            d.name = c.node(1);
            if let Some((token, kind)) = c.token(2) {
                if kind == SyntaxKind::QuestionToken {
                    d.question_token = Some(token);
                } else {
                    d.exclamation_token = Some(token);
                }
            }
            c.skip(3);
            d.initializer = c.node(4);
        }
        NodeData::ShorthandPropertyAssignment(d) => {
            d.modifiers = c.list(0);
            d.name = c.node(1);
            if let Some((token, kind)) = c.token(2) {
                if kind == SyntaxKind::QuestionToken {
                    d.question_token = Some(token);
                } else {
                    d.exclamation_token = Some(token);
                }
            }
            c.skip(3);
            d.equals_token = c.node(4);
            d.object_assignment_initializer = c.node(5);
        }
        NodeData::SpreadAssignment(d) => {
            d.expression = c.node(0);
        }
        NodeData::EnumMember(d) => {
            d.name = c.node(0);
            d.initializer = c.node(1);
        }
        NodeData::JSDocTypeExpression(d) => {
            d.r#type = c.node(0);
        }
        NodeData::JSDocNameReference(d) => {
            d.name = c.node(0);
        }
        NodeData::JSDocNullableType(d) => {
            d.r#type = c.node(0);
        }
        NodeData::JSDocNonNullableType(d) => {
            d.r#type = c.node(0);
        }
        NodeData::JSDocOptionalType(d) => {
            d.r#type = c.node(0);
        }
        NodeData::JSDocVariadicType(d) => {
            d.r#type = c.node(0);
        }
        NodeData::JSDoc(d) => {
            d.comment = c.comment(0);
            d.tags = c.list(1);
        }
        NodeData::JSDocTypeLiteral(d) => {
            d.js_doc_property_tags = c.slice(0);
        }
        NodeData::JSDocSignature(d) => {
            d.type_parameters = c.list(0);
            d.parameters = c.list(1);
            d.r#type = c.node(2);
        }
        NodeData::JSDocLink(d) => {
            d.name = c.node(0);
        }
        NodeData::JSDocLinkCode(d) => {
            d.name = c.node(0);
        }
        NodeData::JSDocLinkPlain(d) => {
            d.name = c.node(0);
        }
        NodeData::JSDocTag(d) => {
            d.tag_name = c.node(0);
            d.comment = c.comment(1);
        }
        NodeData::JSDocAugmentsTag(d) => {
            d.tag_name = c.node(0);
            d.class = c.node(1);
            d.comment = c.comment(2);
        }
        NodeData::JSDocImplementsTag(d) => {
            d.tag_name = c.node(0);
            d.class = c.node(1);
            d.comment = c.comment(2);
        }
        NodeData::JSDocDeprecatedTag(d) => {
            d.tag_name = c.node(0);
            d.comment = c.comment(1);
        }
        NodeData::JSDocPublicTag(d) => {
            d.tag_name = c.node(0);
            d.comment = c.comment(1);
        }
        NodeData::JSDocPrivateTag(d) => {
            d.tag_name = c.node(0);
            d.comment = c.comment(1);
        }
        NodeData::JSDocProtectedTag(d) => {
            d.tag_name = c.node(0);
            d.comment = c.comment(1);
        }
        NodeData::JSDocReadonlyTag(d) => {
            d.tag_name = c.node(0);
            d.comment = c.comment(1);
        }
        NodeData::JSDocOverrideTag(d) => {
            d.tag_name = c.node(0);
            d.comment = c.comment(1);
        }
        NodeData::JSDocCallbackTag(d) => {
            d.tag_name = c.node(0);
            d.type_expression = c.node(1);
            d.full_name = c.node(2);
            d.comment = c.comment(3);
        }
        NodeData::JSDocOverloadTag(d) => {
            d.tag_name = c.node(0);
            d.type_expression = c.node(1);
            d.comment = c.comment(2);
        }
        NodeData::JSDocParameterTag(d) => {
            d.tag_name = c.node(0);
            d.name = c.node(1);
            d.type_expression = c.node(2);
            d.comment = c.comment(3);
        }
        NodeData::JSDocReturnTag(d) => {
            d.tag_name = c.node(0);
            d.type_expression = c.node(1);
            d.comment = c.comment(2);
        }
        NodeData::JSDocThisTag(d) => {
            d.tag_name = c.node(0);
            d.type_expression = c.node(1);
            d.comment = c.comment(2);
        }
        NodeData::JSDocTypeTag(d) => {
            d.tag_name = c.node(0);
            d.type_expression = c.node(1);
            d.comment = c.comment(2);
        }
        NodeData::JSDocTemplateTag(d) => {
            d.tag_name = c.node(0);
            d.constraint = c.node(1);
            d.type_parameters = c.list(2);
            d.comment = c.comment(3);
        }
        NodeData::JSDocTypedefTag(d) => {
            d.tag_name = c.node(0);
            d.type_expression = c.node(1);
            d.full_name = c.node(2);
            d.comment = c.comment(3);
        }
        NodeData::JSDocSeeTag(d) => {
            d.tag_name = c.node(0);
            d.name = c.node(1);
            d.comment = c.comment(2);
        }
        NodeData::JSDocPropertyTag(d) => {
            d.tag_name = c.node(0);
            d.name = c.node(1);
            d.type_expression = c.node(2);
            d.comment = c.comment(3);
        }
        NodeData::JSDocThrowsTag(d) => {
            d.tag_name = c.node(0);
            d.type_expression = c.node(1);
            d.comment = c.comment(2);
        }
        NodeData::JSDocSatisfiesTag(d) => {
            d.tag_name = c.node(0);
            d.type_expression = c.node(1);
            d.comment = c.comment(2);
        }
        NodeData::JSDocImportTag(d) => {
            d.tag_name = c.node(0);
            d.import_clause = c.node(1);
            d.module_specifier = c.node(2);
            d.attributes = c.node(3);
            d.comment = c.comment(4);
        }
        NodeData::SyntaxList(_) => {
            c.skip(0);
        }
        NodeData::PartiallyEmittedExpression(d) => {
            d.expression = c.node(0);
        }
        _ => {}
    }
}
