//! tsc plainJSErrors: the bind/check allowlist for plain JS files —
//! getBindAndCheckDiagnosticsForFileNoCache (123717) filters BOTH
//! bands through it before the comment-directive merge (which plain
//! JS files skip: includeBindAndCheckDiagnostics = !isPlainJs).

use tsrs2_diags::gen as diagnostics;

/// tsc-port: plainJSErrors @6.0.3
/// tsc-hash: 9068c49f4ac525d7b7cac90bd636a3c8f833127e0b5b721ba936caccd9ed5c62
/// tsc-span: _tsc.js:122514-122610
pub(crate) fn is_plain_js_error(code: u32) -> bool {
    PLAIN_JS_ERRORS
        .iter()
        .any(|message| message.code == code)
}

static PLAIN_JS_ERRORS: &[&tsrs2_diags::DiagnosticMessage] = &[
    &diagnostics::Cannot_redeclare_block_scoped_variable_0,
    &diagnostics::A_module_cannot_have_multiple_default_exports,
    &diagnostics::Another_export_default_is_here,
    &diagnostics::The_first_export_default_is_here,
    &diagnostics::Identifier_expected_0_is_a_reserved_word_at_the_top_level_of_a_module,
    &diagnostics::Identifier_expected_0_is_a_reserved_word_in_strict_mode_Modules_are_automatically_in_strict_mode,
    &diagnostics::Identifier_expected_0_is_a_reserved_word_that_cannot_be_used_here,
    &diagnostics::constructor_is_a_reserved_word,
    &diagnostics::delete_cannot_be_called_on_an_identifier_in_strict_mode,
    &diagnostics::Code_contained_in_a_class_is_evaluated_in_JavaScript_s_strict_mode_which_does_not_allow_this_use_of_0_For_more_information_see_https_developer_mozilla_org_en_US_docs_Web_JavaScript_Reference_Strict_mode,
    &diagnostics::Invalid_use_of_0_Modules_are_automatically_in_strict_mode,
    &diagnostics::Invalid_use_of_0_in_strict_mode,
    &diagnostics::A_label_is_not_allowed_here,
    &diagnostics::with_statements_are_not_allowed_in_strict_mode,
    &diagnostics::A_break_statement_can_only_be_used_within_an_enclosing_iteration_or_switch_statement,
    &diagnostics::A_break_statement_can_only_jump_to_a_label_of_an_enclosing_statement,
    &diagnostics::A_class_declaration_without_the_default_modifier_must_have_a_name,
    &diagnostics::A_class_member_cannot_have_the_0_keyword,
    &diagnostics::A_comma_expression_is_not_allowed_in_a_computed_property_name,
    &diagnostics::A_continue_statement_can_only_be_used_within_an_enclosing_iteration_statement,
    &diagnostics::A_continue_statement_can_only_jump_to_a_label_of_an_enclosing_iteration_statement,
    &diagnostics::A_continue_statement_can_only_jump_to_a_label_of_an_enclosing_iteration_statement,
    &diagnostics::A_default_clause_cannot_appear_more_than_once_in_a_switch_statement,
    &diagnostics::A_default_export_must_be_at_the_top_level_of_a_file_or_module_declaration,
    &diagnostics::A_definite_assignment_assertion_is_not_permitted_in_this_context,
    &diagnostics::A_destructuring_declaration_must_have_an_initializer,
    &diagnostics::A_get_accessor_cannot_have_parameters,
    &diagnostics::A_rest_element_cannot_contain_a_binding_pattern,
    &diagnostics::A_rest_element_cannot_have_a_property_name,
    &diagnostics::A_rest_element_cannot_have_an_initializer,
    &diagnostics::A_rest_element_must_be_last_in_a_destructuring_pattern,
    &diagnostics::A_rest_parameter_cannot_have_an_initializer,
    &diagnostics::A_rest_parameter_must_be_last_in_a_parameter_list,
    &diagnostics::A_rest_parameter_or_binding_pattern_may_not_have_a_trailing_comma,
    &diagnostics::A_return_statement_cannot_be_used_inside_a_class_static_block,
    &diagnostics::A_set_accessor_cannot_have_rest_parameter,
    &diagnostics::A_set_accessor_must_have_exactly_one_parameter,
    &diagnostics::An_export_declaration_can_only_be_used_at_the_top_level_of_a_module,
    &diagnostics::An_export_declaration_cannot_have_modifiers,
    &diagnostics::An_import_declaration_can_only_be_used_at_the_top_level_of_a_module,
    &diagnostics::An_import_declaration_cannot_have_modifiers,
    &diagnostics::An_object_member_cannot_be_declared_optional,
    &diagnostics::Argument_of_dynamic_import_cannot_be_spread_element,
    &diagnostics::Cannot_assign_to_private_method_0_Private_methods_are_not_writable,
    &diagnostics::Cannot_redeclare_identifier_0_in_catch_clause,
    &diagnostics::Catch_clause_variable_cannot_have_an_initializer,
    &diagnostics::Class_decorators_can_t_be_used_with_static_private_identifier_Consider_removing_the_experimental_decorator,
    &diagnostics::Classes_can_only_extend_a_single_class,
    &diagnostics::Classes_may_not_have_a_field_named_constructor,
    &diagnostics::Did_you_mean_to_use_a_An_can_only_follow_a_property_name_when_the_containing_object_literal_is_part_of_a_destructuring_pattern,
    &diagnostics::Duplicate_label_0,
    &diagnostics::Dynamic_imports_can_only_accept_a_module_specifier_and_an_optional_set_of_attributes_as_arguments,
    &diagnostics::for_await_loops_cannot_be_used_inside_a_class_static_block,
    &diagnostics::JSX_attributes_must_only_be_assigned_a_non_empty_expression,
    &diagnostics::JSX_elements_cannot_have_multiple_attributes_with_the_same_name,
    &diagnostics::JSX_expressions_may_not_use_the_comma_operator_Did_you_mean_to_write_an_array,
    &diagnostics::JSX_property_access_expressions_cannot_include_JSX_namespace_names,
    &diagnostics::Jump_target_cannot_cross_function_boundary,
    &diagnostics::Line_terminator_not_permitted_before_arrow,
    &diagnostics::Modifiers_cannot_appear_here,
    &diagnostics::Only_a_single_variable_declaration_is_allowed_in_a_for_in_statement,
    &diagnostics::Only_a_single_variable_declaration_is_allowed_in_a_for_of_statement,
    &diagnostics::Private_identifiers_are_not_allowed_outside_class_bodies,
    &diagnostics::Private_identifiers_are_only_allowed_in_class_bodies_and_may_only_be_used_as_part_of_a_class_member_declaration_property_access_or_on_the_left_hand_side_of_an_in_expression,
    &diagnostics::Property_0_is_not_accessible_outside_class_1_because_it_has_a_private_identifier,
    &diagnostics::Tagged_template_expressions_are_not_permitted_in_an_optional_chain,
    &diagnostics::The_left_hand_side_of_a_for_of_statement_may_not_be_async,
    &diagnostics::The_variable_declaration_of_a_for_in_statement_cannot_have_an_initializer,
    &diagnostics::The_variable_declaration_of_a_for_of_statement_cannot_have_an_initializer,
    &diagnostics::Trailing_comma_not_allowed,
    &diagnostics::Variable_declaration_list_cannot_be_empty,
    &diagnostics::_0_and_1_operations_cannot_be_mixed_without_parentheses,
    &diagnostics::_0_expected,
    &diagnostics::_0_is_not_a_valid_meta_property_for_keyword_1_Did_you_mean_2,
    &diagnostics::_0_list_cannot_be_empty,
    &diagnostics::_0_modifier_already_seen,
    &diagnostics::_0_modifier_cannot_appear_on_a_constructor_declaration,
    &diagnostics::_0_modifier_cannot_appear_on_a_module_or_namespace_element,
    &diagnostics::_0_modifier_cannot_appear_on_a_parameter,
    &diagnostics::_0_modifier_cannot_appear_on_class_elements_of_this_kind,
    &diagnostics::_0_modifier_cannot_be_used_here,
    &diagnostics::_0_modifier_must_precede_1_modifier,
    &diagnostics::_0_declarations_can_only_be_declared_inside_a_block,
    &diagnostics::_0_declarations_must_be_initialized,
    &diagnostics::extends_clause_already_seen,
    &diagnostics::let_is_not_allowed_to_be_used_as_a_name_in_let_or_const_declarations,
    &diagnostics::Class_constructor_may_not_be_a_generator,
    &diagnostics::Class_constructor_may_not_be_an_accessor,
    &diagnostics::await_expressions_are_only_allowed_within_async_functions_and_at_the_top_levels_of_modules,
    &diagnostics::await_using_statements_are_only_allowed_within_async_functions_and_at_the_top_levels_of_modules,
    &diagnostics::Private_field_0_must_be_declared_in_an_enclosing_class,
    &diagnostics::This_condition_will_always_return_0_since_JavaScript_compares_objects_by_reference_not_value,
];
