import json
C=[]
def add(name, src): C.append({"name":name,"src":src})

# ── assignability & literals ──
add("asg_num_str", "const x: number = 'a';")
add("asg_lit_widen", "let x = 1; const y: 2 = x;")
add("asg_lit_ok", "const x: 1 = 1;")
add("asg_union_ok", "const x: number | string = 'a';")
add("asg_union_bad", "const x: number | boolean = 'a';")
add("asg_never", "const x: never = 1 as never; const y: number = x;")
add("asg_any_to_num", "declare const a: any; const x: number = a;")
add("asg_unknown_bad", "declare const u: unknown; const x: number = u;")
add("asg_null_strict", "const x: string = null;")
add("asg_undef_strict", "const x: number = undefined;")
add("asg_void_fn", "const f: () => void = () => 42;")
add("asg_obj_excess", "const o: { a: number } = { a: 1, b: 2 };")
add("asg_obj_missing", "const o: { a: number; b: string } = { a: 1 };")
add("asg_obj_ok", "const o: { a: number } = { a: 1 };")
add("asg_literal_obj_nested", "const o: { a: { b: number } } = { a: { b: 'x' } };")
add("asg_arr_elem", "const a: number[] = [1, 'x'];")
add("asg_const_assert", "const o = { a: 1 } as const; const x: 1 = o.a;")
add("asg_tuple_len", "const t: [number, string] = [1];")
add("asg_tuple_extra", "const t: [number] = [1, 2];")
add("asg_intersection", "type A = { a: number }; type B = { b: string }; const x: A & B = { a: 1 };")

# ── unions / intersections ──
add("uni_distribute", "type T = (number | string)[]; const x: T = [1, 'a'];")
add("uni_index", "type T = { a: number } | { a: string }; declare const t: T; const x: number = t.a;")
add("int_method", "type A = { f(): number }; type B = { g(): string }; declare const x: A & B; const n: number = x.f();")
add("uni_call", "declare const f: (() => number) | (() => string); const x: number = f();")
add("uni_optional", "type T = { a?: number }; const x: T = {};")

# ── narrowing ──
add("nar_typeof_str", "function f(x: string | number) { if (typeof x === 'string') { const s: string = x; } }")
add("nar_typeof_else", "function f(x: string | number) { if (typeof x === 'string') {} else { const n: number = x; } }")
add("nar_truthy", "function f(x: string | null) { if (x) { const s: string = x; } }")
add("nar_eq_null", "function f(x: string | null) { if (x !== null) { const s: string = x; } }")
add("nar_in_op", "type A = { a: number }; type B = { b: string }; function f(x: A | B) { if ('a' in x) { const n: number = x.a; } }")
add("nar_discriminated", "type T = { k: 'a'; v: number } | { k: 'b'; v: string }; function f(t: T) { if (t.k === 'a') { const n: number = t.v; } }")
add("nar_instanceof", "class C { x = 1; } function f(o: object) { if (o instanceof C) { const n: number = o.x; } }")
add("nar_typeof_bad", "function f(x: string | number) { if (typeof x === 'string') { const n: number = x; } }")
add("nar_assert_fn", "function assert(x: unknown): asserts x is string {} function f(u: unknown) { assert(u); const s: string = u; }")
add("nar_guard_fn", "function isStr(x: unknown): x is string { return true; } function f(u: unknown) { if (isStr(u)) { const s: string = u; } }")
add("nar_neg_guard", "function isStr(x: unknown): x is string { return true; } function f(u: unknown) { if (!isStr(u)) { return; } const s: string = u; }")
add("nar_exhaustive", "type T = 'a' | 'b'; function f(t: T): number { if (t === 'a') return 1; if (t === 'b') return 2; const n: never = t; return n; }")
add("nar_double", "function f(x: string | number | boolean) { if (typeof x === 'string') {} else if (typeof x === 'number') {} else { const b: boolean = x; } }")

# ── generics ──
add("gen_id", "declare function id<T>(x: T): T; const n: number = id(5);")
add("gen_ctx", "interface Box<T> { v: T; } declare function make<T>(): Box<T>; const b: Box<string> = make();")
add("gen_constraint_ok", "function f<T extends { a: number }>(x: T) { return x.a; } f({ a: 1 });")
add("gen_constraint_bad", "function f<T extends { a: number }>(x: T) {} f({ b: 1 });")
add("gen_default", "interface B<T = number> { v: T; } const b: B = { v: 1 };")
add("gen_infer_arr", "declare function first<T>(a: T[]): T; const n: number = first([1, 2]);")
add("gen_variance_fn", "const f: () => number = (() => 'x') as () => string;")
add("gen_nested", "declare function wrap<T>(x: T): { v: T }; const r = wrap(5); const n: number = r.v;")
add("gen_keyof", "declare function get<T, K extends keyof T>(o: T, k: K): T[K]; const o = { a: 1 }; const n: number = get(o, 'a');")
add("gen_two_params", "declare function pair<A, B>(a: A, b: B): [A, B]; const p = pair(1, 'x'); const n: number = p[0]; const s: string = p[1];")
add("gen_promise_var", "const p: Promise<string> = Promise.resolve(42);")
add("gen_map_ctx", "const m: Map<string, number> = new Map(); const v: number | undefined = m.get('x');")

# ── functions / overloads ──
add("fn_optional_param", "function f(a: number, b?: string) {} f(1);")
add("fn_too_few", "function f(a: number, b: string) {} f(1);")
add("fn_too_many", "function f(a: number) {} f(1, 2);")
add("fn_rest", "function f(...xs: number[]) {} f(1, 2, 3);")
add("fn_rest_bad", "function f(...xs: number[]) {} f(1, 'x');")
add("fn_this_param", "function f(this: { a: number }) { return this.a; }")
add("fn_overload", "function f(x: number): number; function f(x: string): string; function f(x: any): any { return x; } const n: number = f(1);")
add("fn_overload_bad", "function f(x: number): number; function f(x: string): string; function f(x: any): any { return x; } f(true);")
add("fn_default_param", "function f(a: number = 1) {} f();")
add("fn_contextual_cb", "declare function each<T>(a: T[], f: (x: T) => void): void; each([1, 2], (x) => { const n: number = x; });")
add("fn_return_mismatch", "function f(): number { return 'x'; }")
add("fn_arrow_return", "const f = (): number => 'x';")

# ── objects / spread / index ──
add("obj_spread_basic", "const o = { ...{ a: 1 }, b: 2 }; const x: { a: number; b: number } = o;")
add("obj_spread_override", "const o = { ...{ x: 1 }, ...{ x: 'a' } }; const s: string = o.x;")
add("obj_spread_optional", "declare const p: { x?: string }; const o = { ...{ x: 1 }, ...p }; const v: string | number = o.x;")
add("obj_spread_union", "declare const u: { a: 1 } | { b: 2 }; const o = { ...u }; const x: { a: 1 } | { b: 2 } = o;")
add("obj_shorthand", "const a = 1; const o = { a }; const n: number = o.a;")
add("obj_index_sig", "const o: { [k: string]: number } = { a: 1 }; const n: number = o.foo;")
add("obj_index_bad", "const o: { [k: string]: number } = { a: 'x' };")
add("obj_getter", "const o = { get v(): number { return 1; } }; const n: number = o.v;")
add("obj_method", "const o = { f(x: number): number { return x; } }; const n: number = o.f(1);")
add("obj_readonly", "const o: { readonly a: number } = { a: 1 }; o.a = 2;")
add("obj_optional_access", "declare const o: { a?: number }; const x: number = o.a;")
add("obj_computed", "const k = 'a'; const o = { [k]: 1 };")
add("obj_nested_spread", "const o = { outer: { ...{ p: 1 } } }; const x: { outer: { p: number } } = o;")

# ── classes ──
add("cls_field", "class C { x: number = 1; } const c = new C(); const n: number = c.x;")
add("cls_private", "class C { private x = 1; } const c = new C(); const n = c.x;")
add("cls_method", "class C { f(): number { return 1; } } const n: number = new C().f();")
add("cls_inherit", "class A { x = 1; } class B extends A { y = 2; } const b = new B(); const n: number = b.x + b.y;")
add("cls_abstract", "abstract class A { abstract f(): number; } const a = new A();")
add("cls_static", "class C { static x = 1; } const n: number = C.x;")
add("cls_ctor_args", "class C { constructor(public x: number) {} } const c = new C(1); const n: number = c.x;")
add("cls_ctor_missing", "class C { constructor(x: number) {} } new C();")
add("cls_this_type", "class C { x = 1; f() { const n: number = this.x; } }")
add("cls_readonly_field", "class C { readonly x = 1; g() { this.x = 2; } }")
add("cls_accessor", "class C { get v(): number { return 1; } } const n: number = new C().v;")
add("cls_implements", "interface I { x: number; } class C implements I { x = 1; }")
add("cls_implements_bad", "interface I { x: number; } class C implements I {}")
add("cls_super", "class A { constructor(public x: number) {} } class B extends A { constructor() { super(1); } }")

# ── enums / tuples ──
add("enum_basic", "enum E { A, B } const e: E = E.A; const n: number = e;")
add("enum_str", "enum E { A = 'a', B = 'b' } const e: E = E.A;")
add("enum_member_type", "enum E { A, B } function f(e: E.A) {} f(E.A);")
add("tuple_index", "const t: [number, string] = [1, 'a']; const n: number = t[0]; const s: string = t[1];")
add("tuple_readonly", "const t: readonly [number, string] = [1, 'a']; t[0] = 2;")
add("tuple_optional", "const t: [number, string?] = [1];")
add("tuple_rest", "const t: [number, ...string[]] = [1, 'a', 'b'];")
add("tuple_destructure", "const [a, b]: [number, string] = [1, 'x']; const n: number = a; const s: string = b;")

# ── mapped / conditional / keyof / template ──
add("map_partial", "type P = Partial<{ a: number; b: string }>; const x: P = { a: 1 };")
add("map_readonly", "type R = Readonly<{ a: number }>; const x: R = { a: 1 }; x.a = 2;")
add("map_pick", "type P = Pick<{ a: number; b: string }, 'a'>; const x: P = { a: 1 };")
add("map_record", "type R = Record<string, number>; const x: R = { a: 1 }; const n: number = x.foo;")
add("cond_basic", "type T<X> = X extends string ? 1 : 2; const a: T<string> = 1; const b: T<number> = 2;")
add("cond_infer", "type Elem<T> = T extends (infer U)[] ? U : never; const x: Elem<number[]> = 1;")
add("keyof_basic", "type K = keyof { a: 1; b: 2 }; const k: K = 'a';")
add("keyof_bad", "type K = keyof { a: 1; b: 2 }; const k: K = 'c';")
add("indexed_access", "type T = { a: number; b: string }; const x: T['a'] = 1;")
add("template_lit", "type T = `pre_${string}`; const x: T = 'pre_foo';")
add("template_lit_bad", "type T = `pre_${string}`; const x: T = 'no';")

# ── control flow ──
add("cf_definite", "let x: number; x = 1; const y: number = x;")
add("cf_use_before", "let x: number; const y: number = x;")
add("cf_const_uninit", "const x: number;")
add("cf_unreachable", "function f(): number { return 1; const x = 2; }")
add("cf_if_return", "function f(x: boolean): number { if (x) { return 1; } return 2; }")
add("cf_switch", "function f(x: 1 | 2): string { switch (x) { case 1: return 'a'; case 2: return 'b'; } }")
add("cf_throw", "function f(): number { throw new Error(); }")
add("cf_while_true", "function f(): number { while (true) {} }")
add("cf_assign_in_branch", "function f(b: boolean) { let x: number; if (b) { x = 1; } else { x = 2; } const y: number = x; }")

# ── misc / operators ──
add("op_add_num", "const x: number = 1 + 2;")
add("op_add_str", "const x: string = 'a' + 'b';")
add("op_add_mixed", "const x: string = 1 + 'a';")
add("op_compare", "const x: boolean = 1 < 2;")
add("op_logical", "const x: number | string = (1 as number) || 'a';")
add("op_nullish", "declare const a: number | null; const x: number = a ?? 0;")
add("op_optional_chain", "declare const o: { a?: { b: number } }; const x: number | undefined = o.a?.b;")
add("op_not", "const x: boolean = !1;")
add("op_typeof_expr", "const x: string = typeof 1;")
add("op_ternary", "const x: number | string = true ? 1 : 'a';")

json.dump(C, open('/tmp/cases.json','w'))
print(f"generated {len(C)} cases")
