import json
C=[]
def add(n,s): C.append({"name":n,"src":s})
# more assignability / structural
add("b2_fn_param_contra", "const f: (x: number) => void = (x: string) => {};")
add("b2_fn_param_widen", "const f: (x: 1 | 2) => void = (x: number) => {};")
add("b2_obj_method_var", "declare const a: { f(): number }; const b: { f(): string } = a;")
add("b2_arr_covariant", "const a: number[] = [1]; const b: (number | string)[] = a;")
add("b2_arr_invariant_param", "declare const a: (x: number) => void; const b: (x: string) => void = a;")
add("b2_readonly_arr", "const a: readonly number[] = [1]; const b: number[] = a;")
add("b2_mut_to_readonly", "const a: number[] = [1]; const b: readonly number[] = a;")
add("b2_nested_optional", "const o: { a?: { b: number } } = { a: { b: 1 } };")
add("b2_excess_nested", "const o: { a: { b: number } } = { a: { b: 1, c: 2 } };")
add("b2_func_overload_pick", "interface F { (x: number): string; (x: string): number; } declare const f: F; const s: string = f(1);")
# literals / widening
add("b2_const_obj_literal", "const o = { a: 1 }; const n: 1 = o.a;")
add("b2_let_widen", "let s = 'a'; const x: string = s;")
add("b2_as_const_arr", "const a = [1, 2] as const; const x: readonly [1, 2] = a;")
add("b2_template_widen", "const x = `a${1}b`; const y: string = x;")
add("b2_enum_const", "const enum E { A = 1 } const x: number = E.A;")
add("b2_bigint_lit", "const x: bigint = 1n;")
add("b2_neg_lit", "const x: -1 = -1;")
# narrowing advanced
add("b2_nar_array_isarray", "function f(x: number | number[]) { if (Array.isArray(x)) { const a: number[] = x; } }")
add("b2_nar_typeof_obj", "function f(x: object | number) { if (typeof x === 'object') { const o: object = x; } }")
add("b2_nar_null_undef", "function f(x: number | null | undefined) { if (x != null) { const n: number = x; } }")
add("b2_nar_assign", "function f(x: number | string) { x = 5; const n: number = x; }")
add("b2_nar_return_early", "function f(x: string | null): string { if (x === null) return ''; return x; }")
add("b2_nar_and_chain", "function f(x: { a?: number }) { if (x.a) { const n: number = x.a; } }")
add("b2_nar_typeof_fn", "function f(x: (() => void) | number) { if (typeof x === 'function') { x(); } }")
add("b2_nar_literal_eq", "function f(x: 'a' | 'b' | 'c') { if (x === 'a') {} else { const y: 'b' | 'c' = x; } }")
add("b2_nar_in_nested", "type T = { a: { x: number } } | { b: { y: string } }; function f(t: T) { if ('a' in t) { const n: number = t.a.x; } }")
# generics advanced
add("b2_gen_default_use", "type Cont<T = string> = { v: T }; const c: Cont = { v: 'x' }; const s: string = c.v;")
add("b2_gen_conditional_ret", "declare function f<T>(x: T): T extends string ? number : boolean; const a: number = f('x');")
add("b2_gen_constraint_default", "function f<T extends number = number>(x: T): T { return x; } const n: number = f(5);")
add("b2_gen_rec_infer", "type Flat<T> = T extends (infer U)[] ? Flat<U> : T; const x: Flat<number[][]> = 1;")
add("b2_gen_mapped_generic", "type M<T> = { [K in keyof T]: T[K] }; const x: M<{ a: number }> = { a: 1 };")
add("b2_gen_partial_infer", "declare function merge<T>(a: T, b: Partial<T>): T; const r = merge({ a: 1 }, { a: 2 }); const n: number = r.a;")
add("b2_gen_tuple_spread", "declare function f<T extends unknown[]>(...args: T): T; const r = f(1, 'x'); const n: number = r[0];")
add("b2_gen_this_return", "class Box<T> { v!: T; set(v: T): this { return this; } } const b = new Box<number>(); const b2: Box<number> = b.set(1);")
# functions
add("b2_fn_void_return_undef", "const f: () => void = () => { return undefined; };")
add("b2_fn_never_throw", "function f(): never { throw 1; } const n: never = f();")
add("b2_fn_optional_undefined", "function f(x?: number) { const y: number | undefined = x; }")
add("b2_fn_destructure_param", "function f({ a }: { a: number }) { const n: number = a; }")
add("b2_fn_default_destructure", "function f({ a = 1 }: { a?: number } = {}) { const n: number = a; }")
add("b2_fn_rest_tuple", "function f(...args: [number, string]) { const n: number = args[0]; }")
add("b2_fn_generic_callback", "function map<T, U>(a: T[], f: (x: T) => U): U[] { return a.map(f); }")
add("b2_fn_overload_impl_check", "function f(x: number): number; function f(x: string): number; function f(x: number | string): number { return 0; }")
# classes advanced
add("b2_cls_generic", "class Box<T> { constructor(public v: T) {} } const b = new Box(5); const n: number = b.v;")
add("b2_cls_protected_access", "class A { protected x = 1; } class B extends A { f() { return this.x; } }")
add("b2_cls_static_method", "class C { static make(): C { return new C(); } } const c: C = C.make();")
add("b2_cls_override", "class A { f(): number { return 1; } } class B extends A { f(): number { return 2; } }")
add("b2_cls_abstract_impl", "abstract class A { abstract f(): number; } class B extends A { f(): number { return 1; } } const b: A = new B();")
add("b2_cls_getter_setter", "class C { private _x = 0; get x(): number { return this._x; } set x(v: number) { this._x = v; } }")
add("b2_cls_index_sig", "class C { [k: string]: number; } const c = new C(); const n: number = c.foo;")
add("b2_cls_private_field", "class C { #x = 1; f() { return this.#x; } }")
add("b2_cls_param_prop_readonly", "class C { constructor(readonly x: number) {} } const c = new C(1); const n: number = c.x;")
add("b2_cls_super_method", "class A { f(): number { return 1; } } class B extends A { f(): number { return super.f() + 1; } }")
# enums / tuples
add("b2_enum_reverse", "enum E { A, B } const name = E[0]; const s: string = name;")
add("b2_enum_compute", "enum E { A = 1, B = A * 2 } const x: number = E.B;")
add("b2_tuple_named", "type T = [x: number, y: string]; const t: T = [1, 'a'];")
add("b2_tuple_concat", "type A = [number]; type B = [...A, string]; const t: B = [1, 'a'];")
add("b2_tuple_length", "const t: [number, string] = [1, 'a']; const n: 2 = t.length;")
add("b2_tuple_optional_access", "const t: [number, string?] = [1]; const s: string | undefined = t[1];")
# mapped / conditional / template
add("b2_map_remove_opt", "type R<T> = { [K in keyof T]-?: T[K] }; const x: R<{ a?: number }> = { a: 1 };")
add("b2_map_as_remap", "type Rename<T> = { [K in keyof T as `get_${string & K}`]: T[K] }; const x: Rename<{ a: number }> = { get_a: 1 };")
add("b2_cond_distribute", "type NonNull<T> = T extends null | undefined ? never : T; const x: NonNull<string | null> = 'a';")
add("b2_cond_nested", "type T<X> = X extends string ? 'str' : X extends number ? 'num' : 'other'; const a: T<number> = 'num';")
add("b2_template_union", "type T = `${'a' | 'b'}_x`; const x: T = 'a_x';")
add("b2_keyof_union", "type T = keyof ({ a: 1 } | { b: 2 }); const x: T = 'a' as never;")
add("b2_indexed_union", "type T = { a: number; b: string }; const x: T['a' | 'b'] = 1;")
add("b2_infer_return", "type Ret<T> = T extends (...a: any) => infer R ? R : never; const x: Ret<() => number> = 1;")
add("b2_infer_param", "type P<T> = T extends (x: infer U) => any ? U : never; const x: P<(n: number) => void> = 1;")
# control flow
add("b2_cf_exhaustive_enum", "enum E { A, B } function f(e: E): string { switch (e) { case E.A: return 'a'; case E.B: return 'b'; } }")
add("b2_cf_assert_never", "type T = 'a' | 'b'; function f(t: T): number { switch (t) { case 'a': return 1; case 'b': return 2; default: const n: never = t; return n; } }")
add("b2_cf_do_while", "function f(): number { do { return 1; } while (true); }")
add("b2_cf_for_return", "function f(a: number[]): number { for (const x of a) { return x; } return 0; }")
add("b2_cf_try_finally", "function f(): number { try { return 1; } finally {} }")
add("b2_cf_nested_if", "function f(x: number): string { if (x > 0) { if (x > 1) return 'a'; return 'b'; } return 'c'; }")
add("b2_cf_label_break", "function f(): number { outer: for (;;) { break outer; } return 1; }")
add("b2_cf_definite_field", "class C { x: number; constructor() { this.x = 1; } }")
add("b2_cf_definite_field_bad", "class C { x: number; }")
# operators / misc
add("b2_op_in_array", "const x: boolean = 0 in [1, 2];")
add("b2_op_instanceof_narrow", "class C {} const o: unknown = new C(); const b: boolean = o instanceof C;")
add("b2_op_spread_call", "function f(a: number, b: number) {} const args: [number, number] = [1, 2]; f(...args);")
add("b2_op_spread_array", "const a = [1, 2]; const b = [...a, 3]; const x: number[] = b;")
add("b2_op_comma", "const x: number = (1, 2);")
add("b2_op_void", "const x: undefined = void 0;")
add("b2_op_delete", "declare const o: { a?: number }; delete o.a;")
add("b2_op_exponent", "const x: number = 2 ** 3;")
add("b2_op_bitwise", "const x: number = 5 & 3;")
add("b2_op_string_index", "const s = 'abc'; const c: string = s[0];")
add("b2_op_unary_minus", "const x: number = -5;")
add("b2_op_typeof_undef", "const x: 'undefined' | 'number' = typeof undefined;")
json.dump(C, open('/tmp/cases2.json','w'))
print(f"generated {len(C)} batch-2 cases")
