from pathlib import Path
import gzip,hashlib,json,subprocess,time
R=Path('/Users/hiramatsu/dev/tsc-rs-emitter-final-variable-producer-prep');B=R/'docs/design/greenfield/slices/emitter-final-batch/integration';O=Path('/tmp/emitter-export-clause-apply-r439');O.mkdir(exist_ok=False);h=lambda b:hashlib.sha256(b).hexdigest();r=json.loads((B/'records/module-boundary-validation-r433/validation-manifest.json').read_bytes());assert not r['qualified'] and len(r['steps'])==4 and r['steps'][-1]['exact_x2_lines']==407;assert h(subprocess.check_output(['git','diff','HEAD'],cwd=R))==r['candidate_diff_sha256'];assert 'proposed bounded fix is the right one' in json.loads(Path('/tmp/emitter-namespace-prefix-review-r436/response.json').read_bytes())['result']
f=R/'crates/compiler/tests/fixtures/token-comment-phases.json';before=f.read_bytes();old=json.loads(before);assert len(old['cases'])==245;(O/'before.json.gz').write_bytes(gzip.compress(before,mtime=0));files=[]
for directory in ['emitter-export-clause-r437','emitter-export-clause-controls-r438']:
 p=Path('/tmp')/directory;m=json.loads((p/'manifest.json').read_bytes())
 for row in m['files']:
  dest=R/row['path'];assert h(dest.read_bytes())==row['before'];data=(p/row['path']).read_bytes();assert h(data)==row['after'];dest.write_bytes(data);files.append(row)
report={'head':r['head'],'source_qualified':False,'review':'actual Opus195 endorses caller-local owner-aware prefix. Proposal uses export_item_anchor (not review snippet export_keyword) to preserve isTypeOnly. Review explanation of passing namespace-declare was inaccurate: source is declare+export, arithmetic export token end6 lies inside declare; no trailing comment resume, not coincident clause start.','files':files,'steps':[]}
for label,cmd in [('export-clause-oracle-r439',['node','scripts/observe-token-comment-phases.mjs','--write']),('export-clause-format-r439',['cargo','fmt','--all'])]:
 t=time.monotonic();code=subprocess.run(['python3',str(B/'run-local.py'),label,*cmd],cwd=R).returncode;report['steps'].append({'label':label,'exit':code,'seconds':time.monotonic()-t});(O/'manifest.json').write_text(json.dumps(report,indent=2)+'\n');assert code==0
new=json.loads(f.read_bytes());assert new['cases'][:245]==old['cases'];assert len(new['cases'])==265 and len({c['case_id'] for c in new['cases']})==265;report.update(original_observations_unchanged=True,added_complete_commands=20,fixture_sha256=h(f.read_bytes()),candidate_diff_sha256=h(subprocess.check_output(['git','diff','HEAD'],cwd=R)));(O/'manifest.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report))
