[package]
name = "tsc-rs-checker"
version.workspace = true
edition.workspace = true
license.workspace = true

[package.metadata.tsc-rs]
role = "checker"
dev-profile-opt-level = 3

[lib]
name = "tsc_checker"
path = "src/lib.rs"

[dependencies]
indexmap = "2"
serde_json = { version = "1.0", features = ["preserve_order"] }
tsc-binder.workspace = true
tsc-diagnostics.workspace = true
tsc-emitter.workspace = true
tsc-program.workspace = true
tsc-syntax.workspace = true
tsc-types.workspace = true

[lints]
workspace = true
