[package]
name = "tsc-rs-program"
version.workspace = true
edition.workspace = true
license.workspace = true

[package.metadata.tsc-rs]
role = "program"

[lib]
name = "tsc_program"
path = "src/lib.rs"

[dependencies]
serde_json = { version = "1.0", features = ["preserve_order"] }
tsc-diagnostics.workspace = true
tsc-host.workspace = true
tsc-syntax.workspace = true
tsc-types.workspace = true

[lints]
workspace = true
