from pathlib import Path
import json
root=Path('/Users/hiramatsu/dev/tsc-rs-emitter-final-variable-producer-prep')
rows={
'E-ENTRY':('Typed emit/no-emit entry separation and sink behavior.', ['crates/compiler/tests/integration/emit_session_contract.rs','crates/compiler/tests/integration/upstream_no_emit_harness_contract.rs']),
'E-PLAN-SCRIPT':('Admitted output selection, root, mode and path plans.', ['crates/emitter/tests/integration/output_plan_contract.rs','crates/compiler/tests/integration/h2_8a_output_matrix.rs']),
'E-RESOLVER-IDENTITY-G':('Mounted parse identities and typed original-node projection.', ['crates/emitter/tests/unit/factory_seams/tests.rs','crates/emitter/tests/integration/factory_transform_contract.rs']),
'E-METADATA-BASE':('Sparse transform metadata, original identity and independent comment/map ranges.', ['crates/emitter/tests/unit/factory_seams/tests.rs','crates/emitter/tests/unit/source_map/tests.rs']),
'E-METADATA-G-CLASS':('Named/decorated class and parameter-property provenance across admitted passes.', ['crates/emitter/tests/integration/active_transform_contract.rs','crates/compiler/tests/integration/h2_8a_class_helper_accessor_producers.rs']),
'E-CAPTURE-BASE':('Admitted async lexical arguments/super capture and preserved source ranges.', ['crates/compiler/tests/integration/async_arrow_body_ranges.rs','crates/emitter/tests/integration/active_transform_contract.rs']),
'E-CHECKER-FACTS-BASE':('Existing typed resolver facts; adjacent missing-body return inference correction remains with the checker.', ['crates/checker/tests/unit/functions/tests.rs','crates/compiler/tests/integration/declaration_transformer_replay_decision_equal.rs']),
'E-NAMES-BASE':('Generated identity, allocation scope and finalized printable spelling.', ['crates/emitter/tests/unit/generated_bindings/tests.rs','crates/emitter/tests/unit/target_bindings_tests.rs']),
'E-NAMES-CLASS-G':('Class temporary allocation phases and loop-local ownership.', ['crates/emitter/tests/integration/active_transform_contract.rs']),
'E-HELPERS-IMPORT-STATE':('Imported helper identity, scope, dependency ordering and complete output/map observations.', ['crates/compiler/tests/integration/h2_8a_import_helpers.rs','crates/compiler/tests/integration/h2_5h_static_this_super_witnesses.rs']),
'E-PRINTER-G':('Ordinary arrow parameter/list phases, retained-token hook refusal and measured line-layout owners.', ['crates/emitter/tests/integration/factory_transform_contract.rs','crates/emitter/src/printer.rs']),
'E-COMMENT-SCOPE-H':('Three independent comment scope values, source-aware cursors and failure/reuse behavior.', ['crates/emitter/tests/integration/comment_scope_witness_contract.rs','crates/emitter/tests/unit/comment_scope_predicate/tests.rs']),
'E-MAPS':('JavaScript/declaration map and callback tuples across the exercised command families.', ['crates/compiler/tests/h2_6a_map_option_projection.rs','crates/compiler/tests/h2_7e_declaration_maps.rs','crates/compiler/tests/h2_7e_declaration_map_apis.rs']),
'E-OUTPUT-FUTURE':('Active JavaScript/declaration/map/bundle products, sink errors and output ordering; builder/build-info remains unsupported.', ['crates/compiler/tests/h2_7d_bundle_sinks.rs','crates/compiler/tests/integration/h2_8a_output_filesystem.rs','crates/compiler/tests/integration/h2_8a_output_matrix.rs']),
'E-RECOVERY-FACTS':('Parser-owned retained facts, rollback and bounded context admission; original parser-input proof and complete newly admitted commands.', ['crates/syntax/tests/emitter_recovery.rs','crates/syntax/tests/unit/parser/recovery.rs','crates/compiler/tests/emitter_final_universe.rs']),
'E-COMMENTS-G':('Typed token/comment progress and the observed collector/Unicode/relocated-owner contracts.', ['crates/emitter/tests/source_comment_topology_contract.rs','crates/emitter/tests/unit/token_cursor/tests.rs','crates/compiler/tests/integration/h2_8a_one_sided_class_comments.rs']),
'E-COMMENT-PHASES-A36':('Modifier/source-file/list/spread comment phases in the enumerated controls.', ['crates/emitter/tests/token_comment_phase_metadata_contract.rs','crates/compiler/tests/integration/h2_8a_token_comment_phases.rs']),
'E-COMMENT-ELLIPSIS-A37':('Rest/spread/JSX ordinary child comment and map phases in the enumerated controls.', ['crates/emitter/tests/ellipsis_comment_metadata_contract.rs','crates/compiler/tests/integration/h2_8a_ellipsis_comment_owners.rs']),
}
plan=json.loads(Path('/tmp/emitter-delivery-plan-r227.json').read_text());assert set(rows)==set(plan['delegated_rows'])
for scope,paths in rows.values():
 for p in paths:assert (root/p).is_file(),p
Path('/tmp/emitter-delivery-proof-matrix-r250.json').write_text(json.dumps({'status':'Preparation only. These are existing test/source references, not an execution claim. Final V full-CI receipt and actual hosted/merge result are required for qualification; r211-r224 retain their own source attribution. Ignore counts must come from actual libtest results.','rows':{k:{'scope':scope,'test_references':paths} for k,(scope,paths) in rows.items()},'reference_rules':['D changes only architecture-validation.md after all final V gates and merge M.','Profile table:22 H2runtime+1H2transition revalidated at V;1H1emit historical;24total. Compare runtime_inputs hashes to V for current profiles, not the H1 historical inputs.','Link complete profile runtime_inputs arrays through V artifact path/hash table; do not duplicate1000rows. Vtree==Mtree proves all tracked inputs unchanged.','Use selected_rows in owner identitiesr249, with pinned TypeScript source SHA and recomputed body SHA at V. Four guessed absent names in raw candidate inventory are excluded from selections.','Do not infer universal compatibility, build/watch, JSONsource-kind, public API reemit or TS7 completion.']},indent=2)+'\n')
print('Prepared18boundedproofscopes;',sum(len(p) for _,p in rows.values()),'existingtest/source references')
