[package]
name = "tsc-rs-binder"
version.workspace = true
edition.workspace = true
license.workspace = true

[package.metadata.tsc-rs]
role = "binder"
dev-profile-opt-level = 3

[lib]
name = "tsc_binder"
path = "src/lib.rs"

[dependencies]
indexmap = "2"
tsc-diagnostics.workspace = true
tsc-syntax.workspace = true
tsc-types.workspace = true

[lints]
workspace = true
