//! Standalone probe compiled with the identical digest source against the
//! candidate, the restored pre-interface projection, and the main merge base.
#[path = "../crates/xtask/src/recovery_parse_snapshot.rs"]
mod snapshot;

use serde_json::{json, Value};
use std::collections::BTreeMap;
use std::io::{Read, Write};

fn main() {
    let mut bytes = Vec::new();
    std::io::stdin().read_to_end(&mut bytes).unwrap();
    let artifact: Value = serde_json::from_slice(&bytes).unwrap();
    assert_eq!(artifact["schema"], 1);
    assert_eq!(artifact["kind"], "emitter-recovery-parse-snapshot");
    let digest_hash = snapshot::sha256(include_bytes!(
        "../crates/xtask/src/recovery_parse_snapshot.rs"
    ));
    assert_eq!(artifact["digest_code_sha256"], digest_hash);
    let mut digests = BTreeMap::new();
    let mut recovery_digests = BTreeMap::new();
    for (id, input) in artifact["inputs"].as_object().unwrap() {
        assert_eq!(id, input["input_id"].as_str().unwrap());
        let source = snapshot::replay(input);
        recovery_digests.insert(id.clone(), recovery_digest(&source));
        assert!(digests
            .insert(id.clone(), json!({"core":snapshot::digest(&source),"profiles":profiles(&source)}))
            .is_none());
    }
    let result = json!({"schema":1,"kind":"emitter-recovery-parse-replay",
        "input_artifact_sha256":snapshot::sha256(bytes),"digest_code_sha256":digest_hash,
        "digests":digests, "recovery_facts_format":"rust-debug-ParseRecovery-v1",
        "recovery_facts_sha256":recovery_digests});
    serde_json::to_writer(std::io::stdout().lock(), &result).unwrap();
    std::io::stdout().write_all(b"\n").unwrap();
}

// This independent digest includes committed events, suppressed reports and
// skip/reparse actions. It leaves the census's parse-graph digest unchanged.
#[cfg(feature = "current-recovery-profiles")]
fn recovery_digest(source: &tsc_syntax::SourceFile) -> Value {
    json!(snapshot::sha256(format!("{:?}", source.parse_recovery())))
}

#[cfg(not(feature = "current-recovery-profiles"))]
fn recovery_digest(_source: &tsc_syntax::SourceFile) -> Value { Value::Null }

#[cfg(feature = "current-recovery-profiles")]
fn profiles(source: &tsc_syntax::SourceFile) -> Value {
    json!({"literal":source.has_only_literal_recovery(),
        "missing_await":source.has_only_literal_or_missing_await_recovery(),
        "missing_declaration":source.has_only_missing_node_emit_recovery(),
        "parameter_gaps":source.has_only_parameter_gap_emit_recovery(),
        "statement_gaps":source.has_only_statement_gap_emit_recovery(),
        "context_recovery":source.has_supported_emit_recovery()})
}

#[cfg(not(feature = "current-recovery-profiles"))]
fn profiles(_source: &tsc_syntax::SourceFile) -> Value { Value::Null }

#[cfg(test)]
mod tests {
    #[test]
    fn original_census_input_identity_survives_standalone_build() {
        // Verbatim first input from the completed r78 snapshot (SHA256
        // 1846fce26da956f515874486d43b9ac856fda31456e76a2925455a8488f76d75).
        // A round trip generated by this binary alone would miss a differing
        // serde_json map representation, which changes input and graph hashes.
        let input = serde_json::from_str(r#"{
            "input_id":"0000b94d3e3d22ccf57b0164a10a575183f316f79f9f0f039e0260941a85dfda",
            "file_name":"/.src/1.ts",
            "text_utf8_base64":"ZXhwb3J0ICogYXMgbnMgZnJvbSAnLi8wJzsKbnMuYTsKbnMuYjsKbGV0IG5zID0ge2E6IDEsIGI6IDJ9Cm5zLmE7Cm5zLmI7Cg==",
            "text_sha256":"47c399190d545283d78fdf230adca597e6ac9797ade5fbc9bf3c65b5440bf73f",
            "text_utf8_bytes":73,"utf16_len":73,
            "options":{"script_target":2,"language_variant":0,"javascript_file":false,
                "js_doc_parsing_mode":0,"force_external_module":false,
                "detect_external_module_from_jsx":false,"node_id_base":0,"node_array_id_base":0}
        }"#).unwrap();
        super::snapshot::replay(&input);
    }
}
