// @generated by `cargo xtask codegen nodes`. Do not edit by hand.

use crate::SyntaxKind;

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub struct NodeId(pub u32);

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub struct NodeArrayId(pub u32);

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct NodeArray {
    pub nodes: Vec<NodeId>,
    pub pos: u32,
    pub end: u32,
    pub has_trailing_comma: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub enum NodePayload {
    Bool(bool),
    String(String),
    Number(f64),
    Kind(SyntaxKind),
}

#[derive(Clone, Debug, PartialEq)]
pub struct Node {
    pub kind: SyntaxKind,
    pub flags: i32,
    pub pos: u32,
    pub end: u32,
    pub parent: Option<NodeId>,
    pub data: NodeData,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ArrayBindingPatternData {
    pub elements: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ArrayLiteralExpressionData {
    pub elements: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ArrayTypeData {
    pub element_type: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ArrowFunctionData {
    pub modifiers: Option<NodeArrayId>,
    pub r#type: Option<NodeId>,
    pub type_parameters: Option<NodeArrayId>,
    pub parameters: Option<NodeArrayId>,
    pub equals_greater_than_token: Option<NodeId>,
    pub body: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct AsExpressionData {
    pub expression: Option<NodeId>,
    pub r#type: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct AwaitExpressionData {
    pub expression: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct BigIntLiteralData {
    pub text: String,
}

#[derive(Clone, Debug, PartialEq)]
pub struct BinaryExpressionData {
    pub left: Option<NodeId>,
    pub operator_token: Option<NodeId>,
    pub right: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct BindingElementData {
    pub dot_dot_dot_token: Option<NodeId>,
    pub property_name: Option<NodeId>,
    pub name: Option<NodeId>,
    pub initializer: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct BlockData {
    pub statements: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct BreakStatementData {
    pub label: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct CallExpressionData {
    pub expression: Option<NodeId>,
    pub question_dot_token: Option<NodeId>,
    pub type_arguments: Option<NodeArrayId>,
    pub arguments: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct CallSignatureData {
    pub r#type: Option<NodeId>,
    pub type_parameters: Option<NodeArrayId>,
    pub parameters: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct CaseBlockData {
    pub clauses: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct CaseClauseData {
    pub expression: Option<NodeId>,
    pub statements: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct CatchClauseData {
    pub variable_declaration: Option<NodeId>,
    pub block: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ClassDeclarationData {
    pub modifiers: Option<NodeArrayId>,
    pub name: Option<NodeId>,
    pub type_parameters: Option<NodeArrayId>,
    pub heritage_clauses: Option<NodeArrayId>,
    pub members: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ClassExpressionData {
    pub modifiers: Option<NodeArrayId>,
    pub name: Option<NodeId>,
    pub type_parameters: Option<NodeArrayId>,
    pub heritage_clauses: Option<NodeArrayId>,
    pub members: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ClassStaticBlockDeclarationData {
    pub modifiers: Option<NodeArrayId>,
    pub body: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct CommaListExpressionData {
    pub elements: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ComputedPropertyNameData {
    pub expression: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ConditionalExpressionData {
    pub condition: Option<NodeId>,
    pub question_token: Option<NodeId>,
    pub when_true: Option<NodeId>,
    pub colon_token: Option<NodeId>,
    pub when_false: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ConditionalTypeData {
    pub check_type: Option<NodeId>,
    pub extends_type: Option<NodeId>,
    pub true_type: Option<NodeId>,
    pub false_type: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ConstructSignatureData {
    pub r#type: Option<NodeId>,
    pub type_parameters: Option<NodeArrayId>,
    pub parameters: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ConstructorData {
    pub modifiers: Option<NodeArrayId>,
    pub name: Option<NodeId>,
    pub r#type: Option<NodeId>,
    pub type_parameters: Option<NodeArrayId>,
    pub parameters: Option<NodeArrayId>,
    pub body: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ConstructorTypeData {
    pub modifiers: Option<NodeArrayId>,
    pub r#type: Option<NodeId>,
    pub type_parameters: Option<NodeArrayId>,
    pub parameters: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ContinueStatementData {
    pub label: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct DecoratorData {
    pub expression: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct DefaultClauseData {
    pub statements: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct DeleteExpressionData {
    pub expression: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct DoStatementData {
    pub statement: Option<NodeId>,
    pub expression: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ElementAccessExpressionData {
    pub expression: Option<NodeId>,
    pub question_dot_token: Option<NodeId>,
    pub argument_expression: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct EnumDeclarationData {
    pub modifiers: Option<NodeArrayId>,
    pub name: Option<NodeId>,
    pub members: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct EnumMemberData {
    pub name: Option<NodeId>,
    pub initializer: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ExportAssignmentData {
    pub modifiers: Option<NodeArrayId>,
    pub expression: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ExportDeclarationData {
    pub modifiers: Option<NodeArrayId>,
    pub export_clause: Option<NodeId>,
    pub module_specifier: Option<NodeId>,
    pub attributes: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ExportSpecifierData {
    pub property_name: Option<NodeId>,
    pub name: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ExpressionStatementData {
    pub expression: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ExpressionWithTypeArgumentsData {
    pub expression: Option<NodeId>,
    pub type_arguments: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ExternalModuleReferenceData {
    pub expression: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ForInStatementData {
    pub initializer: Option<NodeId>,
    pub expression: Option<NodeId>,
    pub statement: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ForOfStatementData {
    pub await_modifier: Option<NodeId>,
    pub initializer: Option<NodeId>,
    pub expression: Option<NodeId>,
    pub statement: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ForStatementData {
    pub initializer: Option<NodeId>,
    pub condition: Option<NodeId>,
    pub incrementor: Option<NodeId>,
    pub statement: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct FunctionDeclarationData {
    pub modifiers: Option<NodeArrayId>,
    pub asterisk_token: Option<NodeId>,
    pub name: Option<NodeId>,
    pub r#type: Option<NodeId>,
    pub type_parameters: Option<NodeArrayId>,
    pub parameters: Option<NodeArrayId>,
    pub body: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct FunctionExpressionData {
    pub modifiers: Option<NodeArrayId>,
    pub asterisk_token: Option<NodeId>,
    pub name: Option<NodeId>,
    pub r#type: Option<NodeId>,
    pub type_parameters: Option<NodeArrayId>,
    pub parameters: Option<NodeArrayId>,
    pub body: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct FunctionTypeData {
    pub modifiers: Option<NodeArrayId>,
    pub r#type: Option<NodeId>,
    pub type_parameters: Option<NodeArrayId>,
    pub parameters: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct GetAccessorData {
    pub modifiers: Option<NodeArrayId>,
    pub name: Option<NodeId>,
    pub r#type: Option<NodeId>,
    pub type_parameters: Option<NodeArrayId>,
    pub parameters: Option<NodeArrayId>,
    pub body: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct HeritageClauseData {
    pub types: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct IdentifierData {
    pub escaped_text: String,
    pub text: String,
}

#[derive(Clone, Debug, PartialEq)]
pub struct IfStatementData {
    pub expression: Option<NodeId>,
    pub then_statement: Option<NodeId>,
    pub else_statement: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ImportAttributeData {
    pub name: Option<NodeId>,
    pub value: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ImportAttributesData {
    pub elements: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ImportClauseData {
    pub name: Option<NodeId>,
    pub named_bindings: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ImportDeclarationData {
    pub modifiers: Option<NodeArrayId>,
    pub import_clause: Option<NodeId>,
    pub module_specifier: Option<NodeId>,
    pub attributes: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ImportEqualsDeclarationData {
    pub modifiers: Option<NodeArrayId>,
    pub name: Option<NodeId>,
    pub module_reference: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ImportSpecifierData {
    pub property_name: Option<NodeId>,
    pub name: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ImportTypeData {
    pub argument: Option<NodeId>,
    pub attributes: Option<NodeId>,
    pub qualifier: Option<NodeId>,
    pub type_arguments: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ImportTypeAssertionContainerData {
    pub assert_clause: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct IndexSignatureData {
    pub modifiers: Option<NodeArrayId>,
    pub r#type: Option<NodeId>,
    pub type_parameters: Option<NodeArrayId>,
    pub parameters: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct IndexedAccessTypeData {
    pub object_type: Option<NodeId>,
    pub index_type: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct InferTypeData {
    pub type_parameter: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct InterfaceDeclarationData {
    pub modifiers: Option<NodeArrayId>,
    pub name: Option<NodeId>,
    pub type_parameters: Option<NodeArrayId>,
    pub heritage_clauses: Option<NodeArrayId>,
    pub members: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct IntersectionTypeData {
    pub types: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocData {
    pub comment: Option<NodeArrayId>,
    pub tags: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocAugmentsTagData {
    pub tag_name: Option<NodeId>,
    pub class: Option<NodeId>,
    pub comment: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocAuthorTagData {
    pub tag_name: Option<NodeId>,
    pub comment: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocCallbackTagData {
    pub tag_name: Option<NodeId>,
    pub full_name: Option<NodeId>,
    pub type_expression: Option<NodeId>,
    pub comment: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocClassTagData {
    pub tag_name: Option<NodeId>,
    pub comment: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocDeprecatedTagData {
    pub readonly_pos: f64,
    pub readonly_end: f64,
    pub readonly_kind: SyntaxKind,
    pub readonly_flags: NodeId,
    pub readonly_parent: NodeId,
    pub readonly_tag_name: NodeId,
    pub readonly_comment: Option<NodeArrayId>,
    pub tag_name: Option<NodeId>,
    pub comment: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocEnumTagData {
    pub tag_name: Option<NodeId>,
    pub type_expression: Option<NodeId>,
    pub comment: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocFunctionTypeData {
    pub parameters: Option<NodeArrayId>,
    pub r#type: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocImplementsTagData {
    pub tag_name: Option<NodeId>,
    pub class: Option<NodeId>,
    pub comment: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocImportTagData {
    pub tag_name: Option<NodeId>,
    pub import_clause: Option<NodeId>,
    pub module_specifier: Option<NodeId>,
    pub attributes: Option<NodeId>,
    pub comment: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocLinkData {
    pub name: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocLinkCodeData {
    pub name: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocLinkPlainData {
    pub name: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocMemberNameData {
    pub left: Option<NodeId>,
    pub right: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocNameReferenceData {
    pub name: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocNonNullableTypeData {
    pub r#type: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocNullableTypeData {
    pub r#type: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocOptionalTypeData {
    pub r#type: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocOverloadTagData {
    pub tag_name: Option<NodeId>,
    pub type_expression: Option<NodeId>,
    pub comment: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocOverrideTagData {
    pub tag_name: Option<NodeId>,
    pub comment: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocParameterTagData {
    pub tag_name: Option<NodeId>,
    pub name: Option<NodeId>,
    pub type_expression: Option<NodeId>,
    pub comment: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocPrivateTagData {
    pub tag_name: Option<NodeId>,
    pub comment: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocPropertyTagData {
    pub tag_name: Option<NodeId>,
    pub name: Option<NodeId>,
    pub type_expression: Option<NodeId>,
    pub comment: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocProtectedTagData {
    pub tag_name: Option<NodeId>,
    pub comment: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocPublicTagData {
    pub tag_name: Option<NodeId>,
    pub comment: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocReadonlyTagData {
    pub tag_name: Option<NodeId>,
    pub comment: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocReturnTagData {
    pub tag_name: Option<NodeId>,
    pub type_expression: Option<NodeId>,
    pub comment: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocSatisfiesTagData {
    pub tag_name: Option<NodeId>,
    pub type_expression: Option<NodeId>,
    pub comment: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocSeeTagData {
    pub tag_name: Option<NodeId>,
    pub name: Option<NodeId>,
    pub comment: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocSignatureData {
    pub r#type: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocTagData {
    pub tag_name: Option<NodeId>,
    pub comment: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocTemplateTagData {
    pub tag_name: Option<NodeId>,
    pub constraint: Option<NodeId>,
    pub type_parameters: Option<NodeArrayId>,
    pub comment: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocThisTagData {
    pub tag_name: Option<NodeId>,
    pub type_expression: Option<NodeId>,
    pub comment: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocThrowsTagData {
    pub tag_name: Option<NodeId>,
    pub type_expression: Option<NodeId>,
    pub comment: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocTypeExpressionData {
    pub r#type: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocTypeLiteralData {}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocTypeTagData {
    pub tag_name: Option<NodeId>,
    pub type_expression: Option<NodeId>,
    pub comment: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocTypedefTagData {
    pub tag_name: Option<NodeId>,
    pub type_expression: Option<NodeId>,
    pub full_name: Option<NodeId>,
    pub comment: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JSDocVariadicTypeData {
    pub r#type: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JsxAttributeData {
    pub name: Option<NodeId>,
    pub initializer: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JsxAttributesData {
    pub properties: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JsxClosingElementData {
    pub tag_name: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JsxElementData {
    pub opening_element: Option<NodeId>,
    pub children: Option<NodeArrayId>,
    pub closing_element: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JsxExpressionData {
    pub dot_dot_dot_token: Option<NodeId>,
    pub expression: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JsxFragmentData {
    pub opening_fragment: Option<NodeId>,
    pub children: Option<NodeArrayId>,
    pub closing_fragment: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JsxNamespacedNameData {
    pub namespace: Option<NodeId>,
    pub name: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JsxOpeningElementData {
    pub tag_name: Option<NodeId>,
    pub type_arguments: Option<NodeArrayId>,
    pub attributes: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JsxSelfClosingElementData {
    pub tag_name: Option<NodeId>,
    pub type_arguments: Option<NodeArrayId>,
    pub attributes: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JsxSpreadAttributeData {
    pub expression: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JsxTextData {
    pub text: String,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LabeledStatementData {
    pub label: Option<NodeId>,
    pub statement: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LiteralTypeData {
    pub literal: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct MappedTypeData {
    pub readonly_token: Option<NodeId>,
    pub type_parameter: Option<NodeId>,
    pub r#type: Option<NodeId>,
    pub name_type: Option<NodeId>,
    pub question_token: Option<NodeId>,
    pub members: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct MetaPropertyData {
    pub name: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct MethodDeclarationData {
    pub modifiers: Option<NodeArrayId>,
    pub asterisk_token: Option<NodeId>,
    pub name: Option<NodeId>,
    pub question_token: Option<NodeId>,
    pub exclamation_token: Option<NodeId>,
    pub r#type: Option<NodeId>,
    pub type_parameters: Option<NodeArrayId>,
    pub parameters: Option<NodeArrayId>,
    pub body: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct MethodSignatureData {
    pub modifiers: Option<NodeArrayId>,
    pub name: Option<NodeId>,
    pub question_token: Option<NodeId>,
    pub r#type: Option<NodeId>,
    pub type_parameters: Option<NodeArrayId>,
    pub parameters: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct MissingDeclarationData {
    pub modifiers: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ModuleBlockData {
    pub statements: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ModuleDeclarationData {
    pub modifiers: Option<NodeArrayId>,
    pub name: Option<NodeId>,
    pub body: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct NamedExportsData {
    pub elements: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct NamedImportsData {
    pub elements: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct NamedTupleMemberData {
    pub dot_dot_dot_token: Option<NodeId>,
    pub name: Option<NodeId>,
    pub question_token: Option<NodeId>,
    pub r#type: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct NamespaceExportData {
    pub name: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct NamespaceExportDeclarationData {
    pub modifiers: Option<NodeArrayId>,
    pub name: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct NamespaceImportData {
    pub name: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct NewExpressionData {
    pub expression: Option<NodeId>,
    pub question_dot_token: Option<NodeId>,
    pub type_arguments: Option<NodeArrayId>,
    pub arguments: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct NoSubstitutionTemplateLiteralData {
    pub text: String,
}

#[derive(Clone, Debug, PartialEq)]
pub struct NonNullExpressionData {
    pub expression: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct NumericLiteralData {
    pub text: String,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ObjectBindingPatternData {
    pub elements: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ObjectLiteralExpressionData {
    pub properties: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct OptionalTypeData {
    pub r#type: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ParameterData {
    pub modifiers: Option<NodeArrayId>,
    pub dot_dot_dot_token: Option<NodeId>,
    pub name: Option<NodeId>,
    pub question_token: Option<NodeId>,
    pub r#type: Option<NodeId>,
    pub initializer: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ParenthesizedExpressionData {
    pub expression: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ParenthesizedTypeData {
    pub r#type: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct PartiallyEmittedExpressionData {
    pub expression: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct PostfixUnaryExpressionData {
    pub operand: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct PrefixUnaryExpressionData {
    pub operand: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct PrivateIdentifierData {
    pub escaped_text: String,
    pub text: String,
}

#[derive(Clone, Debug, PartialEq)]
pub struct PropertyAccessExpressionData {
    pub expression: Option<NodeId>,
    pub question_dot_token: Option<NodeId>,
    pub name: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct PropertyAssignmentData {
    pub modifiers: Option<NodeArrayId>,
    pub name: Option<NodeId>,
    pub question_token: Option<NodeId>,
    pub exclamation_token: Option<NodeId>,
    pub initializer: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct PropertyDeclarationData {
    pub modifiers: Option<NodeArrayId>,
    pub name: Option<NodeId>,
    pub question_token: Option<NodeId>,
    pub exclamation_token: Option<NodeId>,
    pub r#type: Option<NodeId>,
    pub initializer: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct PropertySignatureData {
    pub modifiers: Option<NodeArrayId>,
    pub name: Option<NodeId>,
    pub question_token: Option<NodeId>,
    pub r#type: Option<NodeId>,
    pub initializer: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct QualifiedNameData {
    pub left: Option<NodeId>,
    pub right: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct RegularExpressionLiteralData {
    pub text: String,
}

#[derive(Clone, Debug, PartialEq)]
pub struct RestTypeData {
    pub r#type: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ReturnStatementData {
    pub expression: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct SatisfiesExpressionData {
    pub expression: Option<NodeId>,
    pub r#type: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct SetAccessorData {
    pub modifiers: Option<NodeArrayId>,
    pub name: Option<NodeId>,
    pub r#type: Option<NodeId>,
    pub type_parameters: Option<NodeArrayId>,
    pub parameters: Option<NodeArrayId>,
    pub body: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShorthandPropertyAssignmentData {
    pub modifiers: Option<NodeArrayId>,
    pub name: Option<NodeId>,
    pub question_token: Option<NodeId>,
    pub exclamation_token: Option<NodeId>,
    pub equals_token: Option<NodeId>,
    pub object_assignment_initializer: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct SourceFileData {
    pub statements: Option<NodeArrayId>,
    pub end_of_file_token: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct SpreadAssignmentData {
    pub expression: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct SpreadElementData {
    pub expression: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct StringLiteralData {
    pub text: String,
}

#[derive(Clone, Debug, PartialEq)]
pub struct SwitchStatementData {
    pub expression: Option<NodeId>,
    pub case_block: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct SyntaxListData {
    pub readonly_pos: f64,
    pub readonly_end: f64,
    pub readonly_kind: SyntaxKind,
    pub readonly_flags: NodeId,
    pub readonly_parent: NodeId,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TaggedTemplateExpressionData {
    pub tag: Option<NodeId>,
    pub question_dot_token: Option<NodeId>,
    pub type_arguments: Option<NodeArrayId>,
    pub template: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TemplateExpressionData {
    pub head: Option<NodeId>,
    pub template_spans: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TemplateHeadData {
    pub text: String,
    pub raw_text: Option<String>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TemplateLiteralTypeData {
    pub readonly_pos: f64,
    pub readonly_end: f64,
    pub readonly_kind: SyntaxKind,
    pub readonly_flags: NodeId,
    pub readonly_parent: NodeId,
    pub readonly_head: NodePayload,
    pub readonly_template_spans: NodeArrayId,
    pub head: Option<NodeId>,
    pub template_spans: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TemplateLiteralTypeSpanData {
    pub r#type: Option<NodeId>,
    pub literal: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TemplateMiddleData {
    pub text: String,
    pub raw_text: Option<String>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TemplateSpanData {
    pub expression: Option<NodeId>,
    pub literal: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TemplateTailData {
    pub text: String,
    pub raw_text: Option<String>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ThrowStatementData {
    pub expression: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TryStatementData {
    pub try_block: Option<NodeId>,
    pub catch_clause: Option<NodeId>,
    pub finally_block: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TupleTypeData {
    pub elements: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TypeAliasDeclarationData {
    pub modifiers: Option<NodeArrayId>,
    pub name: Option<NodeId>,
    pub r#type: Option<NodeId>,
    pub type_parameters: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TypeAssertionExpressionData {
    pub r#type: Option<NodeId>,
    pub expression: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TypeLiteralData {
    pub members: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TypeOfExpressionData {
    pub expression: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TypeOperatorData {
    pub r#type: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TypeParameterData {
    pub modifiers: Option<NodeArrayId>,
    pub name: Option<NodeId>,
    pub constraint: Option<NodeId>,
    pub r#default: Option<NodeId>,
    pub expression: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TypePredicateData {
    pub asserts_modifier: Option<NodeId>,
    pub parameter_name: Option<NodeId>,
    pub r#type: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TypeQueryData {
    pub expr_name: Option<NodeId>,
    pub type_arguments: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TypeReferenceData {
    pub type_name: Option<NodeId>,
    pub type_arguments: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnionTypeData {
    pub types: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct VariableDeclarationData {
    pub name: Option<NodeId>,
    pub exclamation_token: Option<NodeId>,
    pub r#type: Option<NodeId>,
    pub initializer: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct VariableDeclarationListData {
    pub declarations: Option<NodeArrayId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct VariableStatementData {
    pub modifiers: Option<NodeArrayId>,
    pub declaration_list: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct VoidExpressionData {
    pub expression: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct WhileStatementData {
    pub expression: Option<NodeId>,
    pub statement: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct WithStatementData {
    pub expression: Option<NodeId>,
    pub statement: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct YieldExpressionData {
    pub asterisk_token: Option<NodeId>,
    pub expression: Option<NodeId>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum NodeData {
    Token,
    ArrayBindingPattern(ArrayBindingPatternData),
    ArrayLiteralExpression(ArrayLiteralExpressionData),
    ArrayType(ArrayTypeData),
    ArrowFunction(ArrowFunctionData),
    AsExpression(AsExpressionData),
    AwaitExpression(AwaitExpressionData),
    BigIntLiteral(BigIntLiteralData),
    BinaryExpression(BinaryExpressionData),
    BindingElement(BindingElementData),
    Block(BlockData),
    BreakStatement(BreakStatementData),
    CallExpression(CallExpressionData),
    CallSignature(CallSignatureData),
    CaseBlock(CaseBlockData),
    CaseClause(CaseClauseData),
    CatchClause(CatchClauseData),
    ClassDeclaration(ClassDeclarationData),
    ClassExpression(ClassExpressionData),
    ClassStaticBlockDeclaration(ClassStaticBlockDeclarationData),
    CommaListExpression(CommaListExpressionData),
    ComputedPropertyName(ComputedPropertyNameData),
    ConditionalExpression(ConditionalExpressionData),
    ConditionalType(ConditionalTypeData),
    ConstructSignature(ConstructSignatureData),
    Constructor(ConstructorData),
    ConstructorType(ConstructorTypeData),
    ContinueStatement(ContinueStatementData),
    Decorator(DecoratorData),
    DefaultClause(DefaultClauseData),
    DeleteExpression(DeleteExpressionData),
    DoStatement(DoStatementData),
    ElementAccessExpression(ElementAccessExpressionData),
    EnumDeclaration(EnumDeclarationData),
    EnumMember(EnumMemberData),
    ExportAssignment(ExportAssignmentData),
    ExportDeclaration(ExportDeclarationData),
    ExportSpecifier(ExportSpecifierData),
    ExpressionStatement(ExpressionStatementData),
    ExpressionWithTypeArguments(ExpressionWithTypeArgumentsData),
    ExternalModuleReference(ExternalModuleReferenceData),
    ForInStatement(ForInStatementData),
    ForOfStatement(ForOfStatementData),
    ForStatement(ForStatementData),
    FunctionDeclaration(FunctionDeclarationData),
    FunctionExpression(FunctionExpressionData),
    FunctionType(FunctionTypeData),
    GetAccessor(GetAccessorData),
    HeritageClause(HeritageClauseData),
    Identifier(IdentifierData),
    IfStatement(IfStatementData),
    ImportAttribute(ImportAttributeData),
    ImportAttributes(ImportAttributesData),
    ImportClause(ImportClauseData),
    ImportDeclaration(ImportDeclarationData),
    ImportEqualsDeclaration(ImportEqualsDeclarationData),
    ImportSpecifier(ImportSpecifierData),
    ImportType(ImportTypeData),
    ImportTypeAssertionContainer(ImportTypeAssertionContainerData),
    IndexSignature(IndexSignatureData),
    IndexedAccessType(IndexedAccessTypeData),
    InferType(InferTypeData),
    InterfaceDeclaration(InterfaceDeclarationData),
    IntersectionType(IntersectionTypeData),
    JSDoc(JSDocData),
    JSDocAugmentsTag(JSDocAugmentsTagData),
    JSDocAuthorTag(JSDocAuthorTagData),
    JSDocCallbackTag(JSDocCallbackTagData),
    JSDocClassTag(JSDocClassTagData),
    JSDocDeprecatedTag(JSDocDeprecatedTagData),
    JSDocEnumTag(JSDocEnumTagData),
    JSDocFunctionType(JSDocFunctionTypeData),
    JSDocImplementsTag(JSDocImplementsTagData),
    JSDocImportTag(JSDocImportTagData),
    JSDocLink(JSDocLinkData),
    JSDocLinkCode(JSDocLinkCodeData),
    JSDocLinkPlain(JSDocLinkPlainData),
    JSDocMemberName(JSDocMemberNameData),
    JSDocNameReference(JSDocNameReferenceData),
    JSDocNonNullableType(JSDocNonNullableTypeData),
    JSDocNullableType(JSDocNullableTypeData),
    JSDocOptionalType(JSDocOptionalTypeData),
    JSDocOverloadTag(JSDocOverloadTagData),
    JSDocOverrideTag(JSDocOverrideTagData),
    JSDocParameterTag(JSDocParameterTagData),
    JSDocPrivateTag(JSDocPrivateTagData),
    JSDocPropertyTag(JSDocPropertyTagData),
    JSDocProtectedTag(JSDocProtectedTagData),
    JSDocPublicTag(JSDocPublicTagData),
    JSDocReadonlyTag(JSDocReadonlyTagData),
    JSDocReturnTag(JSDocReturnTagData),
    JSDocSatisfiesTag(JSDocSatisfiesTagData),
    JSDocSeeTag(JSDocSeeTagData),
    JSDocSignature(JSDocSignatureData),
    JSDocTag(JSDocTagData),
    JSDocTemplateTag(JSDocTemplateTagData),
    JSDocThisTag(JSDocThisTagData),
    JSDocThrowsTag(JSDocThrowsTagData),
    JSDocTypeExpression(JSDocTypeExpressionData),
    JSDocTypeLiteral(JSDocTypeLiteralData),
    JSDocTypeTag(JSDocTypeTagData),
    JSDocTypedefTag(JSDocTypedefTagData),
    JSDocVariadicType(JSDocVariadicTypeData),
    JsxAttribute(JsxAttributeData),
    JsxAttributes(JsxAttributesData),
    JsxClosingElement(JsxClosingElementData),
    JsxElement(JsxElementData),
    JsxExpression(JsxExpressionData),
    JsxFragment(JsxFragmentData),
    JsxNamespacedName(JsxNamespacedNameData),
    JsxOpeningElement(JsxOpeningElementData),
    JsxSelfClosingElement(JsxSelfClosingElementData),
    JsxSpreadAttribute(JsxSpreadAttributeData),
    JsxText(JsxTextData),
    LabeledStatement(LabeledStatementData),
    LiteralType(LiteralTypeData),
    MappedType(MappedTypeData),
    MetaProperty(MetaPropertyData),
    MethodDeclaration(MethodDeclarationData),
    MethodSignature(MethodSignatureData),
    MissingDeclaration(MissingDeclarationData),
    ModuleBlock(ModuleBlockData),
    ModuleDeclaration(ModuleDeclarationData),
    NamedExports(NamedExportsData),
    NamedImports(NamedImportsData),
    NamedTupleMember(NamedTupleMemberData),
    NamespaceExport(NamespaceExportData),
    NamespaceExportDeclaration(NamespaceExportDeclarationData),
    NamespaceImport(NamespaceImportData),
    NewExpression(NewExpressionData),
    NoSubstitutionTemplateLiteral(NoSubstitutionTemplateLiteralData),
    NonNullExpression(NonNullExpressionData),
    NumericLiteral(NumericLiteralData),
    ObjectBindingPattern(ObjectBindingPatternData),
    ObjectLiteralExpression(ObjectLiteralExpressionData),
    OptionalType(OptionalTypeData),
    Parameter(ParameterData),
    ParenthesizedExpression(ParenthesizedExpressionData),
    ParenthesizedType(ParenthesizedTypeData),
    PartiallyEmittedExpression(PartiallyEmittedExpressionData),
    PostfixUnaryExpression(PostfixUnaryExpressionData),
    PrefixUnaryExpression(PrefixUnaryExpressionData),
    PrivateIdentifier(PrivateIdentifierData),
    PropertyAccessExpression(PropertyAccessExpressionData),
    PropertyAssignment(PropertyAssignmentData),
    PropertyDeclaration(PropertyDeclarationData),
    PropertySignature(PropertySignatureData),
    QualifiedName(QualifiedNameData),
    RegularExpressionLiteral(RegularExpressionLiteralData),
    RestType(RestTypeData),
    ReturnStatement(ReturnStatementData),
    SatisfiesExpression(SatisfiesExpressionData),
    SetAccessor(SetAccessorData),
    ShorthandPropertyAssignment(ShorthandPropertyAssignmentData),
    SourceFile(SourceFileData),
    SpreadAssignment(SpreadAssignmentData),
    SpreadElement(SpreadElementData),
    StringLiteral(StringLiteralData),
    SwitchStatement(SwitchStatementData),
    SyntaxList(SyntaxListData),
    TaggedTemplateExpression(TaggedTemplateExpressionData),
    TemplateExpression(TemplateExpressionData),
    TemplateHead(TemplateHeadData),
    TemplateLiteralType(TemplateLiteralTypeData),
    TemplateLiteralTypeSpan(TemplateLiteralTypeSpanData),
    TemplateMiddle(TemplateMiddleData),
    TemplateSpan(TemplateSpanData),
    TemplateTail(TemplateTailData),
    ThrowStatement(ThrowStatementData),
    TryStatement(TryStatementData),
    TupleType(TupleTypeData),
    TypeAliasDeclaration(TypeAliasDeclarationData),
    TypeAssertionExpression(TypeAssertionExpressionData),
    TypeLiteral(TypeLiteralData),
    TypeOfExpression(TypeOfExpressionData),
    TypeOperator(TypeOperatorData),
    TypeParameter(TypeParameterData),
    TypePredicate(TypePredicateData),
    TypeQuery(TypeQueryData),
    TypeReference(TypeReferenceData),
    UnionType(UnionTypeData),
    VariableDeclaration(VariableDeclarationData),
    VariableDeclarationList(VariableDeclarationListData),
    VariableStatement(VariableStatementData),
    VoidExpression(VoidExpressionData),
    WhileStatement(WhileStatementData),
    WithStatement(WithStatementData),
    YieldExpression(YieldExpressionData),
}

impl NodeData {
    pub const fn kind(&self) -> Option<SyntaxKind> {
        match self {
            Self::Token => None,
            Self::ArrayBindingPattern(_) => Some(SyntaxKind::ArrayBindingPattern),
            Self::ArrayLiteralExpression(_) => Some(SyntaxKind::ArrayLiteralExpression),
            Self::ArrayType(_) => Some(SyntaxKind::ArrayType),
            Self::ArrowFunction(_) => Some(SyntaxKind::ArrowFunction),
            Self::AsExpression(_) => Some(SyntaxKind::AsExpression),
            Self::AwaitExpression(_) => Some(SyntaxKind::AwaitExpression),
            Self::BigIntLiteral(_) => Some(SyntaxKind::BigIntLiteral),
            Self::BinaryExpression(_) => Some(SyntaxKind::BinaryExpression),
            Self::BindingElement(_) => Some(SyntaxKind::BindingElement),
            Self::Block(_) => Some(SyntaxKind::Block),
            Self::BreakStatement(_) => Some(SyntaxKind::BreakStatement),
            Self::CallExpression(_) => Some(SyntaxKind::CallExpression),
            Self::CallSignature(_) => Some(SyntaxKind::CallSignature),
            Self::CaseBlock(_) => Some(SyntaxKind::CaseBlock),
            Self::CaseClause(_) => Some(SyntaxKind::CaseClause),
            Self::CatchClause(_) => Some(SyntaxKind::CatchClause),
            Self::ClassDeclaration(_) => Some(SyntaxKind::ClassDeclaration),
            Self::ClassExpression(_) => Some(SyntaxKind::ClassExpression),
            Self::ClassStaticBlockDeclaration(_) => Some(SyntaxKind::ClassStaticBlockDeclaration),
            Self::CommaListExpression(_) => Some(SyntaxKind::CommaListExpression),
            Self::ComputedPropertyName(_) => Some(SyntaxKind::ComputedPropertyName),
            Self::ConditionalExpression(_) => Some(SyntaxKind::ConditionalExpression),
            Self::ConditionalType(_) => Some(SyntaxKind::ConditionalType),
            Self::ConstructSignature(_) => Some(SyntaxKind::ConstructSignature),
            Self::Constructor(_) => Some(SyntaxKind::Constructor),
            Self::ConstructorType(_) => Some(SyntaxKind::ConstructorType),
            Self::ContinueStatement(_) => Some(SyntaxKind::ContinueStatement),
            Self::Decorator(_) => Some(SyntaxKind::Decorator),
            Self::DefaultClause(_) => Some(SyntaxKind::DefaultClause),
            Self::DeleteExpression(_) => Some(SyntaxKind::DeleteExpression),
            Self::DoStatement(_) => Some(SyntaxKind::DoStatement),
            Self::ElementAccessExpression(_) => Some(SyntaxKind::ElementAccessExpression),
            Self::EnumDeclaration(_) => Some(SyntaxKind::EnumDeclaration),
            Self::EnumMember(_) => Some(SyntaxKind::EnumMember),
            Self::ExportAssignment(_) => Some(SyntaxKind::ExportAssignment),
            Self::ExportDeclaration(_) => Some(SyntaxKind::ExportDeclaration),
            Self::ExportSpecifier(_) => Some(SyntaxKind::ExportSpecifier),
            Self::ExpressionStatement(_) => Some(SyntaxKind::ExpressionStatement),
            Self::ExpressionWithTypeArguments(_) => Some(SyntaxKind::ExpressionWithTypeArguments),
            Self::ExternalModuleReference(_) => Some(SyntaxKind::ExternalModuleReference),
            Self::ForInStatement(_) => Some(SyntaxKind::ForInStatement),
            Self::ForOfStatement(_) => Some(SyntaxKind::ForOfStatement),
            Self::ForStatement(_) => Some(SyntaxKind::ForStatement),
            Self::FunctionDeclaration(_) => Some(SyntaxKind::FunctionDeclaration),
            Self::FunctionExpression(_) => Some(SyntaxKind::FunctionExpression),
            Self::FunctionType(_) => Some(SyntaxKind::FunctionType),
            Self::GetAccessor(_) => Some(SyntaxKind::GetAccessor),
            Self::HeritageClause(_) => Some(SyntaxKind::HeritageClause),
            Self::Identifier(_) => Some(SyntaxKind::Identifier),
            Self::IfStatement(_) => Some(SyntaxKind::IfStatement),
            Self::ImportAttribute(_) => Some(SyntaxKind::ImportAttribute),
            Self::ImportAttributes(_) => Some(SyntaxKind::ImportAttributes),
            Self::ImportClause(_) => Some(SyntaxKind::ImportClause),
            Self::ImportDeclaration(_) => Some(SyntaxKind::ImportDeclaration),
            Self::ImportEqualsDeclaration(_) => Some(SyntaxKind::ImportEqualsDeclaration),
            Self::ImportSpecifier(_) => Some(SyntaxKind::ImportSpecifier),
            Self::ImportType(_) => Some(SyntaxKind::ImportType),
            Self::ImportTypeAssertionContainer(_) => Some(SyntaxKind::ImportTypeAssertionContainer),
            Self::IndexSignature(_) => Some(SyntaxKind::IndexSignature),
            Self::IndexedAccessType(_) => Some(SyntaxKind::IndexedAccessType),
            Self::InferType(_) => Some(SyntaxKind::InferType),
            Self::InterfaceDeclaration(_) => Some(SyntaxKind::InterfaceDeclaration),
            Self::IntersectionType(_) => Some(SyntaxKind::IntersectionType),
            Self::JSDoc(_) => Some(SyntaxKind::JSDoc),
            Self::JSDocAugmentsTag(_) => Some(SyntaxKind::JSDocAugmentsTag),
            Self::JSDocAuthorTag(_) => Some(SyntaxKind::JSDocAuthorTag),
            Self::JSDocCallbackTag(_) => Some(SyntaxKind::JSDocCallbackTag),
            Self::JSDocClassTag(_) => Some(SyntaxKind::JSDocClassTag),
            Self::JSDocDeprecatedTag(_) => Some(SyntaxKind::JSDocDeprecatedTag),
            Self::JSDocEnumTag(_) => Some(SyntaxKind::JSDocEnumTag),
            Self::JSDocFunctionType(_) => Some(SyntaxKind::JSDocFunctionType),
            Self::JSDocImplementsTag(_) => Some(SyntaxKind::JSDocImplementsTag),
            Self::JSDocImportTag(_) => Some(SyntaxKind::JSDocImportTag),
            Self::JSDocLink(_) => Some(SyntaxKind::JSDocLink),
            Self::JSDocLinkCode(_) => Some(SyntaxKind::JSDocLinkCode),
            Self::JSDocLinkPlain(_) => Some(SyntaxKind::JSDocLinkPlain),
            Self::JSDocMemberName(_) => Some(SyntaxKind::JSDocMemberName),
            Self::JSDocNameReference(_) => Some(SyntaxKind::JSDocNameReference),
            Self::JSDocNonNullableType(_) => Some(SyntaxKind::JSDocNonNullableType),
            Self::JSDocNullableType(_) => Some(SyntaxKind::JSDocNullableType),
            Self::JSDocOptionalType(_) => Some(SyntaxKind::JSDocOptionalType),
            Self::JSDocOverloadTag(_) => Some(SyntaxKind::JSDocOverloadTag),
            Self::JSDocOverrideTag(_) => Some(SyntaxKind::JSDocOverrideTag),
            Self::JSDocParameterTag(_) => Some(SyntaxKind::JSDocParameterTag),
            Self::JSDocPrivateTag(_) => Some(SyntaxKind::JSDocPrivateTag),
            Self::JSDocPropertyTag(_) => Some(SyntaxKind::JSDocPropertyTag),
            Self::JSDocProtectedTag(_) => Some(SyntaxKind::JSDocProtectedTag),
            Self::JSDocPublicTag(_) => Some(SyntaxKind::JSDocPublicTag),
            Self::JSDocReadonlyTag(_) => Some(SyntaxKind::JSDocReadonlyTag),
            Self::JSDocReturnTag(_) => Some(SyntaxKind::JSDocReturnTag),
            Self::JSDocSatisfiesTag(_) => Some(SyntaxKind::JSDocSatisfiesTag),
            Self::JSDocSeeTag(_) => Some(SyntaxKind::JSDocSeeTag),
            Self::JSDocSignature(_) => Some(SyntaxKind::JSDocSignature),
            Self::JSDocTag(_) => Some(SyntaxKind::JSDocTag),
            Self::JSDocTemplateTag(_) => Some(SyntaxKind::JSDocTemplateTag),
            Self::JSDocThisTag(_) => Some(SyntaxKind::JSDocThisTag),
            Self::JSDocThrowsTag(_) => Some(SyntaxKind::JSDocThrowsTag),
            Self::JSDocTypeExpression(_) => Some(SyntaxKind::JSDocTypeExpression),
            Self::JSDocTypeLiteral(_) => Some(SyntaxKind::JSDocTypeLiteral),
            Self::JSDocTypeTag(_) => Some(SyntaxKind::JSDocTypeTag),
            Self::JSDocTypedefTag(_) => Some(SyntaxKind::JSDocTypedefTag),
            Self::JSDocVariadicType(_) => Some(SyntaxKind::JSDocVariadicType),
            Self::JsxAttribute(_) => Some(SyntaxKind::JsxAttribute),
            Self::JsxAttributes(_) => Some(SyntaxKind::JsxAttributes),
            Self::JsxClosingElement(_) => Some(SyntaxKind::JsxClosingElement),
            Self::JsxElement(_) => Some(SyntaxKind::JsxElement),
            Self::JsxExpression(_) => Some(SyntaxKind::JsxExpression),
            Self::JsxFragment(_) => Some(SyntaxKind::JsxFragment),
            Self::JsxNamespacedName(_) => Some(SyntaxKind::JsxNamespacedName),
            Self::JsxOpeningElement(_) => Some(SyntaxKind::JsxOpeningElement),
            Self::JsxSelfClosingElement(_) => Some(SyntaxKind::JsxSelfClosingElement),
            Self::JsxSpreadAttribute(_) => Some(SyntaxKind::JsxSpreadAttribute),
            Self::JsxText(_) => Some(SyntaxKind::JsxText),
            Self::LabeledStatement(_) => Some(SyntaxKind::LabeledStatement),
            Self::LiteralType(_) => Some(SyntaxKind::LiteralType),
            Self::MappedType(_) => Some(SyntaxKind::MappedType),
            Self::MetaProperty(_) => Some(SyntaxKind::MetaProperty),
            Self::MethodDeclaration(_) => Some(SyntaxKind::MethodDeclaration),
            Self::MethodSignature(_) => Some(SyntaxKind::MethodSignature),
            Self::MissingDeclaration(_) => Some(SyntaxKind::MissingDeclaration),
            Self::ModuleBlock(_) => Some(SyntaxKind::ModuleBlock),
            Self::ModuleDeclaration(_) => Some(SyntaxKind::ModuleDeclaration),
            Self::NamedExports(_) => Some(SyntaxKind::NamedExports),
            Self::NamedImports(_) => Some(SyntaxKind::NamedImports),
            Self::NamedTupleMember(_) => Some(SyntaxKind::NamedTupleMember),
            Self::NamespaceExport(_) => Some(SyntaxKind::NamespaceExport),
            Self::NamespaceExportDeclaration(_) => Some(SyntaxKind::NamespaceExportDeclaration),
            Self::NamespaceImport(_) => Some(SyntaxKind::NamespaceImport),
            Self::NewExpression(_) => Some(SyntaxKind::NewExpression),
            Self::NoSubstitutionTemplateLiteral(_) => {
                Some(SyntaxKind::NoSubstitutionTemplateLiteral)
            }
            Self::NonNullExpression(_) => Some(SyntaxKind::NonNullExpression),
            Self::NumericLiteral(_) => Some(SyntaxKind::NumericLiteral),
            Self::ObjectBindingPattern(_) => Some(SyntaxKind::ObjectBindingPattern),
            Self::ObjectLiteralExpression(_) => Some(SyntaxKind::ObjectLiteralExpression),
            Self::OptionalType(_) => Some(SyntaxKind::OptionalType),
            Self::Parameter(_) => Some(SyntaxKind::Parameter),
            Self::ParenthesizedExpression(_) => Some(SyntaxKind::ParenthesizedExpression),
            Self::ParenthesizedType(_) => Some(SyntaxKind::ParenthesizedType),
            Self::PartiallyEmittedExpression(_) => Some(SyntaxKind::PartiallyEmittedExpression),
            Self::PostfixUnaryExpression(_) => Some(SyntaxKind::PostfixUnaryExpression),
            Self::PrefixUnaryExpression(_) => Some(SyntaxKind::PrefixUnaryExpression),
            Self::PrivateIdentifier(_) => Some(SyntaxKind::PrivateIdentifier),
            Self::PropertyAccessExpression(_) => Some(SyntaxKind::PropertyAccessExpression),
            Self::PropertyAssignment(_) => Some(SyntaxKind::PropertyAssignment),
            Self::PropertyDeclaration(_) => Some(SyntaxKind::PropertyDeclaration),
            Self::PropertySignature(_) => Some(SyntaxKind::PropertySignature),
            Self::QualifiedName(_) => Some(SyntaxKind::QualifiedName),
            Self::RegularExpressionLiteral(_) => Some(SyntaxKind::RegularExpressionLiteral),
            Self::RestType(_) => Some(SyntaxKind::RestType),
            Self::ReturnStatement(_) => Some(SyntaxKind::ReturnStatement),
            Self::SatisfiesExpression(_) => Some(SyntaxKind::SatisfiesExpression),
            Self::SetAccessor(_) => Some(SyntaxKind::SetAccessor),
            Self::ShorthandPropertyAssignment(_) => Some(SyntaxKind::ShorthandPropertyAssignment),
            Self::SourceFile(_) => Some(SyntaxKind::SourceFile),
            Self::SpreadAssignment(_) => Some(SyntaxKind::SpreadAssignment),
            Self::SpreadElement(_) => Some(SyntaxKind::SpreadElement),
            Self::StringLiteral(_) => Some(SyntaxKind::StringLiteral),
            Self::SwitchStatement(_) => Some(SyntaxKind::SwitchStatement),
            Self::SyntaxList(_) => Some(SyntaxKind::SyntaxList),
            Self::TaggedTemplateExpression(_) => Some(SyntaxKind::TaggedTemplateExpression),
            Self::TemplateExpression(_) => Some(SyntaxKind::TemplateExpression),
            Self::TemplateHead(_) => Some(SyntaxKind::TemplateHead),
            Self::TemplateLiteralType(_) => Some(SyntaxKind::TemplateLiteralType),
            Self::TemplateLiteralTypeSpan(_) => Some(SyntaxKind::TemplateLiteralTypeSpan),
            Self::TemplateMiddle(_) => Some(SyntaxKind::TemplateMiddle),
            Self::TemplateSpan(_) => Some(SyntaxKind::TemplateSpan),
            Self::TemplateTail(_) => Some(SyntaxKind::TemplateTail),
            Self::ThrowStatement(_) => Some(SyntaxKind::ThrowStatement),
            Self::TryStatement(_) => Some(SyntaxKind::TryStatement),
            Self::TupleType(_) => Some(SyntaxKind::TupleType),
            Self::TypeAliasDeclaration(_) => Some(SyntaxKind::TypeAliasDeclaration),
            Self::TypeAssertionExpression(_) => Some(SyntaxKind::TypeAssertionExpression),
            Self::TypeLiteral(_) => Some(SyntaxKind::TypeLiteral),
            Self::TypeOfExpression(_) => Some(SyntaxKind::TypeOfExpression),
            Self::TypeOperator(_) => Some(SyntaxKind::TypeOperator),
            Self::TypeParameter(_) => Some(SyntaxKind::TypeParameter),
            Self::TypePredicate(_) => Some(SyntaxKind::TypePredicate),
            Self::TypeQuery(_) => Some(SyntaxKind::TypeQuery),
            Self::TypeReference(_) => Some(SyntaxKind::TypeReference),
            Self::UnionType(_) => Some(SyntaxKind::UnionType),
            Self::VariableDeclaration(_) => Some(SyntaxKind::VariableDeclaration),
            Self::VariableDeclarationList(_) => Some(SyntaxKind::VariableDeclarationList),
            Self::VariableStatement(_) => Some(SyntaxKind::VariableStatement),
            Self::VoidExpression(_) => Some(SyntaxKind::VoidExpression),
            Self::WhileStatement(_) => Some(SyntaxKind::WhileStatement),
            Self::WithStatement(_) => Some(SyntaxKind::WithStatement),
            Self::YieldExpression(_) => Some(SyntaxKind::YieldExpression),
        }
    }

    pub fn as_array_binding_pattern(&self) -> Option<&ArrayBindingPatternData> {
        match self {
            Self::ArrayBindingPattern(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_array_literal_expression(&self) -> Option<&ArrayLiteralExpressionData> {
        match self {
            Self::ArrayLiteralExpression(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_array_type(&self) -> Option<&ArrayTypeData> {
        match self {
            Self::ArrayType(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_arrow_function(&self) -> Option<&ArrowFunctionData> {
        match self {
            Self::ArrowFunction(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_as_expression(&self) -> Option<&AsExpressionData> {
        match self {
            Self::AsExpression(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_await_expression(&self) -> Option<&AwaitExpressionData> {
        match self {
            Self::AwaitExpression(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_big_int_literal(&self) -> Option<&BigIntLiteralData> {
        match self {
            Self::BigIntLiteral(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_binary_expression(&self) -> Option<&BinaryExpressionData> {
        match self {
            Self::BinaryExpression(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_binding_element(&self) -> Option<&BindingElementData> {
        match self {
            Self::BindingElement(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_block(&self) -> Option<&BlockData> {
        match self {
            Self::Block(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_break_statement(&self) -> Option<&BreakStatementData> {
        match self {
            Self::BreakStatement(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_call_expression(&self) -> Option<&CallExpressionData> {
        match self {
            Self::CallExpression(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_call_signature(&self) -> Option<&CallSignatureData> {
        match self {
            Self::CallSignature(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_case_block(&self) -> Option<&CaseBlockData> {
        match self {
            Self::CaseBlock(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_case_clause(&self) -> Option<&CaseClauseData> {
        match self {
            Self::CaseClause(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_catch_clause(&self) -> Option<&CatchClauseData> {
        match self {
            Self::CatchClause(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_class_declaration(&self) -> Option<&ClassDeclarationData> {
        match self {
            Self::ClassDeclaration(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_class_expression(&self) -> Option<&ClassExpressionData> {
        match self {
            Self::ClassExpression(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_class_static_block_declaration(&self) -> Option<&ClassStaticBlockDeclarationData> {
        match self {
            Self::ClassStaticBlockDeclaration(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_comma_list_expression(&self) -> Option<&CommaListExpressionData> {
        match self {
            Self::CommaListExpression(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_computed_property_name(&self) -> Option<&ComputedPropertyNameData> {
        match self {
            Self::ComputedPropertyName(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_conditional_expression(&self) -> Option<&ConditionalExpressionData> {
        match self {
            Self::ConditionalExpression(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_conditional_type(&self) -> Option<&ConditionalTypeData> {
        match self {
            Self::ConditionalType(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_construct_signature(&self) -> Option<&ConstructSignatureData> {
        match self {
            Self::ConstructSignature(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_constructor(&self) -> Option<&ConstructorData> {
        match self {
            Self::Constructor(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_constructor_type(&self) -> Option<&ConstructorTypeData> {
        match self {
            Self::ConstructorType(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_continue_statement(&self) -> Option<&ContinueStatementData> {
        match self {
            Self::ContinueStatement(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_decorator(&self) -> Option<&DecoratorData> {
        match self {
            Self::Decorator(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_default_clause(&self) -> Option<&DefaultClauseData> {
        match self {
            Self::DefaultClause(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_delete_expression(&self) -> Option<&DeleteExpressionData> {
        match self {
            Self::DeleteExpression(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_do_statement(&self) -> Option<&DoStatementData> {
        match self {
            Self::DoStatement(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_element_access_expression(&self) -> Option<&ElementAccessExpressionData> {
        match self {
            Self::ElementAccessExpression(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_enum_declaration(&self) -> Option<&EnumDeclarationData> {
        match self {
            Self::EnumDeclaration(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_enum_member(&self) -> Option<&EnumMemberData> {
        match self {
            Self::EnumMember(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_export_assignment(&self) -> Option<&ExportAssignmentData> {
        match self {
            Self::ExportAssignment(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_export_declaration(&self) -> Option<&ExportDeclarationData> {
        match self {
            Self::ExportDeclaration(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_export_specifier(&self) -> Option<&ExportSpecifierData> {
        match self {
            Self::ExportSpecifier(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_expression_statement(&self) -> Option<&ExpressionStatementData> {
        match self {
            Self::ExpressionStatement(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_expression_with_type_arguments(&self) -> Option<&ExpressionWithTypeArgumentsData> {
        match self {
            Self::ExpressionWithTypeArguments(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_external_module_reference(&self) -> Option<&ExternalModuleReferenceData> {
        match self {
            Self::ExternalModuleReference(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_for_in_statement(&self) -> Option<&ForInStatementData> {
        match self {
            Self::ForInStatement(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_for_of_statement(&self) -> Option<&ForOfStatementData> {
        match self {
            Self::ForOfStatement(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_for_statement(&self) -> Option<&ForStatementData> {
        match self {
            Self::ForStatement(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_function_declaration(&self) -> Option<&FunctionDeclarationData> {
        match self {
            Self::FunctionDeclaration(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_function_expression(&self) -> Option<&FunctionExpressionData> {
        match self {
            Self::FunctionExpression(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_function_type(&self) -> Option<&FunctionTypeData> {
        match self {
            Self::FunctionType(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_get_accessor(&self) -> Option<&GetAccessorData> {
        match self {
            Self::GetAccessor(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_heritage_clause(&self) -> Option<&HeritageClauseData> {
        match self {
            Self::HeritageClause(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_identifier(&self) -> Option<&IdentifierData> {
        match self {
            Self::Identifier(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_if_statement(&self) -> Option<&IfStatementData> {
        match self {
            Self::IfStatement(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_import_attribute(&self) -> Option<&ImportAttributeData> {
        match self {
            Self::ImportAttribute(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_import_attributes(&self) -> Option<&ImportAttributesData> {
        match self {
            Self::ImportAttributes(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_import_clause(&self) -> Option<&ImportClauseData> {
        match self {
            Self::ImportClause(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_import_declaration(&self) -> Option<&ImportDeclarationData> {
        match self {
            Self::ImportDeclaration(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_import_equals_declaration(&self) -> Option<&ImportEqualsDeclarationData> {
        match self {
            Self::ImportEqualsDeclaration(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_import_specifier(&self) -> Option<&ImportSpecifierData> {
        match self {
            Self::ImportSpecifier(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_import_type(&self) -> Option<&ImportTypeData> {
        match self {
            Self::ImportType(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_import_type_assertion_container(&self) -> Option<&ImportTypeAssertionContainerData> {
        match self {
            Self::ImportTypeAssertionContainer(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_index_signature(&self) -> Option<&IndexSignatureData> {
        match self {
            Self::IndexSignature(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_indexed_access_type(&self) -> Option<&IndexedAccessTypeData> {
        match self {
            Self::IndexedAccessType(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_infer_type(&self) -> Option<&InferTypeData> {
        match self {
            Self::InferType(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_interface_declaration(&self) -> Option<&InterfaceDeclarationData> {
        match self {
            Self::InterfaceDeclaration(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_intersection_type(&self) -> Option<&IntersectionTypeData> {
        match self {
            Self::IntersectionType(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc(&self) -> Option<&JSDocData> {
        match self {
            Self::JSDoc(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_augments_tag(&self) -> Option<&JSDocAugmentsTagData> {
        match self {
            Self::JSDocAugmentsTag(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_author_tag(&self) -> Option<&JSDocAuthorTagData> {
        match self {
            Self::JSDocAuthorTag(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_callback_tag(&self) -> Option<&JSDocCallbackTagData> {
        match self {
            Self::JSDocCallbackTag(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_class_tag(&self) -> Option<&JSDocClassTagData> {
        match self {
            Self::JSDocClassTag(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_deprecated_tag(&self) -> Option<&JSDocDeprecatedTagData> {
        match self {
            Self::JSDocDeprecatedTag(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_enum_tag(&self) -> Option<&JSDocEnumTagData> {
        match self {
            Self::JSDocEnumTag(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_function_type(&self) -> Option<&JSDocFunctionTypeData> {
        match self {
            Self::JSDocFunctionType(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_implements_tag(&self) -> Option<&JSDocImplementsTagData> {
        match self {
            Self::JSDocImplementsTag(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_import_tag(&self) -> Option<&JSDocImportTagData> {
        match self {
            Self::JSDocImportTag(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_link(&self) -> Option<&JSDocLinkData> {
        match self {
            Self::JSDocLink(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_link_code(&self) -> Option<&JSDocLinkCodeData> {
        match self {
            Self::JSDocLinkCode(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_link_plain(&self) -> Option<&JSDocLinkPlainData> {
        match self {
            Self::JSDocLinkPlain(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_member_name(&self) -> Option<&JSDocMemberNameData> {
        match self {
            Self::JSDocMemberName(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_name_reference(&self) -> Option<&JSDocNameReferenceData> {
        match self {
            Self::JSDocNameReference(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_non_nullable_type(&self) -> Option<&JSDocNonNullableTypeData> {
        match self {
            Self::JSDocNonNullableType(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_nullable_type(&self) -> Option<&JSDocNullableTypeData> {
        match self {
            Self::JSDocNullableType(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_optional_type(&self) -> Option<&JSDocOptionalTypeData> {
        match self {
            Self::JSDocOptionalType(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_overload_tag(&self) -> Option<&JSDocOverloadTagData> {
        match self {
            Self::JSDocOverloadTag(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_override_tag(&self) -> Option<&JSDocOverrideTagData> {
        match self {
            Self::JSDocOverrideTag(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_parameter_tag(&self) -> Option<&JSDocParameterTagData> {
        match self {
            Self::JSDocParameterTag(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_private_tag(&self) -> Option<&JSDocPrivateTagData> {
        match self {
            Self::JSDocPrivateTag(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_property_tag(&self) -> Option<&JSDocPropertyTagData> {
        match self {
            Self::JSDocPropertyTag(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_protected_tag(&self) -> Option<&JSDocProtectedTagData> {
        match self {
            Self::JSDocProtectedTag(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_public_tag(&self) -> Option<&JSDocPublicTagData> {
        match self {
            Self::JSDocPublicTag(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_readonly_tag(&self) -> Option<&JSDocReadonlyTagData> {
        match self {
            Self::JSDocReadonlyTag(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_return_tag(&self) -> Option<&JSDocReturnTagData> {
        match self {
            Self::JSDocReturnTag(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_satisfies_tag(&self) -> Option<&JSDocSatisfiesTagData> {
        match self {
            Self::JSDocSatisfiesTag(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_see_tag(&self) -> Option<&JSDocSeeTagData> {
        match self {
            Self::JSDocSeeTag(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_signature(&self) -> Option<&JSDocSignatureData> {
        match self {
            Self::JSDocSignature(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_tag(&self) -> Option<&JSDocTagData> {
        match self {
            Self::JSDocTag(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_template_tag(&self) -> Option<&JSDocTemplateTagData> {
        match self {
            Self::JSDocTemplateTag(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_this_tag(&self) -> Option<&JSDocThisTagData> {
        match self {
            Self::JSDocThisTag(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_throws_tag(&self) -> Option<&JSDocThrowsTagData> {
        match self {
            Self::JSDocThrowsTag(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_type_expression(&self) -> Option<&JSDocTypeExpressionData> {
        match self {
            Self::JSDocTypeExpression(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_type_literal(&self) -> Option<&JSDocTypeLiteralData> {
        match self {
            Self::JSDocTypeLiteral(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_type_tag(&self) -> Option<&JSDocTypeTagData> {
        match self {
            Self::JSDocTypeTag(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_typedef_tag(&self) -> Option<&JSDocTypedefTagData> {
        match self {
            Self::JSDocTypedefTag(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_js_doc_variadic_type(&self) -> Option<&JSDocVariadicTypeData> {
        match self {
            Self::JSDocVariadicType(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_jsx_attribute(&self) -> Option<&JsxAttributeData> {
        match self {
            Self::JsxAttribute(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_jsx_attributes(&self) -> Option<&JsxAttributesData> {
        match self {
            Self::JsxAttributes(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_jsx_closing_element(&self) -> Option<&JsxClosingElementData> {
        match self {
            Self::JsxClosingElement(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_jsx_element(&self) -> Option<&JsxElementData> {
        match self {
            Self::JsxElement(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_jsx_expression(&self) -> Option<&JsxExpressionData> {
        match self {
            Self::JsxExpression(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_jsx_fragment(&self) -> Option<&JsxFragmentData> {
        match self {
            Self::JsxFragment(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_jsx_namespaced_name(&self) -> Option<&JsxNamespacedNameData> {
        match self {
            Self::JsxNamespacedName(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_jsx_opening_element(&self) -> Option<&JsxOpeningElementData> {
        match self {
            Self::JsxOpeningElement(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_jsx_self_closing_element(&self) -> Option<&JsxSelfClosingElementData> {
        match self {
            Self::JsxSelfClosingElement(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_jsx_spread_attribute(&self) -> Option<&JsxSpreadAttributeData> {
        match self {
            Self::JsxSpreadAttribute(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_jsx_text(&self) -> Option<&JsxTextData> {
        match self {
            Self::JsxText(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_labeled_statement(&self) -> Option<&LabeledStatementData> {
        match self {
            Self::LabeledStatement(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_literal_type(&self) -> Option<&LiteralTypeData> {
        match self {
            Self::LiteralType(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_mapped_type(&self) -> Option<&MappedTypeData> {
        match self {
            Self::MappedType(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_meta_property(&self) -> Option<&MetaPropertyData> {
        match self {
            Self::MetaProperty(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_method_declaration(&self) -> Option<&MethodDeclarationData> {
        match self {
            Self::MethodDeclaration(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_method_signature(&self) -> Option<&MethodSignatureData> {
        match self {
            Self::MethodSignature(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_missing_declaration(&self) -> Option<&MissingDeclarationData> {
        match self {
            Self::MissingDeclaration(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_module_block(&self) -> Option<&ModuleBlockData> {
        match self {
            Self::ModuleBlock(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_module_declaration(&self) -> Option<&ModuleDeclarationData> {
        match self {
            Self::ModuleDeclaration(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_named_exports(&self) -> Option<&NamedExportsData> {
        match self {
            Self::NamedExports(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_named_imports(&self) -> Option<&NamedImportsData> {
        match self {
            Self::NamedImports(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_named_tuple_member(&self) -> Option<&NamedTupleMemberData> {
        match self {
            Self::NamedTupleMember(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_namespace_export(&self) -> Option<&NamespaceExportData> {
        match self {
            Self::NamespaceExport(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_namespace_export_declaration(&self) -> Option<&NamespaceExportDeclarationData> {
        match self {
            Self::NamespaceExportDeclaration(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_namespace_import(&self) -> Option<&NamespaceImportData> {
        match self {
            Self::NamespaceImport(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_new_expression(&self) -> Option<&NewExpressionData> {
        match self {
            Self::NewExpression(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_no_substitution_template_literal(
        &self,
    ) -> Option<&NoSubstitutionTemplateLiteralData> {
        match self {
            Self::NoSubstitutionTemplateLiteral(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_non_null_expression(&self) -> Option<&NonNullExpressionData> {
        match self {
            Self::NonNullExpression(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_numeric_literal(&self) -> Option<&NumericLiteralData> {
        match self {
            Self::NumericLiteral(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_object_binding_pattern(&self) -> Option<&ObjectBindingPatternData> {
        match self {
            Self::ObjectBindingPattern(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_object_literal_expression(&self) -> Option<&ObjectLiteralExpressionData> {
        match self {
            Self::ObjectLiteralExpression(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_optional_type(&self) -> Option<&OptionalTypeData> {
        match self {
            Self::OptionalType(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_parameter(&self) -> Option<&ParameterData> {
        match self {
            Self::Parameter(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_parenthesized_expression(&self) -> Option<&ParenthesizedExpressionData> {
        match self {
            Self::ParenthesizedExpression(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_parenthesized_type(&self) -> Option<&ParenthesizedTypeData> {
        match self {
            Self::ParenthesizedType(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_partially_emitted_expression(&self) -> Option<&PartiallyEmittedExpressionData> {
        match self {
            Self::PartiallyEmittedExpression(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_postfix_unary_expression(&self) -> Option<&PostfixUnaryExpressionData> {
        match self {
            Self::PostfixUnaryExpression(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_prefix_unary_expression(&self) -> Option<&PrefixUnaryExpressionData> {
        match self {
            Self::PrefixUnaryExpression(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_private_identifier(&self) -> Option<&PrivateIdentifierData> {
        match self {
            Self::PrivateIdentifier(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_property_access_expression(&self) -> Option<&PropertyAccessExpressionData> {
        match self {
            Self::PropertyAccessExpression(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_property_assignment(&self) -> Option<&PropertyAssignmentData> {
        match self {
            Self::PropertyAssignment(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_property_declaration(&self) -> Option<&PropertyDeclarationData> {
        match self {
            Self::PropertyDeclaration(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_property_signature(&self) -> Option<&PropertySignatureData> {
        match self {
            Self::PropertySignature(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_qualified_name(&self) -> Option<&QualifiedNameData> {
        match self {
            Self::QualifiedName(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_regular_expression_literal(&self) -> Option<&RegularExpressionLiteralData> {
        match self {
            Self::RegularExpressionLiteral(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_rest_type(&self) -> Option<&RestTypeData> {
        match self {
            Self::RestType(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_return_statement(&self) -> Option<&ReturnStatementData> {
        match self {
            Self::ReturnStatement(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_satisfies_expression(&self) -> Option<&SatisfiesExpressionData> {
        match self {
            Self::SatisfiesExpression(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_set_accessor(&self) -> Option<&SetAccessorData> {
        match self {
            Self::SetAccessor(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_shorthand_property_assignment(&self) -> Option<&ShorthandPropertyAssignmentData> {
        match self {
            Self::ShorthandPropertyAssignment(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_source_file(&self) -> Option<&SourceFileData> {
        match self {
            Self::SourceFile(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_spread_assignment(&self) -> Option<&SpreadAssignmentData> {
        match self {
            Self::SpreadAssignment(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_spread_element(&self) -> Option<&SpreadElementData> {
        match self {
            Self::SpreadElement(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_string_literal(&self) -> Option<&StringLiteralData> {
        match self {
            Self::StringLiteral(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_switch_statement(&self) -> Option<&SwitchStatementData> {
        match self {
            Self::SwitchStatement(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_syntax_list(&self) -> Option<&SyntaxListData> {
        match self {
            Self::SyntaxList(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_tagged_template_expression(&self) -> Option<&TaggedTemplateExpressionData> {
        match self {
            Self::TaggedTemplateExpression(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_template_expression(&self) -> Option<&TemplateExpressionData> {
        match self {
            Self::TemplateExpression(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_template_head(&self) -> Option<&TemplateHeadData> {
        match self {
            Self::TemplateHead(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_template_literal_type(&self) -> Option<&TemplateLiteralTypeData> {
        match self {
            Self::TemplateLiteralType(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_template_literal_type_span(&self) -> Option<&TemplateLiteralTypeSpanData> {
        match self {
            Self::TemplateLiteralTypeSpan(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_template_middle(&self) -> Option<&TemplateMiddleData> {
        match self {
            Self::TemplateMiddle(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_template_span(&self) -> Option<&TemplateSpanData> {
        match self {
            Self::TemplateSpan(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_template_tail(&self) -> Option<&TemplateTailData> {
        match self {
            Self::TemplateTail(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_throw_statement(&self) -> Option<&ThrowStatementData> {
        match self {
            Self::ThrowStatement(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_try_statement(&self) -> Option<&TryStatementData> {
        match self {
            Self::TryStatement(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_tuple_type(&self) -> Option<&TupleTypeData> {
        match self {
            Self::TupleType(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_type_alias_declaration(&self) -> Option<&TypeAliasDeclarationData> {
        match self {
            Self::TypeAliasDeclaration(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_type_assertion_expression(&self) -> Option<&TypeAssertionExpressionData> {
        match self {
            Self::TypeAssertionExpression(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_type_literal(&self) -> Option<&TypeLiteralData> {
        match self {
            Self::TypeLiteral(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_type_of_expression(&self) -> Option<&TypeOfExpressionData> {
        match self {
            Self::TypeOfExpression(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_type_operator(&self) -> Option<&TypeOperatorData> {
        match self {
            Self::TypeOperator(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_type_parameter(&self) -> Option<&TypeParameterData> {
        match self {
            Self::TypeParameter(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_type_predicate(&self) -> Option<&TypePredicateData> {
        match self {
            Self::TypePredicate(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_type_query(&self) -> Option<&TypeQueryData> {
        match self {
            Self::TypeQuery(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_type_reference(&self) -> Option<&TypeReferenceData> {
        match self {
            Self::TypeReference(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_union_type(&self) -> Option<&UnionTypeData> {
        match self {
            Self::UnionType(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_variable_declaration(&self) -> Option<&VariableDeclarationData> {
        match self {
            Self::VariableDeclaration(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_variable_declaration_list(&self) -> Option<&VariableDeclarationListData> {
        match self {
            Self::VariableDeclarationList(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_variable_statement(&self) -> Option<&VariableStatementData> {
        match self {
            Self::VariableStatement(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_void_expression(&self) -> Option<&VoidExpressionData> {
        match self {
            Self::VoidExpression(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_while_statement(&self) -> Option<&WhileStatementData> {
        match self {
            Self::WhileStatement(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_with_statement(&self) -> Option<&WithStatementData> {
        match self {
            Self::WithStatement(data) => Some(data),
            _ => None,
        }
    }

    pub fn as_yield_expression(&self) -> Option<&YieldExpressionData> {
        match self {
            Self::YieldExpression(data) => Some(data),
            _ => None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_node_schema_has_core_nodes() {
        assert_eq!(NodeData::Token.kind(), None);
        let _ = IdentifierData {
            escaped_text: String::new(),
            text: String::new(),
        };
    }
}
