from pathlib import Path
import hashlib,json,re,subprocess
r=Path('/Users/hiramatsu/dev/tsc-rs-emitter-final-variable-producer-prep');j=json.loads(Path('/tmp/emitter-runtime-input-census-r229.json').read_text());head=subprocess.check_output(['git','rev-parse','HEAD'],cwd=r,text=True).strip();assert head==j['head'];assert not subprocess.check_output(['git','diff','HEAD','--name-only'],cwd=r).strip()
out=Path('/tmp/emitter-runtime-input-proposal-r229');out.mkdir(exist_ok=False);sha=lambda b:hashlib.sha256(b).hexdigest();paths=['crates/oracle/h2-5g-profile.mjs','.github/ci/contracts/h2-5g-profile.schema.json'];before={p:(r/p).read_bytes() for p in paths};s=before[paths[0]].decode();assert j['missing_count']==599 and j['union_before']==323;assert j['stale']==['crates/emitter/tests/unit/tagged_template/tests.rs'];stale=j['stale'][0];assert not (r/stale).exists();needle=f'  "{stale}",\n';assert s.count(needle)==1;s=s.replace(needle,'');add='''  // Emitter-final integration: preserve all prior surviving identities and
  // bind the complete changed crate closure, including integration controls.
  // A path hash is input identity, not proof that a test or fixture executes.
'''+''.join(f'  {json.dumps(p)},\n' for p in j['missing']);end=s.index('\n]);',s.index('const NEW_RUNTIME_INPUTS = Object.freeze(['));s=s[:end]+'\n'+add.rstrip('\n')+s[end:];count=323+599-1;assert count==921;s=s.replace('runtimeInputSet.size === 323','runtimeInputSet.size === 921').replace('pinned 323)','pinned 921)');assert len(re.findall(r'"crates/[^"\n]+"',s.split('const NEW_RUNTIME_INPUTS = Object.freeze([',1)[1].split('\n]);',1)[0]))==835
schema=json.loads(before[paths[1]]);after=json.loads(before[paths[1]]);assert schema['properties']['runtime_inputs']['minItems']==schema['properties']['runtime_inputs']['maxItems']==323;after['properties']['runtime_inputs']['minItems']=after['properties']['runtime_inputs']['maxItems']=921;raw=before[paths[1]].decode();assert raw.count('"minItems": 323,')==raw.count('"maxItems": 323,')==1;raw=raw.replace('"minItems": 323,','"minItems": 921,').replace('"maxItems": 323,','"maxItems": 921,');assert json.loads(raw)==after
files=[]
for p,data in zip(paths,[s.encode(),raw.encode()]):
 q=out/p;q.parent.mkdir(parents=True,exist_ok=True);q.write_bytes(data);files.append({'path':p,'before_sha256':sha(before[p]),'after_sha256':sha(data)})
manifest={'head':head,'files':files,'parent_inputs_preserved':86,'previous_inputs':323,'added_paths':j['missing'],'removed_path':stale,'removal_reason':'file deleted by d364a056a and absent at trusted main and current HEAD; preserve history, do not fabricate an input file','inputs_after':921,'existing_shadow_exemptions_unchanged':True,'limits':'Conservative input hashes only, no additional case admission or execution/qualification claim; official canonical walk regenerates artifacts.'};(out/'proposal.json').write_text(json.dumps(manifest,indent=2)+'\n');print(json.dumps({'out':str(out),'added':599,'removed_deleted':1,'after':921}))
