// @generated by `cargo xtask codegen nodes`. Do not edit by hand.

use crate::nodes::{JSDocComment, Node, NodeArrayId, NodeData, NodeId};

#[derive(Clone, Copy, Debug, PartialEq)]
pub enum ObservableField<'a> {
    Node(NodeId),
    NodeArray(NodeArrayId),
    Bool(bool),
    String(&'a str),
}

pub fn for_each_observable_field<'a, F>(node: &'a Node, mut cb: F)
where
    F: FnMut(&'static str, ObservableField<'a>),
{
    match &node.data {
        NodeData::Token => {}
        NodeData::ArrayBindingPattern(data) => {
            if let Some(value) = data.elements {
                cb("elements", ObservableField::NodeArray(value));
            }
        }
        NodeData::ArrayLiteralExpression(data) => {
            if let Some(value) = data.elements {
                cb("elements", ObservableField::NodeArray(value));
            }
        }
        NodeData::ArrayType(data) => {
            if let Some(value) = data.element_type {
                cb("elementType", ObservableField::Node(value));
            }
        }
        NodeData::ArrowFunction(data) => {
            if let Some(value) = data.body {
                cb("body", ObservableField::Node(value));
            }
            if let Some(value) = data.equals_greater_than_token {
                cb("equalsGreaterThanToken", ObservableField::Node(value));
            }
            if let Some(value) = data.modifiers {
                cb("modifiers", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.parameters {
                cb("parameters", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
            if let Some(value) = data.type_parameters {
                cb("typeParameters", ObservableField::NodeArray(value));
            }
        }
        NodeData::AsExpression(data) => {
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
        }
        NodeData::AwaitExpression(data) => {
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
        }
        NodeData::BigIntLiteral(data) => {
            cb("text", ObservableField::String(&data.text));
        }
        NodeData::BinaryExpression(data) => {
            if let Some(value) = data.left {
                cb("left", ObservableField::Node(value));
            }
            if let Some(value) = data.operator_token {
                cb("operatorToken", ObservableField::Node(value));
            }
            if let Some(value) = data.right {
                cb("right", ObservableField::Node(value));
            }
        }
        NodeData::BindingElement(data) => {
            if let Some(value) = data.dot_dot_dot_token {
                cb("dotDotDotToken", ObservableField::Node(value));
            }
            if let Some(value) = data.initializer {
                cb("initializer", ObservableField::Node(value));
            }
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            if let Some(value) = data.property_name {
                cb("propertyName", ObservableField::Node(value));
            }
        }
        NodeData::Block(data) => {
            if let Some(value) = data.statements {
                cb("statements", ObservableField::NodeArray(value));
            }
        }
        NodeData::BreakStatement(data) => {
            if let Some(value) = data.label {
                cb("label", ObservableField::Node(value));
            }
        }
        NodeData::CallExpression(data) => {
            if let Some(value) = data.arguments {
                cb("arguments", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
            if let Some(value) = data.question_dot_token {
                cb("questionDotToken", ObservableField::Node(value));
            }
            if let Some(value) = data.type_arguments {
                cb("typeArguments", ObservableField::NodeArray(value));
            }
        }
        NodeData::CallSignature(data) => {
            if let Some(value) = data.parameters {
                cb("parameters", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
            if let Some(value) = data.type_parameters {
                cb("typeParameters", ObservableField::NodeArray(value));
            }
        }
        NodeData::CaseBlock(data) => {
            if let Some(value) = data.clauses {
                cb("clauses", ObservableField::NodeArray(value));
            }
        }
        NodeData::CaseClause(data) => {
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
            if let Some(value) = data.statements {
                cb("statements", ObservableField::NodeArray(value));
            }
        }
        NodeData::CatchClause(data) => {
            if let Some(value) = data.block {
                cb("block", ObservableField::Node(value));
            }
            if let Some(value) = data.variable_declaration {
                cb("variableDeclaration", ObservableField::Node(value));
            }
        }
        NodeData::ClassDeclaration(data) => {
            if let Some(value) = data.heritage_clauses {
                cb("heritageClauses", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.members {
                cb("members", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.modifiers {
                cb("modifiers", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            if let Some(value) = data.type_parameters {
                cb("typeParameters", ObservableField::NodeArray(value));
            }
        }
        NodeData::ClassExpression(data) => {
            if let Some(value) = data.heritage_clauses {
                cb("heritageClauses", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.members {
                cb("members", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.modifiers {
                cb("modifiers", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            if let Some(value) = data.type_parameters {
                cb("typeParameters", ObservableField::NodeArray(value));
            }
        }
        NodeData::ClassStaticBlockDeclaration(data) => {
            if let Some(value) = data.body {
                cb("body", ObservableField::Node(value));
            }
            if let Some(value) = data.modifiers {
                cb("modifiers", ObservableField::NodeArray(value));
            }
        }
        NodeData::CommaListExpression(data) => {
            if let Some(value) = data.elements {
                cb("elements", ObservableField::NodeArray(value));
            }
        }
        NodeData::ComputedPropertyName(data) => {
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
        }
        NodeData::ConditionalExpression(data) => {
            if let Some(value) = data.colon_token {
                cb("colonToken", ObservableField::Node(value));
            }
            if let Some(value) = data.condition {
                cb("condition", ObservableField::Node(value));
            }
            if let Some(value) = data.question_token {
                cb("questionToken", ObservableField::Node(value));
            }
            if let Some(value) = data.when_false {
                cb("whenFalse", ObservableField::Node(value));
            }
            if let Some(value) = data.when_true {
                cb("whenTrue", ObservableField::Node(value));
            }
        }
        NodeData::ConditionalType(data) => {
            if let Some(value) = data.check_type {
                cb("checkType", ObservableField::Node(value));
            }
            if let Some(value) = data.extends_type {
                cb("extendsType", ObservableField::Node(value));
            }
            if let Some(value) = data.false_type {
                cb("falseType", ObservableField::Node(value));
            }
            if let Some(value) = data.true_type {
                cb("trueType", ObservableField::Node(value));
            }
        }
        NodeData::ConstructSignature(data) => {
            if let Some(value) = data.parameters {
                cb("parameters", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
            if let Some(value) = data.type_parameters {
                cb("typeParameters", ObservableField::NodeArray(value));
            }
        }
        NodeData::Constructor(data) => {
            if let Some(value) = data.body {
                cb("body", ObservableField::Node(value));
            }
            if let Some(value) = data.modifiers {
                cb("modifiers", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            if let Some(value) = data.parameters {
                cb("parameters", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
            if let Some(value) = data.type_parameters {
                cb("typeParameters", ObservableField::NodeArray(value));
            }
        }
        NodeData::ConstructorType(data) => {
            if let Some(value) = data.modifiers {
                cb("modifiers", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.parameters {
                cb("parameters", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
            if let Some(value) = data.type_parameters {
                cb("typeParameters", ObservableField::NodeArray(value));
            }
        }
        NodeData::ContinueStatement(data) => {
            if let Some(value) = data.label {
                cb("label", ObservableField::Node(value));
            }
        }
        NodeData::DebuggerStatement(_data) => {}
        NodeData::Decorator(data) => {
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
        }
        NodeData::DefaultClause(data) => {
            if let Some(value) = data.statements {
                cb("statements", ObservableField::NodeArray(value));
            }
        }
        NodeData::DeleteExpression(data) => {
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
        }
        NodeData::DoStatement(data) => {
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
            if let Some(value) = data.statement {
                cb("statement", ObservableField::Node(value));
            }
        }
        NodeData::ElementAccessExpression(data) => {
            if let Some(value) = data.argument_expression {
                cb("argumentExpression", ObservableField::Node(value));
            }
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
            if let Some(value) = data.question_dot_token {
                cb("questionDotToken", ObservableField::Node(value));
            }
        }
        NodeData::EmptyStatement(_data) => {}
        NodeData::EnumDeclaration(data) => {
            if let Some(value) = data.members {
                cb("members", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.modifiers {
                cb("modifiers", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
        }
        NodeData::EnumMember(data) => {
            if let Some(value) = data.initializer {
                cb("initializer", ObservableField::Node(value));
            }
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
        }
        NodeData::ExportAssignment(data) => {
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
            if let Some(value) = data.is_export_equals {
                cb("isExportEquals", ObservableField::Bool(value));
            }
            if let Some(value) = data.modifiers {
                cb("modifiers", ObservableField::NodeArray(value));
            }
        }
        NodeData::ExportDeclaration(data) => {
            if let Some(value) = data.attributes {
                cb("attributes", ObservableField::Node(value));
            }
            if let Some(value) = data.export_clause {
                cb("exportClause", ObservableField::Node(value));
            }
            cb("isTypeOnly", ObservableField::Bool(data.is_type_only));
            if let Some(value) = data.modifiers {
                cb("modifiers", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.module_specifier {
                cb("moduleSpecifier", ObservableField::Node(value));
            }
        }
        NodeData::ExportSpecifier(data) => {
            cb("isTypeOnly", ObservableField::Bool(data.is_type_only));
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            if let Some(value) = data.property_name {
                cb("propertyName", ObservableField::Node(value));
            }
        }
        NodeData::ExpressionStatement(data) => {
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
        }
        NodeData::ExpressionWithTypeArguments(data) => {
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
            if let Some(value) = data.type_arguments {
                cb("typeArguments", ObservableField::NodeArray(value));
            }
        }
        NodeData::ExternalModuleReference(data) => {
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
        }
        NodeData::ForInStatement(data) => {
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
            if let Some(value) = data.initializer {
                cb("initializer", ObservableField::Node(value));
            }
            if let Some(value) = data.statement {
                cb("statement", ObservableField::Node(value));
            }
        }
        NodeData::ForOfStatement(data) => {
            if let Some(value) = data.await_modifier {
                cb("awaitModifier", ObservableField::Node(value));
            }
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
            if let Some(value) = data.initializer {
                cb("initializer", ObservableField::Node(value));
            }
            if let Some(value) = data.statement {
                cb("statement", ObservableField::Node(value));
            }
        }
        NodeData::ForStatement(data) => {
            if let Some(value) = data.condition {
                cb("condition", ObservableField::Node(value));
            }
            if let Some(value) = data.incrementor {
                cb("incrementor", ObservableField::Node(value));
            }
            if let Some(value) = data.initializer {
                cb("initializer", ObservableField::Node(value));
            }
            if let Some(value) = data.statement {
                cb("statement", ObservableField::Node(value));
            }
        }
        NodeData::FunctionDeclaration(data) => {
            if let Some(value) = data.asterisk_token {
                cb("asteriskToken", ObservableField::Node(value));
            }
            if let Some(value) = data.body {
                cb("body", ObservableField::Node(value));
            }
            if let Some(value) = data.modifiers {
                cb("modifiers", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            if let Some(value) = data.parameters {
                cb("parameters", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
            if let Some(value) = data.type_parameters {
                cb("typeParameters", ObservableField::NodeArray(value));
            }
        }
        NodeData::FunctionExpression(data) => {
            if let Some(value) = data.asterisk_token {
                cb("asteriskToken", ObservableField::Node(value));
            }
            if let Some(value) = data.body {
                cb("body", ObservableField::Node(value));
            }
            if let Some(value) = data.modifiers {
                cb("modifiers", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            if let Some(value) = data.parameters {
                cb("parameters", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
            if let Some(value) = data.type_parameters {
                cb("typeParameters", ObservableField::NodeArray(value));
            }
        }
        NodeData::FunctionType(data) => {
            if let Some(value) = data.modifiers {
                cb("modifiers", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.parameters {
                cb("parameters", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
            if let Some(value) = data.type_parameters {
                cb("typeParameters", ObservableField::NodeArray(value));
            }
        }
        NodeData::GetAccessor(data) => {
            if let Some(value) = data.body {
                cb("body", ObservableField::Node(value));
            }
            if let Some(value) = data.modifiers {
                cb("modifiers", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            if let Some(value) = data.parameters {
                cb("parameters", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
            if let Some(value) = data.type_parameters {
                cb("typeParameters", ObservableField::NodeArray(value));
            }
        }
        NodeData::HeritageClause(data) => {
            if let Some(value) = data.types {
                cb("types", ObservableField::NodeArray(value));
            }
        }
        NodeData::Identifier(data) => {
            cb("escapedText", ObservableField::String(&data.escaped_text));
        }
        NodeData::IfStatement(data) => {
            if let Some(value) = data.else_statement {
                cb("elseStatement", ObservableField::Node(value));
            }
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
            if let Some(value) = data.then_statement {
                cb("thenStatement", ObservableField::Node(value));
            }
        }
        NodeData::ImportAttribute(data) => {
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            if let Some(value) = data.value {
                cb("value", ObservableField::Node(value));
            }
        }
        NodeData::ImportAttributes(data) => {
            if let Some(value) = data.elements {
                cb("elements", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.multi_line {
                cb("multiLine", ObservableField::Bool(value));
            }
        }
        NodeData::ImportClause(data) => {
            cb("isTypeOnly", ObservableField::Bool(data.is_type_only));
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            if let Some(value) = data.named_bindings {
                cb("namedBindings", ObservableField::Node(value));
            }
        }
        NodeData::ImportDeclaration(data) => {
            if let Some(value) = data.attributes {
                cb("attributes", ObservableField::Node(value));
            }
            if let Some(value) = data.import_clause {
                cb("importClause", ObservableField::Node(value));
            }
            if let Some(value) = data.modifiers {
                cb("modifiers", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.module_specifier {
                cb("moduleSpecifier", ObservableField::Node(value));
            }
        }
        NodeData::ImportEqualsDeclaration(data) => {
            cb("isTypeOnly", ObservableField::Bool(data.is_type_only));
            if let Some(value) = data.modifiers {
                cb("modifiers", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.module_reference {
                cb("moduleReference", ObservableField::Node(value));
            }
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
        }
        NodeData::ImportSpecifier(data) => {
            cb("isTypeOnly", ObservableField::Bool(data.is_type_only));
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            if let Some(value) = data.property_name {
                cb("propertyName", ObservableField::Node(value));
            }
        }
        NodeData::ImportType(data) => {
            if let Some(value) = data.argument {
                cb("argument", ObservableField::Node(value));
            }
            if let Some(value) = data.attributes {
                cb("attributes", ObservableField::Node(value));
            }
            cb("isTypeOf", ObservableField::Bool(data.is_type_of));
            if let Some(value) = data.qualifier {
                cb("qualifier", ObservableField::Node(value));
            }
            if let Some(value) = data.type_arguments {
                cb("typeArguments", ObservableField::NodeArray(value));
            }
        }
        NodeData::ImportTypeAssertionContainer(data) => {
            if let Some(value) = data.assert_clause {
                cb("assertClause", ObservableField::Node(value));
            }
        }
        NodeData::IndexSignature(data) => {
            if let Some(value) = data.modifiers {
                cb("modifiers", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.parameters {
                cb("parameters", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
            if let Some(value) = data.type_parameters {
                cb("typeParameters", ObservableField::NodeArray(value));
            }
        }
        NodeData::IndexedAccessType(data) => {
            if let Some(value) = data.index_type {
                cb("indexType", ObservableField::Node(value));
            }
            if let Some(value) = data.object_type {
                cb("objectType", ObservableField::Node(value));
            }
        }
        NodeData::InferType(data) => {
            if let Some(value) = data.type_parameter {
                cb("typeParameter", ObservableField::Node(value));
            }
        }
        NodeData::InterfaceDeclaration(data) => {
            if let Some(value) = data.heritage_clauses {
                cb("heritageClauses", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.members {
                cb("members", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.modifiers {
                cb("modifiers", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            if let Some(value) = data.type_parameters {
                cb("typeParameters", ObservableField::NodeArray(value));
            }
        }
        NodeData::IntersectionType(data) => {
            if let Some(value) = data.types {
                cb("types", ObservableField::NodeArray(value));
            }
        }
        NodeData::JSDoc(data) => {
            if let Some(value) = data.comment.as_ref() {
                emit_jsdoc_comment("comment", value, &mut cb);
            }
            if let Some(value) = data.tags {
                cb("tags", ObservableField::NodeArray(value));
            }
        }
        NodeData::JSDocAllType(_data) => {}
        NodeData::JSDocAugmentsTag(data) => {
            if let Some(value) = data.class {
                cb("class", ObservableField::Node(value));
            }
            if let Some(value) = data.comment.as_ref() {
                emit_jsdoc_comment("comment", value, &mut cb);
            }
            if let Some(value) = data.tag_name {
                cb("tagName", ObservableField::Node(value));
            }
        }
        NodeData::JSDocAuthorTag(data) => {
            if let Some(value) = data.comment.as_ref() {
                emit_jsdoc_comment("comment", value, &mut cb);
            }
            if let Some(value) = data.tag_name {
                cb("tagName", ObservableField::Node(value));
            }
        }
        NodeData::JSDocCallbackTag(data) => {
            if let Some(value) = data.comment.as_ref() {
                emit_jsdoc_comment("comment", value, &mut cb);
            }
            if let Some(value) = data.full_name {
                cb("fullName", ObservableField::Node(value));
            }
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            if let Some(value) = data.tag_name {
                cb("tagName", ObservableField::Node(value));
            }
            if let Some(value) = data.type_expression {
                cb("typeExpression", ObservableField::Node(value));
            }
        }
        NodeData::JSDocClassTag(data) => {
            if let Some(value) = data.comment.as_ref() {
                emit_jsdoc_comment("comment", value, &mut cb);
            }
            if let Some(value) = data.tag_name {
                cb("tagName", ObservableField::Node(value));
            }
        }
        NodeData::JSDocDeprecatedTag(data) => {
            if let Some(value) = data.comment.as_ref() {
                emit_jsdoc_comment("comment", value, &mut cb);
            }
            if let Some(value) = data.tag_name {
                cb("tagName", ObservableField::Node(value));
            }
        }
        NodeData::JSDocEnumTag(data) => {
            if let Some(value) = data.comment.as_ref() {
                emit_jsdoc_comment("comment", value, &mut cb);
            }
            if let Some(value) = data.tag_name {
                cb("tagName", ObservableField::Node(value));
            }
            if let Some(value) = data.type_expression {
                cb("typeExpression", ObservableField::Node(value));
            }
        }
        NodeData::JSDocFunctionType(data) => {
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            if let Some(value) = data.parameters {
                cb("parameters", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
            if let Some(value) = data.type_parameters {
                cb("typeParameters", ObservableField::NodeArray(value));
            }
        }
        NodeData::JSDocImplementsTag(data) => {
            if let Some(value) = data.class {
                cb("class", ObservableField::Node(value));
            }
            if let Some(value) = data.comment.as_ref() {
                emit_jsdoc_comment("comment", value, &mut cb);
            }
            if let Some(value) = data.tag_name {
                cb("tagName", ObservableField::Node(value));
            }
        }
        NodeData::JSDocImportTag(data) => {
            if let Some(value) = data.attributes {
                cb("attributes", ObservableField::Node(value));
            }
            if let Some(value) = data.comment.as_ref() {
                emit_jsdoc_comment("comment", value, &mut cb);
            }
            if let Some(value) = data.import_clause {
                cb("importClause", ObservableField::Node(value));
            }
            if let Some(value) = data.module_specifier {
                cb("moduleSpecifier", ObservableField::Node(value));
            }
            if let Some(value) = data.tag_name {
                cb("tagName", ObservableField::Node(value));
            }
        }
        NodeData::JSDocLink(data) => {
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            cb("text", ObservableField::String(&data.text));
        }
        NodeData::JSDocLinkCode(data) => {
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            cb("text", ObservableField::String(&data.text));
        }
        NodeData::JSDocLinkPlain(data) => {
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            cb("text", ObservableField::String(&data.text));
        }
        NodeData::JSDocMemberName(data) => {
            if let Some(value) = data.left {
                cb("left", ObservableField::Node(value));
            }
            if let Some(value) = data.right {
                cb("right", ObservableField::Node(value));
            }
        }
        NodeData::JSDocNameReference(data) => {
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
        }
        NodeData::JSDocNamepathType(data) => {
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
        }
        NodeData::JSDocNonNullableType(data) => {
            cb("postfix", ObservableField::Bool(data.postfix));
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
        }
        NodeData::JSDocNullableType(data) => {
            cb("postfix", ObservableField::Bool(data.postfix));
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
        }
        NodeData::JSDocOptionalType(data) => {
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
        }
        NodeData::JSDocOverloadTag(data) => {
            if let Some(value) = data.comment.as_ref() {
                emit_jsdoc_comment("comment", value, &mut cb);
            }
            if let Some(value) = data.tag_name {
                cb("tagName", ObservableField::Node(value));
            }
            if let Some(value) = data.type_expression {
                cb("typeExpression", ObservableField::Node(value));
            }
        }
        NodeData::JSDocOverrideTag(data) => {
            if let Some(value) = data.comment.as_ref() {
                emit_jsdoc_comment("comment", value, &mut cb);
            }
            if let Some(value) = data.tag_name {
                cb("tagName", ObservableField::Node(value));
            }
        }
        NodeData::JSDocParameterTag(data) => {
            if let Some(value) = data.comment.as_ref() {
                emit_jsdoc_comment("comment", value, &mut cb);
            }
            cb("isBracketed", ObservableField::Bool(data.is_bracketed));
            cb("isNameFirst", ObservableField::Bool(data.is_name_first));
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            if let Some(value) = data.tag_name {
                cb("tagName", ObservableField::Node(value));
            }
            if let Some(value) = data.type_expression {
                cb("typeExpression", ObservableField::Node(value));
            }
        }
        NodeData::JSDocPrivateTag(data) => {
            if let Some(value) = data.comment.as_ref() {
                emit_jsdoc_comment("comment", value, &mut cb);
            }
            if let Some(value) = data.tag_name {
                cb("tagName", ObservableField::Node(value));
            }
        }
        NodeData::JSDocPropertyTag(data) => {
            if let Some(value) = data.comment.as_ref() {
                emit_jsdoc_comment("comment", value, &mut cb);
            }
            cb("isBracketed", ObservableField::Bool(data.is_bracketed));
            cb("isNameFirst", ObservableField::Bool(data.is_name_first));
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            if let Some(value) = data.tag_name {
                cb("tagName", ObservableField::Node(value));
            }
            if let Some(value) = data.type_expression {
                cb("typeExpression", ObservableField::Node(value));
            }
        }
        NodeData::JSDocProtectedTag(data) => {
            if let Some(value) = data.comment.as_ref() {
                emit_jsdoc_comment("comment", value, &mut cb);
            }
            if let Some(value) = data.tag_name {
                cb("tagName", ObservableField::Node(value));
            }
        }
        NodeData::JSDocPublicTag(data) => {
            if let Some(value) = data.comment.as_ref() {
                emit_jsdoc_comment("comment", value, &mut cb);
            }
            if let Some(value) = data.tag_name {
                cb("tagName", ObservableField::Node(value));
            }
        }
        NodeData::JSDocReadonlyTag(data) => {
            if let Some(value) = data.comment.as_ref() {
                emit_jsdoc_comment("comment", value, &mut cb);
            }
            if let Some(value) = data.tag_name {
                cb("tagName", ObservableField::Node(value));
            }
        }
        NodeData::JSDocReturnTag(data) => {
            if let Some(value) = data.comment.as_ref() {
                emit_jsdoc_comment("comment", value, &mut cb);
            }
            if let Some(value) = data.tag_name {
                cb("tagName", ObservableField::Node(value));
            }
            if let Some(value) = data.type_expression {
                cb("typeExpression", ObservableField::Node(value));
            }
        }
        NodeData::JSDocSatisfiesTag(data) => {
            if let Some(value) = data.comment.as_ref() {
                emit_jsdoc_comment("comment", value, &mut cb);
            }
            if let Some(value) = data.tag_name {
                cb("tagName", ObservableField::Node(value));
            }
            if let Some(value) = data.type_expression {
                cb("typeExpression", ObservableField::Node(value));
            }
        }
        NodeData::JSDocSeeTag(data) => {
            if let Some(value) = data.comment.as_ref() {
                emit_jsdoc_comment("comment", value, &mut cb);
            }
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            if let Some(value) = data.tag_name {
                cb("tagName", ObservableField::Node(value));
            }
        }
        NodeData::JSDocSignature(data) => {
            if let Some(value) = data.parameters {
                cb("parameters", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
            if let Some(value) = data.type_parameters {
                cb("typeParameters", ObservableField::NodeArray(value));
            }
        }
        NodeData::JSDocTag(data) => {
            if let Some(value) = data.comment.as_ref() {
                emit_jsdoc_comment("comment", value, &mut cb);
            }
            if let Some(value) = data.tag_name {
                cb("tagName", ObservableField::Node(value));
            }
        }
        NodeData::JSDocTemplateTag(data) => {
            if let Some(value) = data.comment.as_ref() {
                emit_jsdoc_comment("comment", value, &mut cb);
            }
            if let Some(value) = data.constraint {
                cb("constraint", ObservableField::Node(value));
            }
            if let Some(value) = data.tag_name {
                cb("tagName", ObservableField::Node(value));
            }
            if let Some(value) = data.type_parameters {
                cb("typeParameters", ObservableField::NodeArray(value));
            }
        }
        NodeData::JSDocText(data) => {
            cb("text", ObservableField::String(&data.text));
        }
        NodeData::JSDocThisTag(data) => {
            if let Some(value) = data.comment.as_ref() {
                emit_jsdoc_comment("comment", value, &mut cb);
            }
            if let Some(value) = data.tag_name {
                cb("tagName", ObservableField::Node(value));
            }
            if let Some(value) = data.type_expression {
                cb("typeExpression", ObservableField::Node(value));
            }
        }
        NodeData::JSDocThrowsTag(data) => {
            if let Some(value) = data.comment.as_ref() {
                emit_jsdoc_comment("comment", value, &mut cb);
            }
            if let Some(value) = data.tag_name {
                cb("tagName", ObservableField::Node(value));
            }
            if let Some(value) = data.type_expression {
                cb("typeExpression", ObservableField::Node(value));
            }
        }
        NodeData::JSDocTypeExpression(data) => {
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
        }
        NodeData::JSDocTypeLiteral(data) => {
            cb("isArrayType", ObservableField::Bool(data.is_array_type));
            if let Some(value) = data.js_doc_property_tags {
                cb("jsDocPropertyTags", ObservableField::NodeArray(value));
            }
        }
        NodeData::JSDocTypeTag(data) => {
            if let Some(value) = data.comment.as_ref() {
                emit_jsdoc_comment("comment", value, &mut cb);
            }
            if let Some(value) = data.tag_name {
                cb("tagName", ObservableField::Node(value));
            }
            if let Some(value) = data.type_expression {
                cb("typeExpression", ObservableField::Node(value));
            }
        }
        NodeData::JSDocTypedefTag(data) => {
            if let Some(value) = data.comment.as_ref() {
                emit_jsdoc_comment("comment", value, &mut cb);
            }
            if let Some(value) = data.full_name {
                cb("fullName", ObservableField::Node(value));
            }
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            if let Some(value) = data.tag_name {
                cb("tagName", ObservableField::Node(value));
            }
            if let Some(value) = data.type_expression {
                cb("typeExpression", ObservableField::Node(value));
            }
        }
        NodeData::JSDocUnknownType(_data) => {}
        NodeData::JSDocVariadicType(data) => {
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
        }
        NodeData::JsxAttribute(data) => {
            if let Some(value) = data.initializer {
                cb("initializer", ObservableField::Node(value));
            }
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
        }
        NodeData::JsxAttributes(data) => {
            if let Some(value) = data.properties {
                cb("properties", ObservableField::NodeArray(value));
            }
        }
        NodeData::JsxClosingElement(data) => {
            if let Some(value) = data.tag_name {
                cb("tagName", ObservableField::Node(value));
            }
        }
        NodeData::JsxElement(data) => {
            if let Some(value) = data.children {
                cb("children", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.closing_element {
                cb("closingElement", ObservableField::Node(value));
            }
            if let Some(value) = data.opening_element {
                cb("openingElement", ObservableField::Node(value));
            }
        }
        NodeData::JsxExpression(data) => {
            if let Some(value) = data.dot_dot_dot_token {
                cb("dotDotDotToken", ObservableField::Node(value));
            }
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
        }
        NodeData::JsxFragment(data) => {
            if let Some(value) = data.children {
                cb("children", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.closing_fragment {
                cb("closingFragment", ObservableField::Node(value));
            }
            if let Some(value) = data.opening_fragment {
                cb("openingFragment", ObservableField::Node(value));
            }
        }
        NodeData::JsxNamespacedName(data) => {
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            if let Some(value) = data.namespace {
                cb("namespace", ObservableField::Node(value));
            }
        }
        NodeData::JsxOpeningElement(data) => {
            if let Some(value) = data.attributes {
                cb("attributes", ObservableField::Node(value));
            }
            if let Some(value) = data.tag_name {
                cb("tagName", ObservableField::Node(value));
            }
            if let Some(value) = data.type_arguments {
                cb("typeArguments", ObservableField::NodeArray(value));
            }
        }
        NodeData::JsxSelfClosingElement(data) => {
            if let Some(value) = data.attributes {
                cb("attributes", ObservableField::Node(value));
            }
            if let Some(value) = data.tag_name {
                cb("tagName", ObservableField::Node(value));
            }
            if let Some(value) = data.type_arguments {
                cb("typeArguments", ObservableField::NodeArray(value));
            }
        }
        NodeData::JsxSpreadAttribute(data) => {
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
        }
        NodeData::JsxText(data) => {
            cb(
                "containsOnlyTriviaWhiteSpaces",
                ObservableField::Bool(data.contains_only_trivia_white_spaces),
            );
            cb("text", ObservableField::String(&data.text));
        }
        NodeData::LabeledStatement(data) => {
            if let Some(value) = data.label {
                cb("label", ObservableField::Node(value));
            }
            if let Some(value) = data.statement {
                cb("statement", ObservableField::Node(value));
            }
        }
        NodeData::LiteralType(data) => {
            if let Some(value) = data.literal {
                cb("literal", ObservableField::Node(value));
            }
        }
        NodeData::MappedType(data) => {
            if let Some(value) = data.members {
                cb("members", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.name_type {
                cb("nameType", ObservableField::Node(value));
            }
            if let Some(value) = data.question_token {
                cb("questionToken", ObservableField::Node(value));
            }
            if let Some(value) = data.readonly_token {
                cb("readonlyToken", ObservableField::Node(value));
            }
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
            if let Some(value) = data.type_parameter {
                cb("typeParameter", ObservableField::Node(value));
            }
        }
        NodeData::MetaProperty(data) => {
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
        }
        NodeData::MethodDeclaration(data) => {
            if let Some(value) = data.asterisk_token {
                cb("asteriskToken", ObservableField::Node(value));
            }
            if let Some(value) = data.body {
                cb("body", ObservableField::Node(value));
            }
            if let Some(value) = data.exclamation_token {
                cb("exclamationToken", ObservableField::Node(value));
            }
            if let Some(value) = data.modifiers {
                cb("modifiers", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            if let Some(value) = data.parameters {
                cb("parameters", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.question_token {
                cb("questionToken", ObservableField::Node(value));
            }
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
            if let Some(value) = data.type_parameters {
                cb("typeParameters", ObservableField::NodeArray(value));
            }
        }
        NodeData::MethodSignature(data) => {
            if let Some(value) = data.modifiers {
                cb("modifiers", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            if let Some(value) = data.parameters {
                cb("parameters", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.question_token {
                cb("questionToken", ObservableField::Node(value));
            }
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
            if let Some(value) = data.type_parameters {
                cb("typeParameters", ObservableField::NodeArray(value));
            }
        }
        NodeData::MissingDeclaration(data) => {
            if let Some(value) = data.modifiers {
                cb("modifiers", ObservableField::NodeArray(value));
            }
        }
        NodeData::ModuleBlock(data) => {
            if let Some(value) = data.statements {
                cb("statements", ObservableField::NodeArray(value));
            }
        }
        NodeData::ModuleDeclaration(data) => {
            if let Some(value) = data.body {
                cb("body", ObservableField::Node(value));
            }
            if let Some(value) = data.modifiers {
                cb("modifiers", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
        }
        NodeData::NamedExports(data) => {
            if let Some(value) = data.elements {
                cb("elements", ObservableField::NodeArray(value));
            }
        }
        NodeData::NamedImports(data) => {
            if let Some(value) = data.elements {
                cb("elements", ObservableField::NodeArray(value));
            }
        }
        NodeData::NamedTupleMember(data) => {
            if let Some(value) = data.dot_dot_dot_token {
                cb("dotDotDotToken", ObservableField::Node(value));
            }
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            if let Some(value) = data.question_token {
                cb("questionToken", ObservableField::Node(value));
            }
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
        }
        NodeData::NamespaceExport(data) => {
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
        }
        NodeData::NamespaceExportDeclaration(data) => {
            if let Some(value) = data.modifiers {
                cb("modifiers", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
        }
        NodeData::NamespaceImport(data) => {
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
        }
        NodeData::NewExpression(data) => {
            if let Some(value) = data.arguments {
                cb("arguments", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
            if let Some(value) = data.question_dot_token {
                cb("questionDotToken", ObservableField::Node(value));
            }
            if let Some(value) = data.type_arguments {
                cb("typeArguments", ObservableField::NodeArray(value));
            }
        }
        NodeData::NoSubstitutionTemplateLiteral(data) => {
            if let Some(value) = data.raw_text.as_deref() {
                cb("rawText", ObservableField::String(value));
            }
            cb("text", ObservableField::String(&data.text));
        }
        NodeData::NonNullExpression(data) => {
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
        }
        NodeData::NotEmittedStatement(_data) => {}
        NodeData::NumericLiteral(data) => {
            cb("text", ObservableField::String(&data.text));
        }
        NodeData::ObjectBindingPattern(data) => {
            if let Some(value) = data.elements {
                cb("elements", ObservableField::NodeArray(value));
            }
        }
        NodeData::ObjectLiteralExpression(data) => {
            if let Some(value) = data.properties {
                cb("properties", ObservableField::NodeArray(value));
            }
        }
        NodeData::OmittedExpression(_data) => {}
        NodeData::OptionalType(data) => {
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
        }
        NodeData::Parameter(data) => {
            if let Some(value) = data.dot_dot_dot_token {
                cb("dotDotDotToken", ObservableField::Node(value));
            }
            if let Some(value) = data.initializer {
                cb("initializer", ObservableField::Node(value));
            }
            if let Some(value) = data.modifiers {
                cb("modifiers", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            if let Some(value) = data.question_token {
                cb("questionToken", ObservableField::Node(value));
            }
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
        }
        NodeData::ParenthesizedExpression(data) => {
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
        }
        NodeData::ParenthesizedType(data) => {
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
        }
        NodeData::PartiallyEmittedExpression(data) => {
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
        }
        NodeData::PostfixUnaryExpression(data) => {
            if let Some(value) = data.operand {
                cb("operand", ObservableField::Node(value));
            }
        }
        NodeData::PrefixUnaryExpression(data) => {
            if let Some(value) = data.operand {
                cb("operand", ObservableField::Node(value));
            }
        }
        NodeData::PrivateIdentifier(data) => {
            cb("escapedText", ObservableField::String(&data.escaped_text));
        }
        NodeData::PropertyAccessExpression(data) => {
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            if let Some(value) = data.question_dot_token {
                cb("questionDotToken", ObservableField::Node(value));
            }
        }
        NodeData::PropertyAssignment(data) => {
            if let Some(value) = data.exclamation_token {
                cb("exclamationToken", ObservableField::Node(value));
            }
            if let Some(value) = data.initializer {
                cb("initializer", ObservableField::Node(value));
            }
            if let Some(value) = data.modifiers {
                cb("modifiers", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            if let Some(value) = data.question_token {
                cb("questionToken", ObservableField::Node(value));
            }
        }
        NodeData::PropertyDeclaration(data) => {
            if let Some(value) = data.exclamation_token {
                cb("exclamationToken", ObservableField::Node(value));
            }
            if let Some(value) = data.initializer {
                cb("initializer", ObservableField::Node(value));
            }
            if let Some(value) = data.modifiers {
                cb("modifiers", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            if let Some(value) = data.question_token {
                cb("questionToken", ObservableField::Node(value));
            }
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
        }
        NodeData::PropertySignature(data) => {
            if let Some(value) = data.initializer {
                cb("initializer", ObservableField::Node(value));
            }
            if let Some(value) = data.modifiers {
                cb("modifiers", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            if let Some(value) = data.question_token {
                cb("questionToken", ObservableField::Node(value));
            }
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
        }
        NodeData::QualifiedName(data) => {
            if let Some(value) = data.left {
                cb("left", ObservableField::Node(value));
            }
            if let Some(value) = data.right {
                cb("right", ObservableField::Node(value));
            }
        }
        NodeData::RegularExpressionLiteral(data) => {
            if let Some(value) = data.is_unterminated {
                cb("isUnterminated", ObservableField::Bool(value));
            }
            cb("text", ObservableField::String(&data.text));
        }
        NodeData::RestType(data) => {
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
        }
        NodeData::ReturnStatement(data) => {
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
        }
        NodeData::SatisfiesExpression(data) => {
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
        }
        NodeData::SetAccessor(data) => {
            if let Some(value) = data.body {
                cb("body", ObservableField::Node(value));
            }
            if let Some(value) = data.modifiers {
                cb("modifiers", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            if let Some(value) = data.parameters {
                cb("parameters", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
            if let Some(value) = data.type_parameters {
                cb("typeParameters", ObservableField::NodeArray(value));
            }
        }
        NodeData::ShorthandPropertyAssignment(data) => {
            if let Some(value) = data.equals_token {
                cb("equalsToken", ObservableField::Node(value));
            }
            if let Some(value) = data.exclamation_token {
                cb("exclamationToken", ObservableField::Node(value));
            }
            if let Some(value) = data.modifiers {
                cb("modifiers", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            if let Some(value) = data.object_assignment_initializer {
                cb("objectAssignmentInitializer", ObservableField::Node(value));
            }
            if let Some(value) = data.question_token {
                cb("questionToken", ObservableField::Node(value));
            }
        }
        NodeData::SourceFile(data) => {
            if let Some(value) = data.end_of_file_token {
                cb("endOfFileToken", ObservableField::Node(value));
            }
            if let Some(value) = data.statements {
                cb("statements", ObservableField::NodeArray(value));
            }
        }
        NodeData::SpreadAssignment(data) => {
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
        }
        NodeData::SpreadElement(data) => {
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
        }
        NodeData::StringLiteral(data) => {
            if let Some(value) = data.has_extended_unicode_escape {
                cb("hasExtendedUnicodeEscape", ObservableField::Bool(value));
            }
            cb("text", ObservableField::String(&data.text));
        }
        NodeData::SwitchStatement(data) => {
            if let Some(value) = data.case_block {
                cb("caseBlock", ObservableField::Node(value));
            }
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
        }
        NodeData::SyntaxList(_data) => {}
        NodeData::TaggedTemplateExpression(data) => {
            if let Some(value) = data.question_dot_token {
                cb("questionDotToken", ObservableField::Node(value));
            }
            if let Some(value) = data.tag {
                cb("tag", ObservableField::Node(value));
            }
            if let Some(value) = data.template {
                cb("template", ObservableField::Node(value));
            }
            if let Some(value) = data.type_arguments {
                cb("typeArguments", ObservableField::NodeArray(value));
            }
        }
        NodeData::TemplateExpression(data) => {
            if let Some(value) = data.head {
                cb("head", ObservableField::Node(value));
            }
            if let Some(value) = data.template_spans {
                cb("templateSpans", ObservableField::NodeArray(value));
            }
        }
        NodeData::TemplateHead(data) => {
            if let Some(value) = data.raw_text.as_deref() {
                cb("rawText", ObservableField::String(value));
            }
            cb("text", ObservableField::String(&data.text));
        }
        NodeData::TemplateLiteralType(data) => {
            if let Some(value) = data.head {
                cb("head", ObservableField::Node(value));
            }
            if let Some(value) = data.template_spans {
                cb("templateSpans", ObservableField::NodeArray(value));
            }
        }
        NodeData::TemplateLiteralTypeSpan(data) => {
            if let Some(value) = data.literal {
                cb("literal", ObservableField::Node(value));
            }
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
        }
        NodeData::TemplateMiddle(data) => {
            if let Some(value) = data.raw_text.as_deref() {
                cb("rawText", ObservableField::String(value));
            }
            cb("text", ObservableField::String(&data.text));
        }
        NodeData::TemplateSpan(data) => {
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
            if let Some(value) = data.literal {
                cb("literal", ObservableField::Node(value));
            }
        }
        NodeData::TemplateTail(data) => {
            if let Some(value) = data.raw_text.as_deref() {
                cb("rawText", ObservableField::String(value));
            }
            cb("text", ObservableField::String(&data.text));
        }
        NodeData::ThrowStatement(data) => {
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
        }
        NodeData::TryStatement(data) => {
            if let Some(value) = data.catch_clause {
                cb("catchClause", ObservableField::Node(value));
            }
            if let Some(value) = data.finally_block {
                cb("finallyBlock", ObservableField::Node(value));
            }
            if let Some(value) = data.try_block {
                cb("tryBlock", ObservableField::Node(value));
            }
        }
        NodeData::TupleType(data) => {
            if let Some(value) = data.elements {
                cb("elements", ObservableField::NodeArray(value));
            }
        }
        NodeData::TypeAliasDeclaration(data) => {
            if let Some(value) = data.modifiers {
                cb("modifiers", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
            if let Some(value) = data.type_parameters {
                cb("typeParameters", ObservableField::NodeArray(value));
            }
        }
        NodeData::TypeAssertionExpression(data) => {
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
        }
        NodeData::TypeLiteral(data) => {
            if let Some(value) = data.members {
                cb("members", ObservableField::NodeArray(value));
            }
        }
        NodeData::TypeOfExpression(data) => {
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
        }
        NodeData::TypeOperator(data) => {
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
        }
        NodeData::TypeParameter(data) => {
            if let Some(value) = data.constraint {
                cb("constraint", ObservableField::Node(value));
            }
            if let Some(value) = data.r#default {
                cb("default", ObservableField::Node(value));
            }
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
            if let Some(value) = data.modifiers {
                cb("modifiers", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
        }
        NodeData::TypePredicate(data) => {
            if let Some(value) = data.asserts_modifier {
                cb("assertsModifier", ObservableField::Node(value));
            }
            if let Some(value) = data.parameter_name {
                cb("parameterName", ObservableField::Node(value));
            }
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
        }
        NodeData::TypeQuery(data) => {
            if let Some(value) = data.expr_name {
                cb("exprName", ObservableField::Node(value));
            }
            if let Some(value) = data.type_arguments {
                cb("typeArguments", ObservableField::NodeArray(value));
            }
        }
        NodeData::TypeReference(data) => {
            if let Some(value) = data.type_arguments {
                cb("typeArguments", ObservableField::NodeArray(value));
            }
            if let Some(value) = data.type_name {
                cb("typeName", ObservableField::Node(value));
            }
        }
        NodeData::UnionType(data) => {
            if let Some(value) = data.types {
                cb("types", ObservableField::NodeArray(value));
            }
        }
        NodeData::VariableDeclaration(data) => {
            if let Some(value) = data.exclamation_token {
                cb("exclamationToken", ObservableField::Node(value));
            }
            if let Some(value) = data.initializer {
                cb("initializer", ObservableField::Node(value));
            }
            if let Some(value) = data.name {
                cb("name", ObservableField::Node(value));
            }
            if let Some(value) = data.r#type {
                cb("type", ObservableField::Node(value));
            }
        }
        NodeData::VariableDeclarationList(data) => {
            if let Some(value) = data.declarations {
                cb("declarations", ObservableField::NodeArray(value));
            }
        }
        NodeData::VariableStatement(data) => {
            if let Some(value) = data.declaration_list {
                cb("declarationList", ObservableField::Node(value));
            }
            if let Some(value) = data.modifiers {
                cb("modifiers", ObservableField::NodeArray(value));
            }
        }
        NodeData::VoidExpression(data) => {
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
        }
        NodeData::WhileStatement(data) => {
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
            if let Some(value) = data.statement {
                cb("statement", ObservableField::Node(value));
            }
        }
        NodeData::WithStatement(data) => {
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
            if let Some(value) = data.statement {
                cb("statement", ObservableField::Node(value));
            }
        }
        NodeData::YieldExpression(data) => {
            if let Some(value) = data.asterisk_token {
                cb("asteriskToken", ObservableField::Node(value));
            }
            if let Some(value) = data.expression {
                cb("expression", ObservableField::Node(value));
            }
        }
    }
}

fn emit_jsdoc_comment<'a, F>(name: &'static str, value: &'a JSDocComment, cb: &mut F)
where
    F: FnMut(&'static str, ObservableField<'a>),
{
    match value {
        JSDocComment::Text(text) => cb(name, ObservableField::String(text)),
        JSDocComment::Nodes(nodes) => cb(name, ObservableField::NodeArray(*nodes)),
    }
}
