// @generated by `cargo xtask codegen nodes`. Do not edit by hand.

use crate::arena::SyntaxIdentityRelocation;
use crate::nodes::{JSDocComment, NodeData};
use tsc_types::IdentityError;

pub(crate) fn relocate_node_data(
    data: &mut NodeData,
    relocation: &SyntaxIdentityRelocation,
) -> Result<(), IdentityError> {
    match data {
        NodeData::Token => Ok(()),
        NodeData::ArrayBindingPattern(data) => {
            if let Some(id) = &mut data.elements {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::ArrayLiteralExpression(data) => {
            if let Some(id) = &mut data.elements {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::ArrayType(data) => {
            if let Some(id) = &mut data.element_type {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::ArrowFunction(data) => {
            if let Some(id) = &mut data.type_parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.body {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.modifiers {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.equals_greater_than_token {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::AsExpression(data) => {
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::AwaitExpression(data) => {
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::BigIntLiteral(_data) => Ok(()),
        NodeData::BinaryExpression(data) => {
            if let Some(id) = &mut data.left {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.operator_token {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.right {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::BindingElement(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.property_name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.dot_dot_dot_token {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.initializer {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::Block(data) => {
            if let Some(id) = &mut data.statements {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::BreakStatement(data) => {
            if let Some(id) = &mut data.label {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::CallExpression(data) => {
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.question_dot_token {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.type_arguments {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.arguments {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::CallSignature(data) => {
            if let Some(id) = &mut data.type_parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::CaseBlock(data) => {
            if let Some(id) = &mut data.clauses {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::CaseClause(data) => {
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.statements {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::CatchClause(data) => {
            if let Some(id) = &mut data.variable_declaration {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.block {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::ClassDeclaration(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.type_parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.heritage_clauses {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.members {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.modifiers {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::ClassExpression(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.type_parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.heritage_clauses {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.members {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.modifiers {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::ClassStaticBlockDeclaration(data) => {
            if let Some(id) = &mut data.body {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.modifiers {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::CommaListExpression(data) => {
            if let Some(id) = &mut data.elements {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::ComputedPropertyName(data) => {
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::ConditionalExpression(data) => {
            if let Some(id) = &mut data.condition {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.question_token {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.when_true {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.colon_token {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.when_false {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::ConditionalType(data) => {
            if let Some(id) = &mut data.check_type {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.extends_type {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.true_type {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.false_type {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::ConstructSignature(data) => {
            if let Some(id) = &mut data.type_parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::Constructor(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.type_parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.body {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.modifiers {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::ConstructorType(data) => {
            if let Some(id) = &mut data.type_parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.modifiers {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::ContinueStatement(data) => {
            if let Some(id) = &mut data.label {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::DebuggerStatement(_data) => Ok(()),
        NodeData::Decorator(data) => {
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::DefaultClause(data) => {
            if let Some(id) = &mut data.statements {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::DeleteExpression(data) => {
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::DoStatement(data) => {
            if let Some(id) = &mut data.statement {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::ElementAccessExpression(data) => {
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.question_dot_token {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.argument_expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::EmptyStatement(_data) => Ok(()),
        NodeData::EnumDeclaration(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.modifiers {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.members {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::EnumMember(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.initializer {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::ExportAssignment(data) => {
            if let Some(id) = &mut data.modifiers {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::ExportDeclaration(data) => {
            if let Some(id) = &mut data.modifiers {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.export_clause {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.module_specifier {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.attributes {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::ExportSpecifier(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.property_name {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::ExpressionStatement(data) => {
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::ExpressionWithTypeArguments(data) => {
            if let Some(id) = &mut data.type_arguments {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::ExternalModuleReference(data) => {
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::ForInStatement(data) => {
            if let Some(id) = &mut data.statement {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.initializer {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::ForOfStatement(data) => {
            if let Some(id) = &mut data.statement {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.await_modifier {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.initializer {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::ForStatement(data) => {
            if let Some(id) = &mut data.statement {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.initializer {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.condition {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.incrementor {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::FunctionDeclaration(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.type_parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.asterisk_token {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.body {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.modifiers {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::FunctionExpression(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.type_parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.asterisk_token {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.body {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.modifiers {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::FunctionType(data) => {
            if let Some(id) = &mut data.type_parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.modifiers {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::GetAccessor(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.type_parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.body {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.modifiers {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::HeritageClause(data) => {
            if let Some(id) = &mut data.types {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::Identifier(_data) => Ok(()),
        NodeData::IfStatement(data) => {
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.then_statement {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.else_statement {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::ImportAttribute(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.value {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::ImportAttributes(data) => {
            if let Some(id) = &mut data.elements {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::ImportClause(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.named_bindings {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::ImportDeclaration(data) => {
            if let Some(id) = &mut data.modifiers {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.import_clause {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.module_specifier {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.attributes {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::ImportEqualsDeclaration(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.modifiers {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.module_reference {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::ImportSpecifier(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.property_name {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::ImportType(data) => {
            if let Some(id) = &mut data.type_arguments {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.argument {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.attributes {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.qualifier {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::ImportTypeAssertionContainer(data) => {
            if let Some(id) = &mut data.assert_clause {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::IndexSignature(data) => {
            if let Some(id) = &mut data.type_parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.modifiers {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::IndexedAccessType(data) => {
            if let Some(id) = &mut data.object_type {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.index_type {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::InferType(data) => {
            if let Some(id) = &mut data.type_parameter {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::InterfaceDeclaration(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.modifiers {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.type_parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.heritage_clauses {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.members {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::IntersectionType(data) => {
            if let Some(id) = &mut data.types {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::JSDoc(data) => {
            if let Some(id) = &mut data.tags {
                relocation.node_array(id)?;
            }
            if let Some(JSDocComment::Nodes(id)) = &mut data.comment {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::JSDocAllType(_data) => Ok(()),
        NodeData::JSDocAugmentsTag(data) => {
            if let Some(id) = &mut data.tag_name {
                relocation.node(id)?;
            }
            if let Some(JSDocComment::Nodes(id)) = &mut data.comment {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.class {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JSDocAuthorTag(data) => {
            if let Some(id) = &mut data.tag_name {
                relocation.node(id)?;
            }
            if let Some(JSDocComment::Nodes(id)) = &mut data.comment {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::JSDocCallbackTag(data) => {
            if let Some(id) = &mut data.tag_name {
                relocation.node(id)?;
            }
            if let Some(JSDocComment::Nodes(id)) = &mut data.comment {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.full_name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.type_expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JSDocClassTag(data) => {
            if let Some(id) = &mut data.tag_name {
                relocation.node(id)?;
            }
            if let Some(JSDocComment::Nodes(id)) = &mut data.comment {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::JSDocDeprecatedTag(data) => {
            if let Some(id) = &mut data.tag_name {
                relocation.node(id)?;
            }
            if let Some(JSDocComment::Nodes(id)) = &mut data.comment {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::JSDocEnumTag(data) => {
            if let Some(id) = &mut data.tag_name {
                relocation.node(id)?;
            }
            if let Some(JSDocComment::Nodes(id)) = &mut data.comment {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.type_expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JSDocFunctionType(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.type_parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JSDocImplementsTag(data) => {
            if let Some(id) = &mut data.tag_name {
                relocation.node(id)?;
            }
            if let Some(JSDocComment::Nodes(id)) = &mut data.comment {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.class {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JSDocImportTag(data) => {
            if let Some(id) = &mut data.tag_name {
                relocation.node(id)?;
            }
            if let Some(JSDocComment::Nodes(id)) = &mut data.comment {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.import_clause {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.module_specifier {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.attributes {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JSDocLink(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JSDocLinkCode(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JSDocLinkPlain(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JSDocMemberName(data) => {
            if let Some(id) = &mut data.left {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.right {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JSDocNameReference(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JSDocNamepathType(data) => {
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JSDocNonNullableType(data) => {
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JSDocNullableType(data) => {
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JSDocOptionalType(data) => {
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JSDocOverloadTag(data) => {
            if let Some(id) = &mut data.tag_name {
                relocation.node(id)?;
            }
            if let Some(JSDocComment::Nodes(id)) = &mut data.comment {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.type_expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JSDocOverrideTag(data) => {
            if let Some(id) = &mut data.tag_name {
                relocation.node(id)?;
            }
            if let Some(JSDocComment::Nodes(id)) = &mut data.comment {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::JSDocParameterTag(data) => {
            if let Some(id) = &mut data.tag_name {
                relocation.node(id)?;
            }
            if let Some(JSDocComment::Nodes(id)) = &mut data.comment {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.type_expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JSDocPrivateTag(data) => {
            if let Some(id) = &mut data.tag_name {
                relocation.node(id)?;
            }
            if let Some(JSDocComment::Nodes(id)) = &mut data.comment {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::JSDocPropertyTag(data) => {
            if let Some(id) = &mut data.tag_name {
                relocation.node(id)?;
            }
            if let Some(JSDocComment::Nodes(id)) = &mut data.comment {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.type_expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JSDocProtectedTag(data) => {
            if let Some(id) = &mut data.tag_name {
                relocation.node(id)?;
            }
            if let Some(JSDocComment::Nodes(id)) = &mut data.comment {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::JSDocPublicTag(data) => {
            if let Some(id) = &mut data.tag_name {
                relocation.node(id)?;
            }
            if let Some(JSDocComment::Nodes(id)) = &mut data.comment {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::JSDocReadonlyTag(data) => {
            if let Some(id) = &mut data.tag_name {
                relocation.node(id)?;
            }
            if let Some(JSDocComment::Nodes(id)) = &mut data.comment {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::JSDocReturnTag(data) => {
            if let Some(id) = &mut data.tag_name {
                relocation.node(id)?;
            }
            if let Some(JSDocComment::Nodes(id)) = &mut data.comment {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.type_expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JSDocSatisfiesTag(data) => {
            if let Some(id) = &mut data.tag_name {
                relocation.node(id)?;
            }
            if let Some(JSDocComment::Nodes(id)) = &mut data.comment {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.type_expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JSDocSeeTag(data) => {
            if let Some(id) = &mut data.tag_name {
                relocation.node(id)?;
            }
            if let Some(JSDocComment::Nodes(id)) = &mut data.comment {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JSDocSignature(data) => {
            if let Some(id) = &mut data.type_parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JSDocTag(data) => {
            if let Some(id) = &mut data.tag_name {
                relocation.node(id)?;
            }
            if let Some(JSDocComment::Nodes(id)) = &mut data.comment {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::JSDocTemplateTag(data) => {
            if let Some(id) = &mut data.tag_name {
                relocation.node(id)?;
            }
            if let Some(JSDocComment::Nodes(id)) = &mut data.comment {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.constraint {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.type_parameters {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::JSDocText(_data) => Ok(()),
        NodeData::JSDocThisTag(data) => {
            if let Some(id) = &mut data.tag_name {
                relocation.node(id)?;
            }
            if let Some(JSDocComment::Nodes(id)) = &mut data.comment {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.type_expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JSDocThrowsTag(data) => {
            if let Some(id) = &mut data.tag_name {
                relocation.node(id)?;
            }
            if let Some(JSDocComment::Nodes(id)) = &mut data.comment {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.type_expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JSDocTypeExpression(data) => {
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JSDocTypeLiteral(data) => {
            if let Some(id) = &mut data.js_doc_property_tags {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::JSDocTypeTag(data) => {
            if let Some(id) = &mut data.tag_name {
                relocation.node(id)?;
            }
            if let Some(JSDocComment::Nodes(id)) = &mut data.comment {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.type_expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JSDocTypedefTag(data) => {
            if let Some(id) = &mut data.tag_name {
                relocation.node(id)?;
            }
            if let Some(JSDocComment::Nodes(id)) = &mut data.comment {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.full_name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.type_expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JSDocUnknownType(_data) => Ok(()),
        NodeData::JSDocVariadicType(data) => {
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JsxAttribute(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.initializer {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JsxAttributes(data) => {
            if let Some(id) = &mut data.properties {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::JsxClosingElement(data) => {
            if let Some(id) = &mut data.tag_name {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JsxElement(data) => {
            if let Some(id) = &mut data.opening_element {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.children {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.closing_element {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JsxExpression(data) => {
            if let Some(id) = &mut data.dot_dot_dot_token {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JsxFragment(data) => {
            if let Some(id) = &mut data.opening_fragment {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.children {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.closing_fragment {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JsxNamespacedName(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.namespace {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JsxOpeningElement(data) => {
            if let Some(id) = &mut data.tag_name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.type_arguments {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.attributes {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JsxSelfClosingElement(data) => {
            if let Some(id) = &mut data.tag_name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.type_arguments {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.attributes {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JsxSpreadAttribute(data) => {
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::JsxText(_data) => Ok(()),
        NodeData::LabeledStatement(data) => {
            if let Some(id) = &mut data.label {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.statement {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::LiteralType(data) => {
            if let Some(id) = &mut data.literal {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::MappedType(data) => {
            if let Some(id) = &mut data.readonly_token {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.type_parameter {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.name_type {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.question_token {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.members {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::MetaProperty(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::MethodDeclaration(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.type_parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.asterisk_token {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.question_token {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.exclamation_token {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.body {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.modifiers {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::MethodSignature(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.type_parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.question_token {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.modifiers {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::MissingDeclaration(data) => {
            if let Some(id) = &mut data.modifiers {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::ModuleBlock(data) => {
            if let Some(id) = &mut data.statements {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::ModuleDeclaration(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.modifiers {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.body {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::NamedExports(data) => {
            if let Some(id) = &mut data.elements {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::NamedImports(data) => {
            if let Some(id) = &mut data.elements {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::NamedTupleMember(data) => {
            if let Some(id) = &mut data.dot_dot_dot_token {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.question_token {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::NamespaceExport(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::NamespaceExportDeclaration(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.modifiers {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::NamespaceImport(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::NewExpression(data) => {
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.type_arguments {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.arguments {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.question_dot_token {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::NoSubstitutionTemplateLiteral(_data) => Ok(()),
        NodeData::NonNullExpression(data) => {
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::NumericLiteral(_data) => Ok(()),
        NodeData::ObjectBindingPattern(data) => {
            if let Some(id) = &mut data.elements {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::ObjectLiteralExpression(data) => {
            if let Some(id) = &mut data.properties {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::OmittedExpression(_data) => Ok(()),
        NodeData::OptionalType(data) => {
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::Parameter(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.modifiers {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.dot_dot_dot_token {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.question_token {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.initializer {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::ParenthesizedExpression(data) => {
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::ParenthesizedType(data) => {
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::PartiallyEmittedExpression(data) => {
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::PostfixUnaryExpression(data) => {
            if let Some(id) = &mut data.operand {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::PrefixUnaryExpression(data) => {
            if let Some(id) = &mut data.operand {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::PrivateIdentifier(_data) => Ok(()),
        NodeData::PropertyAccessExpression(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.question_dot_token {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::PropertyAssignment(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.initializer {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.modifiers {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.question_token {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.exclamation_token {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::PropertyDeclaration(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.modifiers {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.question_token {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.exclamation_token {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.initializer {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::PropertySignature(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.question_token {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.modifiers {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.initializer {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::QualifiedName(data) => {
            if let Some(id) = &mut data.left {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.right {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::RegularExpressionLiteral(_data) => Ok(()),
        NodeData::RestType(data) => {
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::ReturnStatement(data) => {
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::SatisfiesExpression(data) => {
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::SetAccessor(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.type_parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.body {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.modifiers {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::ShorthandPropertyAssignment(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.equals_token {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.object_assignment_initializer {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.modifiers {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.question_token {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.exclamation_token {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::SourceFile(data) => {
            if let Some(id) = &mut data.statements {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.end_of_file_token {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::SpreadAssignment(data) => {
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::SpreadElement(data) => {
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::StringLiteral(_data) => Ok(()),
        NodeData::SwitchStatement(data) => {
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.case_block {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::SyntaxList(_data) => Ok(()),
        NodeData::TaggedTemplateExpression(data) => {
            if let Some(id) = &mut data.tag {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.type_arguments {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.template {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.question_dot_token {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::TemplateExpression(data) => {
            if let Some(id) = &mut data.head {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.template_spans {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::TemplateHead(_data) => Ok(()),
        NodeData::TemplateLiteralType(data) => {
            if let Some(id) = &mut data.head {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.template_spans {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::TemplateLiteralTypeSpan(data) => {
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.literal {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::TemplateMiddle(_data) => Ok(()),
        NodeData::TemplateSpan(data) => {
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.literal {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::TemplateTail(_data) => Ok(()),
        NodeData::ThrowStatement(data) => {
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::TryStatement(data) => {
            if let Some(id) = &mut data.try_block {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.catch_clause {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.finally_block {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::TupleType(data) => {
            if let Some(id) = &mut data.elements {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::TypeAliasDeclaration(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.modifiers {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.type_parameters {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::TypeAssertionExpression(data) => {
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::TypeLiteral(data) => {
            if let Some(id) = &mut data.members {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::TypeOfExpression(data) => {
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::TypeOperator(data) => {
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::TypeParameter(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.modifiers {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.constraint {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.r#default {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::TypePredicate(data) => {
            if let Some(id) = &mut data.asserts_modifier {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.parameter_name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::TypeQuery(data) => {
            if let Some(id) = &mut data.type_arguments {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.expr_name {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::TypeReference(data) => {
            if let Some(id) = &mut data.type_arguments {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.type_name {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::UnionType(data) => {
            if let Some(id) = &mut data.types {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::VariableDeclaration(data) => {
            if let Some(id) = &mut data.name {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.exclamation_token {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.r#type {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.initializer {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::VariableDeclarationList(data) => {
            if let Some(id) = &mut data.declarations {
                relocation.node_array(id)?;
            }
            Ok(())
        }
        NodeData::VariableStatement(data) => {
            if let Some(id) = &mut data.modifiers {
                relocation.node_array(id)?;
            }
            if let Some(id) = &mut data.declaration_list {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::VoidExpression(data) => {
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::WhileStatement(data) => {
            if let Some(id) = &mut data.statement {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::WithStatement(data) => {
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.statement {
                relocation.node(id)?;
            }
            Ok(())
        }
        NodeData::YieldExpression(data) => {
            if let Some(id) = &mut data.asterisk_token {
                relocation.node(id)?;
            }
            if let Some(id) = &mut data.expression {
                relocation.node(id)?;
            }
            Ok(())
        }
    }
}
