from pathlib import Path
import json,subprocess,hashlib,time
R=Path('/Users/hiramatsu/dev/tsc-rs-emitter-final-variable-producer-prep');O=Path('/tmp/emitter-module-boundary-observe-r408');O.mkdir(exist_ok=False)
s=(R/'scripts/observe-token-comment-phases.mjs').read_text();helper=s[s.index('function diagnostic(d)'):s.index('const cases = inputs.map')]
template=json.loads((R/'crates/compiler/tests/fixtures/token-comment-phases.json').read_bytes())['cases'][0]['options'];template.update(target=99,module=99,declaration=True,declarationMap=True,emitDeclarationOnly=False,removeComments=False)
shapes=[('import-'+p.replace(' ','-'),p+" /* a */ import /* b */ './dep';\n") for p in ['export','declare','public','async','declare export']]+[('export-star-'+p,p+" /* a */ export /* b */ * /* c */ from /* d */ './dep';\n") for p in ['export','declare','public','async']]+[('assignment-'+p.replace(' ','-'),p+' /* a */ export /* b */ default /* c */ 1;\n') for p in ['export','async','declare export']]
inputs=[{'case_id':'module-boundary/'+n,'roots':['/project/main.ts'],'files':[{'path':'/project/main.ts','text':t}],'options':template} for n,t in shapes]
source="import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';\n"+f"import ts from '{R}/vendor/typescript-6.0.3/lib/typescript.js';\nimport {{createHermeticDirectoryOverlay}} from '{R}/crates/oracle/vfs-directory-overlay.mjs';\nconst root={json.dumps(str(R))};const inputs={json.dumps(inputs)};\n"+helper+f'''const cases=inputs.map(input=>{{const first=observe(input);assert.deepEqual(observe(input),first,input.case_id);console.log(input.case_id);return {{...input,typescript_observation:first}};}});fs.writeFileSync({json.dumps(str(O/'oracle.json'))},JSON.stringify({{typescript:ts.version,repetitions:2,cases}},null,2)+'\\n');'''
(O/'observe.mjs').write_text(source);report={'scope':'Independent complete TypeScript commands for adjacent retained-modifier cause audit. No canonical mutation; not native success evidence.','head':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip(),'cases':len(inputs),'helper_source_sha256':hashlib.sha256((R/'scripts/observe-token-comment-phases.mjs').read_bytes()).hexdigest()};t=time.monotonic()
with (O/'oracle.log').open('w') as f:report['oracle_exit']=subprocess.run(['taskpolicy','-b','nice','-n','15','node',O/'observe.mjs'],cwd=R,stdout=f,stderr=subprocess.STDOUT).returncode
report['seconds']=time.monotonic()-t;(O/'manifest.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report))
