[package]
name = "tsc-rs-emitter"
version.workspace = true
edition.workspace = true
license.workspace = true

[package.metadata.tsc-rs]
role = "emitter"
dev-profile-opt-level = 3

[lib]
name = "tsc_emitter"
path = "src/lib.rs"

[dependencies]
tsc-diagnostics.workspace = true
tsc-program.workspace = true
tsc-syntax.workspace = true
tsc-types.workspace = true

[dev-dependencies]
serde_json = "1.0"

[lints]
workspace = true
