[package]
name = "tsc-rs-syntax"
version.workspace = true
edition.workspace = true
license.workspace = true

[package.metadata.tsc-rs]
role = "syntax"
dev-profile-opt-level = 3

[lib]
name = "tsc_syntax"
path = "src/lib.rs"

[dependencies]
tsc-diagnostics.workspace = true
tsc-types.workspace = true

[dev-dependencies]
serde_json = "1.0"
stats_alloc = "0.1.10"
